### ISSUE TITLE
dropTargetStyle not updating.

### ISSUE THREAD

**Issue by MaddoxDevelopment** [isaacHagoel/svelte-dnd-action#111]
It appears that dropTargetStyle sets the styles one time when the dnd zone is initialized, but it never updates the styles, even when it calls my function to get the styles as I am dragging over the zone.

In the video below:

- When i first load the page, it sets my dropTargetStyle as ```{ 'background-color': 'white' }```, which is correct.
- When i drag over the dropzone, it gets new styles from my function (as observed by the console log), but it does not actually show them on the screen. The dropzone turns white (because of the initial styles), instead of the #f5f5f5 color that it should be.

Video example: https://streamable.com/w2c050

Code:

```
function dropzoneStyles() {
    console.log("considering", considering)
    if(considering) {
      console.log({ 'background-color': '#f5f5f5', padding: '3em' })
      return { 'background-color': '#f5f5f5', padding: '3em' }
    }
    if (form.fields.length === 1 && form.fields[0].type === "placeholder") {
      console.log({ 'background-color': 'white' })
      return { 'background-color': 'white' }
    }
    console.log({ 'background-color': '#f5f5f5', padding: '3em' })
    return { 'background-color': '#f5f5f5', padding: '3em' }
  }
```

```
<div
    style="padding-bottom: 1em"
    use:dndzone={{ items: form.fields, flipDurationMs: 300, transformDraggedElement, dropTargetStyle: dropzoneStyles() }}
    on:consider={handler}
    on:finalize={handler}>
```

**Comment by isaacHagoel** [comment]
True. That's a feature not a bug :)
The style applies when drag starts. When I reviewed it I noticed it will not be dynamically updated but I thought that it is actually a better to keep it simple until a need arises (if ever). The README should have been explicit about it I guess.
It should be super easy to add it in.
In action.js inside of the 'configure' function (which is called on every update), there is this block which is doing basically the same thing for a different param:
```
   if (isWorkingOnPreviousDrag && config.dropFromOthersDisabled !== dropFromOthersDisabled) {
            if (dropFromOthersDisabled) {
                styleInActiveDropZones([node], dz => dzToConfig.get(dz).dropTargetStyle);
            } else {
                styleActiveDropZones([node], dz => dzToConfig.get(dz).dropTargetStyle);
            }
        }
```
I think that checking whether dropTargetStyle has changed and if so running `styleInActiveDropZones` and then `styleActiveDropZones will have the desired effect.

**Comment by MaddoxDevelopment** [comment]
Gotcha, it seems like a useful feature, but up to you if you want it added to the lib, I can do that workaround for now locally.

**Comment by isaacHagoel** [comment]
Hi @MaddoxDevelopment,
Can you please checkout branch [111-drop-target-style-realtime-update](https://github.com/isaacHagoel/svelte-dnd-action/tree/111-drop-target-style-realtime-update) and see if it solves this issue for your usecase?
Thanks

**Comment by MaddoxDevelopment** [comment]
Hey @isaacHagoel, just tested it out, seemed to work well, thanks for updating that!
