### ISSUE TITLE
getting an error when importing using the Svelte.REPL. Any idea?

### ISSUE THREAD

**Issue by zahachtah** [isaacHagoel/svelte-dnd-action#158]
So I am trying to ```import {dndzone} from 'svelte-dnd-action' ````

in another component "Item.svelte" (used in the app linked to at the end)

and get 

```
'incrementActiveDropZoneCount' is not exported by ./constants.js, imported by https://unpkg.com/svelte-dnd-action@0.6.11/src/pointerAction.js
```

Any idea what this could be?

I am trying to embed dnd in this SubDivide framework by Rich Harris...

https://svelte.dev/repl/96e71816787449e892d504e0933cba88?version=3.29.0

**Comment by zahachtah** [comment]
Only with svelte.REPL, works fine when downloading the project and running locally. maybe not worth looking at?

**Comment by isaacHagoel** [comment]
I saw the REPL doing strange things before. 
Maybe it is some naming conflict or something. I will have a look

**Comment by isaacHagoel** [comment]
look and behold, the library has constants.js too. suspicious...
![image](https://user-images.githubusercontent.com/20507787/96385764-b7915180-11e1-11eb-9fdc-93dcba2a9a15.png)

**Comment by zahachtah** [comment]
see see..... no worries then, I run it locally and it's beautiful :-) really awesome component!!
