### ISSUE TITLE
Version 0.6.11 broke the ability to work within Sapper

### ISSUE THREAD

**Issue by Bighamster** [isaacHagoel/svelte-dnd-action#159]
because of this line (ssr doesn't have an access to document)

https://github.com/isaacHagoel/svelte-dnd-action/blob/5f0adc609bb6c99ead3c8187843bc50436cfc048/src/helpers/aria.js#L29

**Comment by isaacHagoel** [comment]
Thanks for letting me know. I didn't give SSR the attention it deserves. I will have a look. This shouldn't be hard to fix.

**Comment by isaacHagoel** [comment]
should be good now (version 0.6.12). @Bighamster please give it a shot

**Comment by Bighamster** [comment]
Thanks a lot. Works like a charm!
