### ISSUE TITLE
Disable keyboard ?

### ISSUE THREAD

**Issue by Tonton-Blax** [isaacHagoel/svelte-dnd-action#161]
Hi and first and foremost, congratulations for this fantastic lib. It fills a long-standing gap in svelte ecosystem and that's a good thing!

Now I've got this problem where I cannot figure a simple and elegant way to disable the keyboard events listeners of your lib. It's kind of important since I'm using svelte-dnd around text editors components :)

So if you (or anyone!) can give me information, I'm a buyer. 

Thanks and hats off

**Comment by isaacHagoel** [comment]
Hi @Tonton-Blax,
It will be super easy to add such an option but i didn't implement it so far because it means making your app inaccessible. 
Can you please provide more details about your usecase (or a repl)? Maybe we can come up with a way to make it work without sacrificing accessibility

**Comment by Tonton-Blax** [comment]
Thanks Isaac for such a quick reply! My code is such a mess right now that I'd find it difficult to REPLize.
So I can just hope the issue is readable enough with a messy code section.

`   <section use:dndzone={{items: $form.postes, flipDurationMs, dropTargetStyle:{outline:"5px dashed #246A73", height:"100%"} }} on:consider={handleSort} on:finalize={handleSort}>
    {#each $form.postes as poste, j (poste._id)}
    <div animate:flip="{{duration: flipDurationMs, dropTargetStyle:{"outline":"dashed 2px #246A73"},}}" >

    <div class="container">
      <div class="form-group field">
      
            <Text bind:props={ poste.detail } idx={poste._id} />
          
        <div class="columns bottomize">
            <Field>
              <Button
              on:click={rotateUnites(j)} on:click={refresh} type="is-primary">{poste.prix.uniteType}</Button>
            </Field>

          <div class="column right">
            {#if j === $form.postes.length -1 }
              <button class="button is-success" type="button" on:click={add}></button>
            {/if}
          </div>
        </div> 
      </div>
      </div>
    </div>
    {/each}
   </section>`

So, the important thing here is the 'Text' component which is a wrapper around the ['cl-editor'](https://github.com/nenadpnc/cl-editor) repo. I spared you from the usual frontend bells and whistles blinky buttons within the {each} scope, just enough to understand that this block is already an event listener giant party. I guess there might be a way to exclude the 'Text' component from the keyboard 'trap', but since deep inside this editor is yet another dependency I feel a bit discouraged.
But hey, I'm rather new to all this stuff (a late reconversion from video production to code, at 40yo, yes I'm insane) so what do I know ?

Anyway, if it suddenly gives you a magic idea like "Yeah just add this magic oneliner leaveMeAlone=true and you're good to go", please let me know :)

**Comment by Tonton-Blax** [comment]
Oh damn it sorry for the bad github code block formatting issue, I don't know which part this thing struggles to parse

**Comment by isaacHagoel** [comment]
I think I fixed it for you. check [this](https://svelte.dev/repl/56d790351a3b40e2b34c8df1a92423ec?version=3.24.1) out.
The magic is in line 19 of your Text component (stopping event propagation).
Keyboard drag still works normally when tabbing to the outer div (as it should)

**Comment by Tonton-Blax** [comment]
Thank you so much Isaac!
You know what's better than a magical one-liner ?
A magical one-liner noop! :+1: 
And now it's fully functional without any disability trade-off

**Comment by isaacHagoel** [comment]
My pleasure. Keep fighting the good fight

**Comment by isaacHagoel** [comment]
@Tonton-Blax 
with version 0.6.16 and above it should work out of the box without needing the magic solution

**Comment by Tonton-Blax** [comment]
Thanks :+1: 
Curious of how you did that though :)

**Comment by isaacHagoel** [comment]
If the key event (for enter or space) comes from a child and the child has
a 'value' property (which means it is a button or an input), the library
ignores it

**Comment by isaacHagoel** [comment]
actually i tested it now with your repl and i see it still doesn't work because in your case it is not an input element but a normal container with contenteditable true. will create an issue to fix (should be a tiny fix)

**Comment by isaacHagoel** [comment]
okay. now it is really fixed for your usecase (0.6.18)
