### ISSUE TITLE
Dragged content keyboard interactions broken

### ISSUE THREAD

**Issue by weeblr** [isaacHagoel/svelte-dnd-action#166]
Hi there, 

Many thanks for this work, very useful for me. I'm trying to use svelte-dnd-action to allow re-ordering of a table rows by the user.
This works fine for all mouse-based operations but breaks when the rows have interactive elements such as a checkbox.
Here is [a REPL](https://svelte.dev/repl/2140934732a14219975549076f11a10c?version=3.29.0).

Each row can be re-ordered fine and has an "Enabled" checkbox which can be clicked alright.

However, if you use the keyboard to focus the checkbox and press Enter or Space, instead of the checkbox being toggled, it's the  svelte-dnd-action wrapper that grabs the focus and a keyboard drag operation is started.

The problem comes from having a global keydown handler that starts the drag operation as soon as Enter/space is pressed. It should only do that if it is the draggable element itself that has focus, not if the focus is on one of its children. 
I have not been able to fix without breaking it all so for now I've just made a copy and added a flag to disable keyboard operation entirely.

Thanks for looking into it.

Best regards

**Comment by isaacHagoel** [comment]
Hi,
there is a simple solution. Do this:
```
<td>
  <input on:keydown|stopPropagation type="checkbox" id="enabled_{item.id}" name="enabled_{item.id}">
</td>
```
With that said. I should make the keyboard drag react only when the event happens on the parent element (rather than the parent or any of its children). will fix soon.

**Comment by weeblr** [comment]
Hi

Thanks, yes, it's likely better to fix that, it's kinda odd to have to modify each and every controls within the table. This is an ultra-simple example, in reality there are many svelte components involved and I would have to stop propagation at the correct level for each one.

I can live with disabled keyboard dnd for now as each item can also be re-ordered on the item "Edit" page.

**Comment by isaacHagoel** [comment]
Yes I will look into it. it is a simple fix except that it might break the "drag handles" example.
I will leave this issue open and update.

**Comment by weeblr** [comment]
Hi @isaacHagoel 

I give it another try and it seems to be better with this change in `function handleKeyDown` of `keyboardAction.js`:

```
function handleKeyDown(e) {
        console.debug("handling key down", e.key);
        if(!allDragTargets.has(e.target)) {
            // keyboard event is not on a draggable element, likely on a child
            return
        }
        switch (e.key) {
            case("Enter"):
            case(" "): {

...
```

I see no advserse effect, is this what could break your dragHandles example?

**Comment by isaacHagoel** [comment]
btw, while debugging i noticed that the `tr` elements don't look right when dragging them. i think it is because when they stop being a child of the table they loose some of their styling. another thing i will need to look at. first i see the library used on a table :)

**Comment by isaacHagoel** [comment]
(cont)
and regarding the fix u suggest. I was trying something similar within the same handler:
```
 if (e.target.value !== undefined) {
                    return;
  }
```
the idea is that we don't want any input element to trigger a drag but any other child (ex: a drag handle) should.
seems to be working. still playing with it.

**Comment by weeblr** [comment]
Hi

OK I see why you'd want some child elements to still be able to trigger a drag, I'll test this version as well.

As for the tr loosing style, yes, I struggled with that. Eventually what I did was to replace the entire tr with a styled div through "transformDraggedElement":

```
const msg = `<div style="width: 100%; text-align: center;font-weight: bold">${title}</div>`
draggedEl.innerHTML = msg;
draggedEl.style.display = 'flex'
draggedEl.style.justifyItems = 'center'
draggedEl.style.alignItems = 'center'
```

I added a background color to make it stand out and a title that reads something like "Move xxx after yyyy" or "Move xxx to first position". Works well.

**Comment by weeblr** [comment]
Hi

I see no adverse effect with your version of the code in my testing.

**Comment by isaacHagoel** [comment]
Thanks for checking and cool solution for the styling issue! 

I would want the lib to work for tables out of the box if possible (or warn people in the README if there is something fundamental that makes this impossible) . i will create another issue for that. 

About the original issue, I am pretty tired right now so probably not a great idea to rush and release the fix.
I will play with it some more tomorrow in various scenarios and if all looks good, I'll release it.

I wonder what should happen if someone decides to make buttons draggable or text inputs without any wrapper element...
Should space interact with the element, start dragging or both?
On the one hand, why would anyone do it, on the other hand I know someone will 😆

**Comment by weeblr** [comment]
>I would want the lib to work for tables out of the box if possible (or warn people in the README if there is something fundamental that makes this impossible) . i will create another issue for that.

Not sure how you can work this out in the general case. Maybe in my case where I only re-order items within the tbody? But what if you want to drag a row from one table to another? In any case, if the dragged item is not a child of that specific table anymore, it will basically looked unstyled. Going to be hard to handle all cases.

Maybe some suggestions on styling with transformDraggedElement would be helpful. How about having an option that implements this behavior automatically?

New options:
```
styleDraggedElement: true; // default to false; can also be a list of element types like ['tr', 'th',...]
styleDraggedElementTitle: (draggedEl, data, index) => {return 'Moving item #' + index}
```

And the library does this:

```
if(styleDraggedElement) {
const title = styleDraggedElementTitle(draggedEl, data, index)
const msg = `<div style="width: 100%; text-align: center;font-weight: bold">${title}</div>`
draggedEl.innerHTML = msg;
draggedEl.style.display = 'flex'
draggedEl.style.justifyItems = 'center'
draggedEl.style.alignItems = 'center'
}
```

User can still override the display by using transformDraggedElement but you can provide a default behavior, toggable by a config option. You could also enable this behavior automatically for tr element for instance. Or not.

**Comment by isaacHagoel** [comment]
@weeblr I can't prioritise the table styling atm but it still bothers me.
Other elements keep their style just fine thanks to the function in `styler.js` that copies the styles from the original element.
Maybe there are some styles that it misses.

**Comment by weeblr** [comment]
Hi
I don't know enough about the internals of this lib but if the dragged element is created outside of the dndzone, then it'd make sense copying the styling would not be enough and a tr outside of a parent tbody or table would lose its visual aspect. I see you create the dragged element with "cloneNode" but you don't "appendChild to the original element parent element, maybe that's needed? All that said, it's possible as others are doing it so it may have to do with how the dragged element is managed in general?

In the mean time, I noticed an issue related to that exact problem. As mentioned earlier, I'm using `transformDraggedElement` and replace the tr with a div and some styling. Works fine in general **but** when you drag the last row to another position, it looks like `transformDraggedElement` is not called right away but only **after** the dragged item has moved past another item.

Moving around any other item does not show cause this, it only happens with the last item in the table:

![ezgif-1-e32dbd3db6d2](https://user-images.githubusercontent.com/5846185/96974951-293b0980-151a-11eb-8e64-325cd8bd8322.gif)

Cheers

**Comment by isaacHagoel** [comment]
I think it's because when u pick the last item up, the table shrinks and it
is not over it anymore.
If it has padding bottom or another way to stay below the element it wont
happen (unless the user drags it super quickly out of the table).

**Comment by weeblr** [comment]
I think that's normal behavior for a table, tbody, etc Padding does not apply to table elements.
Most importantly remember that this is happening **only on the last row** because I'm overriding the draggedElement styling.
Without doing that, this happens on **all** rows, not just the last one.

**Comment by isaacHagoel** [comment]
TransformDraggedElement only kicks in when the dragged element enters the
area over the dndZone (can be a different transform for different zones).
When u drag any item except for the last it is still over the table.

About it happening all the time for table rows, i opened a separate issue
for that when we discovered it

**Comment by weeblr** [comment]
Isn't there a "shadow" element inserted in lieu of the dragged one to "keep the space"?

**Comment by weeblr** [comment]
> TransformDraggedElement only kicks in when the dragged element enters the
area over the dndZone (can be  different transform for different zones).

This is correct, I added a border to the table and when I start dragging, the dragged element is indeed taken out of the table so the table shrinks. TransformDraggedElement is called when the dragged element gets back onto the table. So maybe the entire issue is about the dragged element jsut being cloned and not being appended to the original element parent?

**Comment by isaacHagoel** [comment]
I dont think so. It can't stay a child of the original parent and as i
stated before, this problem seems unique to this situation. I will debug it
in details when i get to that issue (you're welcome to have a look of
course)

**Comment by weeblr** [comment]
No problem, hope you can sort it out.
