### ISSUE TITLE
<tr> styles are not preserved when removed from the table (on drag)

### ISSUE THREAD

**Issue by isaacHagoel** [isaacHagoel/svelte-dnd-action#167]
Example [here](https://svelte.dev/repl/959792e4586c4258b47096d019a4ddec?version=3.29.0)

**Comment by weeblr** [comment]
Hi @isaacHagoel 

Not sure you had a chance to look at that but I've been facing another, somewhat related issue: if the table I'm working with only has one single row and you try to re-order it, usually by mistake, then dnd crashes:

```
admin-dacd8460bb.js:19698 Uncaught TypeError: dropZones is not iterable
    at watchDraggedElement (admin-dacd8460bb.js:19698)
    at keepOriginalElementInDom (admin-dacd8460bb.js:19933)
```
Happening here:

```
function watchDraggedElement() {
        console.debug('watching dragged element');
        armWindowScroller();
        const dropZones = typeToDropZones.get(draggedElType);
        for (const dz of dropZones) {
            dz.addEventListener(DRAGGED_ENTERED_EVENT_NAME, handleDraggedEntered);
            dz.addEventListener(DRAGGED_LEFT_EVENT_NAME, handleDraggedLeft);
            dz.addEventListener(DRAGGED_OVER_INDEX_EVENT_NAME, handleDraggedIsOverIndex);
        }
  ....
```

The problem here is that I can't replicate this on the REPL, with a simpler setup. It's only happening in my app even though my really, really looks like the repl linked in this issue.

I'll try and look further but it seems for some reasons `typeToDropZones.get(draggedElType)` return undefined in that case.

If you can think of anything that could cause that, that'd be helpful.

In the mean time, I disabled entirely dnd when the list has one row but that causes issues as well as it's hard to re-activate it once a new row is added.

Cheers

**Comment by isaacHagoel** [comment]
i am moving house tomorrow so things are a bit chaotic here atm.
do u assign a type to the dropzone in your options?
could it be that the zone gets destroyed when there is on row left? search for "pointer dndzone will destroy" in the debug console.
otherwise, i will need to see some of your code in order to try to help

**Comment by weeblr** [comment]
Hi

Thanks for taking the time to reply. I'm not assigning a type to the (single) dropzone on that page. I'll look into this more today and let you know if I can find something.

**Comment by weeblr** [comment]
Adding a type does not change anything.

**Comment by weeblr** [comment]
> could it be that the zone gets destroyed when there is on row left? search for "pointer dndzone will destroy

Yes, I see that in the console:

```
pointer dndzone will destroy
admin-ac2dae6bfd.js:20389 keyboard dndzone will destroy
admin-ac2dae6bfd.js:20136 unregistering drop-zone
```

But I don't see why that would happen. The tbody (on which dndzone is attached) is not part of the #each loop:

```
<tbody class="wb-bg-white wb-overflow-y-scroll" use:reorderAction={{items:$store.rows,...dndConfig}}
           on:consider={onConsiderReOrder}
           on:finalize={onFinalizeReOrder}>
    {#each $store.rows as row, rowIndex (getRowId(row))}

        <tr data-id="{getRowId(row)}"
...
```
So I don't think Svelte would destroy it, even if it becomes empty. And when I do a simplified REPL, it does not happen.Don't really know ofc, will try to understand.

**Comment by weeblr** [comment]
OK, I've got a better understanding: the "real" pseudo code of what i'm doing is:

```
  {#if items.length}
    <tbody use:dndzone={{items,config}}>
      {#each items as item, index (getRowId(item))}
          <tr data-id="{getRowId(item)}" animate:flip="{{duration: flipDurationMs}}">
              <td>....</td>
          </tr>
      {/each}
    </tbody>
  {:else}
    <tbody>
      <tr>
        <tr colspan="3" in:fly="{{delay: 250, duration: 300, y: 50}}">No data available</td>
      </tr>
    </tbody>
  {/if}

```

With this, the tbody is indeed removed as soon as the items array is updated inside of on:consider.
So I switched to this:

```
<tbody use:dndzone={{items,config}}>
  {#if items.length}
    {#each items as item, index (getRowId(item))}
        <tr data-id="{getRowId(item)}" animate:flip="{{duration: flipDurationMs}}">
            <td>....</td>
        </tr>
    {/each}
  {:else}
    <tr>
      <tr colspan="3" in:fly="{{delay: 250, duration: 300, y: 50}}">No data available</td>
    </tr>
  {/if}
</tbody>
```

If you do that, then svelte-dnd-action still crashes but the error is not the same:

```
Uncaught (in promise) TypeError: Cannot read property 'isDndShadowItem' of undefined

for (let idx = 0; idx < node.children.length; idx++) {
                const draggableEl = node.children[idx];
                styleDraggable(draggableEl, dragDisabled);
                if (config.items[idx][SHADOW_ITEM_MARKER_PROPERTY_NAME]) {
                    morphDraggedElementToBeLike(draggedEl, draggableEl, currentMousePosition.x, currentMousePosition.y, () => config.transformDraggedElement(draggedEl, draggedElData, idx));
                    styleShadowEl(draggableEl);
                    continue;
                }
```

So right now I have removed the display of a separate "No data available" tr and there's no more crashing. Would love to have some way of still displaying a message though.

**Comment by weeblr** [comment]
Hi again

Another piece of information, this time directly related to the problem at hand, that is working with tables.

If you look[ at this REPL](https://svelte.dev/repl/33410a2062504f1badabf983cba5e7f3?version=3.29.4), you'll see that I tried to use the documented method to style **the shadow** element. I give it a red background in that case.

But as you can see, the red background is applied **to the dragged element**.

So there's something odd here which might be related the styling issue we've seen.

**Comment by isaacHagoel** [comment]
closing this for now. looks like there isn't much to do with table elements atm. feel free to reopen if needed
