### ISSUE TITLE
Element being rendered, even if dndzone is conditional

### ISSUE THREAD

**Issue by pReya** [isaacHagoel/svelte-dnd-action#176]
My parent element (div), that I apply `use:dndzone` to, is being rendered conditionally. However, no matter if the element is actually rendered or not, I always end up with a rendered element in the DOM.

```
{#if images}
  <div
    use:dndzone={{items: images, dragDisabled, flipDurationMs, dropTargetStyle}}
    on:consider={handleConsider}
    on:finalize={handleFinalize}
	...
  >
	  {#each images as image (image.name)}
	      <div animate:flip={{duration: flipDurationMs}}>...</div>
	  {/each}
  </div>
{/if}
```

In the browser I can always find this element (with a height of 0, so it's not visible), regardless of the state of my `images` variable:
![Screenshot 2020-10-28 at 11 35 58](https://user-images.githubusercontent.com/4677417/97425032-d8f4ea80-1911-11eb-8eca-8b15a8794882.png)

Is this a bug or somehow necessary for the action to work?

**Comment by weeblr** [comment]
Hi

Is it possible your `images` variable is defined, ie an array but an empty one? like you should test for 

```
{#if images && images.length}
```
?

**Comment by pReya** [comment]
@weeblr You're absolutely right. I'm sorry I missed this. Thanks for your help!
