### ISSUE TITLE
When using keyboard, on:finalize is triggered at each position change

### ISSUE THREAD

**Issue by weeblr** [isaacHagoel/svelte-dnd-action#177]
Hi

When using the keyboard to re-order rows within a table, one:

- focus a row
- press enter/space
- start moving up/down the row with arrow keys
- finalize (or so I thought) the re-ordering by pressing again the enter/space key?
- maybe cancel the re-ordering by pressing ESC key?

I'm seeing that the on:finalize event is triggered each time an arrow key is pressed instead of only when the final position is reached ([see REPL](https://svelte.dev/repl/2140934732a14219975549076f11a10c?version=3.29.4))

In my case, this results in a large number of API calls instead of just one at the end.

Is this by design?

**Comment by weeblr** [comment]
OK, after reading the doc again, this seems to be by design. 

> Press Space/Enter key while focused on an item, or the Escape key anywhere to exit dragging mode. The reader will tell the user that they are no longer dragging.

Can this be changed somehow so that finalize is fired only once: when user exits dragging mode with Enter/Space. ESC should indeed cancel dragging mode but return the item to its original location?

**Comment by isaacHagoel** [comment]
I think that for the purpose of updating the API, you could ignore all keyboard events (SOURCE would be SOURCES.KEYBOARD) except for TRIGGERS. DRAG_ENDED.

**Comment by weeblr** [comment]
Hi

I assume TRIGGERS. DRAG_ENDED is only triggered when the user presses Enter/Space or ESC the second time?

Don't think that can work though as I can certainly only make an API call to update the server when that happens, however the re-ordering has still taken place in the client. So if I don't make the API calls right away:

- there will be a discrepancy between client ordering and server ordering
- if user cancels the move - by pressing ESC - the items are not returned to the initial ordering, contrary to what happens with mouse-based operation.

So that means I will have to manage that myself? 

- on DRAG_STARTED, save the starting ordering
- On DRAG_ENDED, make API call
- on DRAG_STOPPED or DROPPED_OUTSIDE_OF_ANY restore the initial state?

**Comment by isaacHagoel** [comment]
There is no such thing as cancelling a move when using keyboard. Esc is
just another way to exit dragging mode. It was imlemented like this after
consulting with an accessibility expert. It requires the least amount of
work and memory to operate.

**Comment by weeblr** [comment]
Experts should all agree but they don't :) [W3-ARIA](https://www.w3.org/wiki/PF/ARIA/BestPractices/DragDrop) and [others ](https://dev.opera.com/articles/accessible-drag-and-drop/)think that Enter/Spacebar should validate the move and [ESC should cancel the move entirely](https://medium.com/salesforce-ux/4-major-patterns-for-accessible-drag-and-drop-1d43f64ebf09), as I described above.

I understand this is a big change, I'll leave those 2 pages for reference here and close the topic for now.

**Comment by isaacHagoel** [comment]
I am not concerned about making big changes if they are for the better. In
this case, I think it will worsen the UX. I am willing to be convinced
otherwise

**Comment by weeblr** [comment]
Happy to hear that! I cannot convince you myself, not knowing enough about the topic. I researched the matter and all articles I find, either in "official" sites, ie W3-ARIA wiki or independant entities (Opera browsers, indie devs) describe the same operation mode:

- focus an item
- press Space to enter drag mode
- use arrows to select target
- press Space again to validate operation
- press ESC to cancel operation

Please consult the 3 links in my previous post for reference. They also mention the aria attributes supposed to be used (aria-grabbed and aria-dropeffect) and several differences with current svelte-dnd-behavior, like tabbing into the drop zone should focus the 1st item in the list for instance

**Comment by isaacHagoel** [comment]
I read all of these resources and many more and the documentation on the
different aria attributes (dropeffect etc.). My impression (reenforced by
the expert) was that there is no standard and that reason is the best guide
:)
Try to convince me why behaviour x or attribute y are better than what the
library currently does

**Comment by weeblr** [comment]
>My impression (reenforced by
the expert) was that there is no standard and that reason is the best guide

There definitely IS a standard (I linked to it). That it's not applied by AT providers in a consistent manners seems to be a constant of accessibility. My reason tells me what I outlined below. Your reason may differ :)

>Try to convince me why behaviour x or attribute y are better than what the
library currently does

When doing a drag and drop with a keyboard, I want the same freedom as when using a mouse: only perform the operation when I validate it, not just when I initiate it. 

In our specific case, there's a major issue with the current behavior: 

If I hit the down arrow after pressing the Enter key to initiate a KB-drag, I validate the move operation without knowing **where** the dragged element will be dropped. It's only when the move is completed that I know where I actually dropped the item. And maybe that's not where I wanted the element to be dropped and I have to move it back or keep moving "at random" until I know where I should drop it.

This may have (bad) side-effects if I put an item in the wrong position, even if only for a short time.

I think the ability to know where the item will be dropped **before** dropping it is a major concern.

**Comment by isaacHagoel** [comment]
Hi,
If you read through that ARIA link you might notice that it is talking
about a dropdown menu for "copy", "move", "reference", the ability to
select multiple objects and other things that are not quite relevant.
Some of the properties mentioned at [marked as depracated](
https://www.digitala11y.com/aria-dropeffect-properties/) and so on.
I invite you to turn your screenreader on and try to actually use the
library with the keyboard and the reader (not in the REPL, some of the
announcements won't work there). notice how u can switch the item u r
dragging by clicking on it with the mouse and how u can drag and drop with
the mouse while in "dragging mode" in the keyboard.

It is possible to change the behaviour so that every move is a "consider"
until you exit dragging mode and have escape revert the whole thing without
adding an intermediary "select" phase.
Would that satisfy your usecase?

**Comment by weeblr** [comment]
Hi

Thanks for looking.

> it is talking about a dropdown menu for "copy", "move", "reference", the ability to select multiple objects and other things that are not quite relevant.

For our use case, we are not talking about selecting items here, not sure what you mean. Yes, the spec covers a wider scope but it also covers the basic use case we are facing: moving an item from one place to another.

> drop-effect deprecated

it's in [aria1.1](https://www.w3.org/TR/wai-aria-1.1/#attrs_dragdrop) and the spec says it will be replaced by something else. That does not affect our discussion about the **process** of drag and dropping, just the attributes. Currently, they are the specified ones but using newer ones when available will be fine as well.

>notice how u can switch the item u r dragging by clicking on it with the mouse and how u can drag and drop with the mouse while in "dragging mode" in the keyboard.

Not sure what you mean by that, we're talking about keyboard only usage here.

> It is possible to change the behaviour so that every move is a "consider" until you exit dragging mode and have escape revert the whole thing without adding an intermediary "select" phase.

Again there might be some confusion here. I never said anything about "selecting". What I think is the correct way to do this is for the drop to only happens when the user "validate" the drop. 

The drop (ie, actually moving the item to its new position) cannot happen just by moving the down arrow key - because when I press the down arrow key, I don't know what's the next item, so I don't know if I want to move the item in that position or 3 more lines down.

If I understand you correctly, then yes:

- every **keyboard** move is a "consider" (so that display can be updated)
- Press Enter/Space "validate" the drop (equivalent to releasing the mouse button if using a mouse)
- Press ESC "cancel" the drop and item returns to its initial position (equivalent to dropping "outside_of_any" with a mouse)

would be what I'm after.


Cheers

**Comment by isaacHagoel** [comment]
I think it is very doable and might be better than what we currently have. I guess I didn't explain the mixed mode (clicking and dragging stuff with the mouse while being in keyboard drag mode should still work in a way that is not broken).
I can give it a shot when i have some time or you are welcome to try if you'd like. I shouldn't be too complex and all of the changes should happen in a single file: keyboardAction.js (well, the README too but that doesn't count :))

**Comment by weeblr** [comment]
Made a PR, to get started...

**Comment by weeblr** [comment]
Please look at [this PR](https://github.com/isaacHagoel/svelte-dnd-action/pull/183).

**Comment by isaacHagoel** [comment]
@weeblr I am closing this for now since it has been a long time since we last discussed this. Feel free to reopen if/when u'd like to resume.
