### ISSUE TITLE
Conflict with focus-visible polyfill

### ISSUE THREAD

**Issue by weeblr** [isaacHagoel/svelte-dnd-action#178]
Hi

I have just noticed a conflict [with the focus-visible polyfill](https://github.com/WICG/focus-visible), used to show a focus ring when keyboard is used but avoid it when using mouse navigation.

What using the keyboard to re-order items in a list, svelte-dnd-action normally adds an outline to the item being moved to identify it.

However when focus-visible polyfill is enabled, that outline is sometimes displayed, sometimes not. I confirmed that this works fine when the polyfill is removed from the page.

As the polyfill is used on many applications, I think this needs fixing. One way to workaround may be to use a configuration option for outlining the dragged item?

Just like there is dropTargetStyle, you maybe could have draggedElementStyle to allow for customization of the way the dragged item is identified?

I just noticed actually that the transformDraggedElement option does not apply when using keyboard, or it may apply and then be reverted immediately as the item is dropped right away when using keyboard.

Let me know, I'll try to find a workaround myself for the time being.

**Comment by isaacHagoel** [comment]
The library does not draw the outline. It just calls .focus() on it. The
browser then does whatever it does with focused elements (i.e draws an
outline)

**Comment by weeblr** [comment]
OK. yet, I will review the CSS used with focus-visible and try find a workaround

**Comment by weeblr** [comment]
FYI, I workedaround this by maintaining a variable that holds the currently keyboard-dragged item id and adding the "focus-visible" class when refreshing the rows display.

The class was not restored after a KB-operation. I suspect because this class is added dynamically by the focus-visible polyfill, it was not added back after the svelte redraw.
