### ISSUE TITLE
Option to leave items in DOM (and position with CSS)

### ISSUE THREAD

**Issue by mosheduminer** [isaacHagoel/svelte-dnd-action#179]
Hi, it appears that svelte-dnd-action removes elements from the DOM after drag, and it is upon the caller to recreate the list using `event.detail.items`, which is then rerendered by an `#each` block.

I have a use case with dynamic components and DOM, where I would like to allow rearranging the components, but without altering the DOM or the svelte component tree. I can do this by upating CSS, see [this REPL](https://svelte.dev/repl/918a640c78734a35a1870bb868b082b5?version=3.29.4) for an example of how I do this with CSS grid.

I think this would work, but the dragged items seem to snap to particular positions (which seems to disappear if I comment out line 31), and on drop there is an error `Error: Cannot read property 'parentElement' of undefined`.

I know this is maybe not the usecase for your library, but I would greatly appreciate it if this could be worked out!

**Comment by isaacHagoel** [comment]
@mosheduminer sorry for the delay, you caught me in the midst of moving house. I might be able to help. 
Can you tell me more about your use-case?
What are you trying to achieve?
Would u like the items to always have the same positions (== their original positions) in the list as far as Svelte is concerned (so it doesn't re-render) but still make it look as if they changed position?
This sounds doable to me.

**Comment by mosheduminer** [comment]
> Would u like the items to always have the same positions (== their original positions) in the list as far as Svelte is concerned (so it doesn't re-render) but still make it look as if they changed position? 

Yes, exactly. In fact, I don't even really need to use an each block at all, since I'm not expecting re-renders.

I have mutable state in the various components/items, so I don't want to move them with re-renders, only with css. Unfortunately, it appears to break when I try (as in the REPL i linked above).

**Comment by isaacHagoel** [comment]
@mosheduminer i played with it a bit but yeah, looks like this idea breaks some of the library's core asumptions.
I'm still curious about this usecase. Why would you want to make the reordering of the list visual only? What breaks in your app logic when svelte re-renders the list?

**Comment by mosheduminer** [comment]
I am building a [GUI](https://github.com/sirixdb/sirix-svelte-frontend) for [SirixDB](https://github.com/sirixdb/sirix) (a temporal database) with various independent panes, which I would like to rearrange, and each pane has network and display logic, rerendering would cause a loss of that state, unless I moved the state higher up (something I should maybe do in the future, admittedly). An old screenshot:

![image](https://user-images.githubusercontent.com/47164590/97802401-15c22980-1c11-11eb-801e-073fbc3ee4f6.png)

A more recent one (showing a diff between to revisions in history):
![image](https://github.com/sirixdb/sirix/blob/master/Screenshot%20from%202020-09-28%2018-50-58.png?raw=true)

In addition, re-rendering would cause a flash, in particular because of the nature of the virtual list/tree I implemented for displaying data. At current, because the state of the virtual tree is handled within the pane, recreating the pane would result in the state of the tree (expanded nodes, scrolling) to be lost.

**Comment by isaacHagoel** [comment]
@mosheduminer 
I see. Thanks for the explanation.
Indeed, the way to achieve it is to pull all of the data that needs to be persisted (including scrollTop in your case) into the items array. See [this REPL](https://svelte.dev/repl/eb2f5988bd2f46488810606c1fb13392?version=3.29.4)

**Comment by mosheduminer** [comment]
Hmm, okay, thanks. I didn't want to pull the state up from the panes, but I guess there is no way around it if I want to use this library.

**Comment by isaacHagoel** [comment]
I thinks so. imo, you will be happy that you did long term (it is more idiomatic to how Svelte does things). I will let you know if some other solution pops in my mind.
