### ISSUE TITLE
TypeError: document.body is null

### ISSUE THREAD

**Issue by craigkai** [isaacHagoel/svelte-dnd-action#194]
Hello,

I am not sure this is a bug with svelte-dnd-action or me not doing things the 'svelte' way.

I have an existing application where I am looking to add svelte to part of the UI. I did this by importing the compiled JS from svelte and adding the following to `main.js`:

```javascript
import App from './App.svelte';

const app = new App({
  target: document.getElementById( 'svelte-boards' ),
  props: {
  }
});
export default app;
```

Where I am not grabbing `document.body` but instead a div by ID. When I add ` import {dndzone} from "svelte-dnd-action";` to my App.svelte I see the following error in my browser:

> Uncaught TypeError: document.body is null
>     initAria http://localhost/static/js/boards.js:1761
>     app http://localhost/static/js/boards.js:1814
>     <anonymous> http://localhost/static/js/boards.js:2537
> boards.js:1761:9
>     initAria http://localhost/static/js/boards.js:1761
>     app http://localhost/static/js/boards.js:1814
>     <anonymous> http://localhost/static/js/boards.js:2537

My thought is that the svelte-dnd-action library assumes you are using the typical `document.body` setup for the svelte instance.

Is it possible to have svelte-dnd-action check with the svelte instance to confirm what its "base" is?

Thanks, I apologize if this isn't the right place to ask this.

**Comment by isaacHagoel** [comment]
Hi @craigkai,
This sounds like a legit usecase to me.
I tried to reproduce it locally but couldn't.
How can document.body be null regardless of how u initialise the Svelte component?

**Comment by craigkai** [comment]
Ah that points me in the right direction, the actual code is the following:

```JavaScript
let app;
jQuery( document ).ready(function() {
  if ( document.getElementById( 'svelte-boards-rt' ) ) {
    app = new App({
      target: document.getElementById( 'svelte-boards-rt' ),
      props: {
      }
    });
  }
});
```

So the bug actually seems to be around how I am trying to load svelte after the rest of the page loads

**Comment by isaacHagoel** [comment]
@craigkai actually, seeing this made me realise the problem might be on my end.
i've created this branch: `194-init-aria-only-after-dom-content-loaded` with a fix.
can you try it out locally and let me know if it solves the issue for you?

**Comment by craigkai** [comment]
That branch fixed the issue that I was seeing, thanks!

**Comment by isaacHagoel** [comment]
Cool. I will release it later today.
