### ISSUE TITLE
Can the height of the layout container be the max height of the contents?

### ISSUE THREAD

**Issue by bostondevin** [isaacHagoel/svelte-dnd-action#205]
I'm using this in a drag/drop situation and the height of the layout container is always the default row height instead of the greatest height of the cumulative items in the matrix. Can this be adjusted to accommodate? That math makes my brain hurt to calculate it.

**Comment by isaacHagoel** [comment]
Hi @bostondevin,
not sure i follow, could you pls create a REPL to demo the issue?

**Comment by isaacHagoel** [comment]
@bostondevin any updates on this or should i close it?

**Comment by isaacHagoel** [comment]
closing this for now. feel free to re-open with extra details/ REPL. thx.
