### ISSUE TITLE
Consider marking your touch and wheel event listeners as `passive` to improve your page's scroll performance.

### ISSUE THREAD

**Issue by thousandsofraccoons** [isaacHagoel/svelte-dnd-action#207]
Consider marking your touch and wheel event listeners as `passive` to improve your page's scroll performance.
[https://web.dev/uses-passive-event-listeners/?utm_source=lighthouse&utm_medium=devtools](https://web.dev/uses-passive-event-listeners/?utm_source=lighthouse&utm_medium=devtools)

![image](https://user-images.githubusercontent.com/33694447/103400908-a32fd600-4afb-11eb-968f-bbaf25d975c7.png)

Google lighthouse complain about this lines.
```
    draggableEl.removeEventListener("mousedown", elToMouseDownListener.get(draggableEl));
            draggableEl.removeEventListener("touchstart", elToMouseDownListener.get(draggableEl));
            if (!dragDisabled) {
                draggableEl.addEventListener("mousedown", handleMouseDown);
                draggableEl.addEventListener("touchstart", handleMouseDown);
                elToMouseDownListener.set(draggableEl, handleMouseDown);
            }
            // updating the idx
            elToIdx.set(draggableEl, idx);
```

**Comment by isaacHagoel** [comment]
The reason they are not passive is to stop the page from scrolling when the user is just dragging the item around. You can try it out without (on a local copy). It's very awkward.

**Comment by isaacHagoel** [comment]
closing for now. feel free to re-open/ engage in conversation. thx
