### ISSUE TITLE
Placing before end of flip animation results in unnatural transition

### ISSUE THREAD

**Issue by yjp20** [isaacHagoel/svelte-dnd-action#208]
When you place a drag and drop element before the flip animation is finished, then the transition looks rather unnatural. Do you have a work around for this problem?

I think maybe disabling flip animation for the shadow element might work, but I'm not sure if this is true and possible to apply via the library or if it's something that's better left in the hands of the user.

I'll borrow this example as a demo:

**Demo:**
https://svelte.dev/repl/028674733f67409c94bd52995d5906f1?version=3.31.0

**Comment by isaacHagoel** [comment]
not sure i 100% understand the issue. what do you mean by "unnatural"?

**Comment by yjp20** [comment]
![issue](https://user-images.githubusercontent.com/44457064/103864747-759fe980-5106-11eb-9f31-210b71dd6c79.gif)

The first time through I couldn't get it to work but it seems like there's an error the second time.

**Comment by isaacHagoel** [comment]
Which error? When it snaps to place at the end?

**Comment by yjp20** [comment]
Right

**Comment by isaacHagoel** [comment]
This is not the flip animation. It is about how the dropped item calculates
the index it needs to animate to. I will have a look when i have some time.

**Comment by isaacHagoel** [comment]
okay, found and fixed the issue. it had to do with the flip animation (indirectly). merging the fix soon

**Comment by isaacHagoel** [comment]
@yjp20 this should be fixed in version 0.7.2. give it a shot
