### ISSUE TITLE
Crazy nesting example is broken

### ISSUE THREAD

**Issue by isaacHagoel** [isaacHagoel/svelte-dnd-action#215]
https://svelte.dev/repl/fe8c9eca04f9417a94a8b6041df77139?version=3.31.2

**Comment by Florian-Schoenherr** [comment]
Only really recently, I looked at it last week.

**Comment by isaacHagoel** [comment]
it broke in 0.7.4. investigating

**Comment by isaacHagoel** [comment]
I fixed the REPL. it broke because it was making an assumption that all of the ids in the list exist in the nodes data structure. 0.7.4 broke this assumption.
