### ISSUE TITLE
Cannot read property 'getBoundingClientRect' of undefined

### ISSUE THREAD

**Issue by MTyson** [isaacHagoel/svelte-dnd-action#235]
I'm getting this error when dropping inside the target zone.  It has something to do with me (server-side) loaded data (I'm inside of an await block).

Can you give me an idea where to look?

GREAT library. Thank you.

Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined
    at getBoundingRectNoTransforms (intersection.js:10)
    at animateDraggedToFinalPosition (pointerAction.js:269)
    at handleDrop (pointerAction.js:264)
getBoundingRectNoTransforms @ intersection.js:10
animateDraggedToFinalPosition @ pointerAction.js:269
handleDrop @ pointerAction.js:264

**Comment by MTyson** [comment]
More detail:

```
{#await showMinePromise}
            <p>...Loading</p>
          {:then entries}
            {items = entries}
            <ol>
              {#each entries as entry, i}
            <li>{entry.entryanswer} - {entry._id}</li>
              {/each}
            </ol>
            <section use:dndzone="{{items, flipDurationMs}}" on:consider="{handleDndConsider}" on:finalize="{handleDndFinalize}">
              {#each items as item(item._id)}
                <div animate:flip="{{duration: flipDurationMs}}">{item.entryanswer}</div>
              {/each}
            </section>
          {:catch error}
```

...

  ```
  let items = [
        {_id: 1, name: "item1"},
        {_id: 2, name: "item2"},
        {_id: 3, name: "item3"},
        {_id: 4, name: "item4"}
    ];
    const flipDurationMs = 300;
    function handleDndConsider(e) {
        items = e.detail.items;
    }
    function handleDndFinalize(e) {
        items = e.detail.items;
    }
```

(I assign entries to items as a troubleshooting attempt)

**Comment by isaacHagoel** [comment]
what updates `showMinePromise`?
is the dndzone removed from the dom on drop somehow?

**Comment by isaacHagoel** [comment]
and also Hi and thanks for reporting the issue 😄

**Comment by MTyson** [comment]
If I do this (use entries directly):

```
<section use:dndzone="{{entries, flipDurationMs}}" on:consider="{(e) => entries = e.detail.items}" on:finalize="{(e) => entries = e.detail.items}">
              {#each entries as item(item._id)}
                <div animate:flip="{{duration: flipDurationMs}}">{item.entryanswer}</div>
              {/each}
            </section>
```

I get:

action.js:58 dndzone will ignore unknown options
Uncaught (in promise) Error: no 'items' key provided to dndzone
    at validateOptions (action.js:61)
    at dndzone$2 (action.js:26)
    at Object.mount [as m] (TopicDetail.svelte:130)
    at update (index.mjs:1076)
    at index.mjs:1090


ShowMinePromise:
```
  let showMinePromise = Promise.resolve([]);
  showMinePromise = fetchMineAnswers();
//...
  async function fetchMineAnswers() {
		console.log("ID: " + JSON.stringify(id));
    //const response = await self.fetch("entry/"+id+".json?type=");
    const response = await self.fetch(`entry/associate?userid=${$session.token._id}`);
		
		if (response.ok) {
      let parsed = await response.json();
      console.log("Parsed: " + JSON.stringify(parsed));
      return parsed;
		} else {
			throw new Error(response.json());
		}
  }
```

**Comment by isaacHagoel** [comment]
about the first error. it should probably be:
```
use:dndzone="{{items: entries, flipDurationMs}}"
```

what triggers `fetchAnswers` besides the initial load?

**Comment by MTyson** [comment]
Only the initial load right now!

**Comment by MTyson** [comment]
Only the initial load right now!

**Comment by MTyson** [comment]
When I use:

{{items: entries, flipDurationMs}}

I get no error, but the dropped item vanishes from the dom.  (If I dnd that last item, I then get the undefined error)

**Comment by isaacHagoel** [comment]
will u be able to create a REPL that reproduces the issue so I can debug hands on?

**Comment by MTyson** [comment]
When I use:

{{items: entries, flipDurationMs}}

I get no error, but the dropped item vanishes from the dom.  (If I dnd that last item, I then get the undefined error)

**Comment by MTyson** [comment]
hm, I'm building in sapper locally so my api is local.

**Comment by MTyson** [comment]
OK, got it working with your suggestion:

```
<section use:dndzone="{{items: entries, flipDurationMs}}" on:consider="{(e) => entries = e.detail.items}" on:finalize="{(e) => entries = e.detail.items}">
              {#each entries as item(item._id)}
                <div animate:flip="{{duration: flipDurationMs}}">{item.entryanswer}</div>
              {/each}
            </section>
```

Thanks again, really looking forward to using this project.

**Comment by isaacHagoel** [comment]
hi,
what was the issue though? how did you fix it?

**Comment by MTyson** [comment]
I think I was mixing up the items and entries variable... I need to understand it better.

**Comment by isaacHagoel** [comment]
cool. pls let me know if it is something that requires my attention.

**Comment by MTyson** [comment]
Working like a charm now, thank you!

It would be cool to have an example of using the list with a backend fetch/{#await} block usage. Possibly including updating the backend based on dnd.

I'll try to get to do that.

Rock on.

**Comment by beebase** [comment]
An async example is exactly what I am for . (TIA)  👍

**Comment by isaacHagoel** [comment]
Happy to make one (can get to it today or tomorrow i think). Do you mind creating a new issue for it so i don't forget?

**Comment by beebase** [comment]
Thank you. Very kind of you. 
Meanwhile I figured it out, going through the code snippets in this thread.
I will post a working async snippet here for others.

**Comment by isaacHagoel** [comment]
cool! ideally please make a REPL with a simple JS file that mocks the
server (returns promises that resolve after a timeout from its get and set
methods) so I can add it to the official examples.
if, i am happy to do it as i said above.

**Comment by beebase** [comment]
Here's an example with a simulated server call in one file (I'm new to repl, couldn't figure out export/import)
I've also added a "sort" field that updates all records after a drag/drop.

Anyway here's the link. Feel free to edit/add to the examples.
https://svelte.dev/repl/0ce664fdfb0943d8b6e80b041fafbdc0?version=3.32.0

BTW: thanks for sharing this great package

**Comment by isaacHagoel** [comment]
Hi @beebase 
Thanks for the example. 
I've also made one. Please see [this REPL](https://svelte.dev/repl/964fdac31cb9496da9ded35002300abb?version=3.32.0).
I made it a bit more sophisticated, with optimistic updates and rollback.
Please let me know if it meets the usecase or falls short.
If all good, I will add the link to the README
cc @MTyson

**Comment by beebase** [comment]
That is a very clear and useful example. Thanks!  :-)

**Comment by isaacHagoel** [comment]
cool. added it to the README (with tiny tweaks)

**Comment by MTyson** [comment]
Just seeing this thread... awesome work guys, thank you!! 
The dnd is very stable in our app. Awesome.
