### ISSUE TITLE
Keyboard behavior should mimic pointer behavior

### ISSUE THREAD

**Issue by rmcew** [isaacHagoel/svelte-dnd-action#239]
The finalize event is dispatched when dragging by tabbing / arrowing through dnd zones; the consider event is never used. In order to mimic pointer behavior, the consider event should be dispatched until an item is placed.

**Comment by isaacHagoel** [comment]
Currently the item is placed after every keyboard action. it is intentional.
It means that keyboard draggin always leaves the system in a "stable"
state. From the user perspective it is the same number of operations.
Making trigger consider events requires a more complicated implementation
and pointer/keyboard action to actively work to prevent conflicts (ex: use
drags with the mouse while in "keyboard dragging" mode and then hitting
"escape" to cancel the operation.

With that said, you can, in your code, treat any `finalize` event that
comes from the source "keyboard" as a `consider` until a drop takes place
if you'd like.

**Comment by rmcew** [comment]
Could we not just check if the user is in "keyboard dragging" mode each time a user starts a mouse drag? And if so, cancel keyboard dragging mode? That way the consider and finalize events are a bit less dependent on what type of drag event it is? 

I could try to work up a PR for you to look at if that would help. Let me know! I really like the library

**Comment by isaacHagoel** [comment]
There are definitely things that can be done (i think it will be more than
that). The question is what is the benefit of doing that. What are you
trying to achieve?
I appreciate your willingness to help.

**Comment by rmcew** [comment]
The workaround you mentioned would work, but it feels awkward to me. I, as the user of the library, have to know that keyboard drags are innately treated differently than mouse drags, and it makes my Consider and Finalize functions much more complicated than they need to be. I have to watch for keyboard events in my Finalize function, then run them through my consider logic. Then I have to watch for DRAG_STOPPED in my consider function in order to know when to run my finalize logic. Seems backwards to me

**Comment by isaacHagoel** [comment]
Again, the question is why do you have to do any of that in your code? What
kind of feature are you trying to provide to your users?

**Comment by rmcew** [comment]
If I have any piece of code that is specific to a finalize event, for instance a CRUD, then I need to be able to know with certainty when a user is finished placing an item.

**Comment by isaacHagoel** [comment]
Would you also
 like the user to be able to cancel the keyboard drag and move the item to
its original location?
We can try to create an example for such handlers in the REPL to see how
bad it is...

**Comment by rmcew** [comment]
That's a separate and possibly more challenging issue, but yeah on first thought I think it would probably make sense to be able to cancel / revert the keyboard drag.

**Comment by isaacHagoel** [comment]
It would also require modifying the messeges to the screen reader
(supported)
If you don't support cancel you should persist every keyboard move i think.
Anyhow, let's try it out in the REPL and see what we end up with before
considering a big breaking change to the library.

**Comment by rmcew** [comment]
https://svelte.dev/repl/76b3d2249a2440819de7c0b0828ed734?version=3.32.1

Here's a basic example, modified from one of the main examples in the repo. Lines 11 and 17 in Board.svelte are handling the same use case. They're both saying "ok the user is done with the drag, lets save it off", but one has to happen in the consider and the other in the finalize. Seems to me the whole purpose of the finalize function is to handle these sorts of scenarios, it's confusing to have it bleed over into the consisder

**Comment by isaacHagoel** [comment]
refactored it to remove duplicated code and encapsulate the "save" decision.
https://svelte.dev/repl/e78ca112f2c04a5b943a1a6161617da0?version=3.32.1

i think it looks okay.  this example is not complete though. what should
happen when the user tabs out of the list after moving an item with the
keyboard but without ever exiting dragging-mode?

**Comment by isaacHagoel** [comment]
@rmcew closing for now. feel free to reopen if u have further thoughts on this.
