### ISSUE TITLE
Custom elements with disconnectedCallback error

### ISSUE THREAD

**Issue by danny-andrews** [isaacHagoel/svelte-dnd-action#240]
I have a drag item which contains a custom element ([sl-button-group](https://shoelace.style/components/button-group) to be specific) and when I start dragging, it emits an error when running its disconnect logic.

**Error**
```
Uncaught TypeError: Cannot read property 'removeEventListener' of undefined at HTMLElement.disconnectedCallback
```

**Code**
```
disconnectedCallback() {
  this.buttonGroup.removeEventListener('sl-focus', this.handleFocus);
  this.buttonGroup.removeEventListener('sl-blur', this.handleBlur);
}
```

It seems that by the time this callback is fired, svelte-dnd-action has already removed its corresponding node from the DOM, causing the reference error. Is there a known workaround for this sort of thing?

Thanks!

**Comment by isaacHagoel** [comment]
Interesting. I'm happy to take a look.
Do you mind creating a small example that reproduces it in the REPL ?

**Comment by danny-andrews** [comment]
Looking into this further, I think it may be a limitation with svelte actions itself. I'm investigating further. 🧐

**Comment by isaacHagoel** [comment]
Cool. Let me know. Even if it is, there might be a workaround

**Comment by danny-andrews** [comment]
Here's a reproduction URL: https://svelte.dev/repl/8435ccce66394a60b228fa49dcbbca57?version=3.32.1.

**Comment by danny-andrews** [comment]
It should be noted that if you use keyboard shortcuts to move stuff around, this error does not occur. It only happens when initiating a drag with the mouse.

**Comment by isaacHagoel** [comment]
it doesn't reproduce with a simple custom element. 
https://svelte.dev/repl/09ffc22f972f46dca55add714d929401?version=3.32.1

I haven't looked at the source code of the library yet to see what it's doing different than my example.

**Comment by danny-andrews** [comment]
I think it's something to do with this library in particular. It uses stencil which does some wonky async stuff. I've had a few issues with it already. I'm digging into it with that library's author. I doubt there's anything that needs changed on your end. Closing for now.

**Comment by isaacHagoel** [comment]
You closed it as I was writing a similar comment 😄 
the original comment below. pls let me know if I can help further.

looks like they use stencil. I think the ref on the child div in [this line](https://github.com/shoelace-style/shoelace/blob/5283b5a8086f71212743a87f5f032f9673d34e85/src/components/button-group/button-group.tsx#L50) gets confused.
```html
      <div ref={el => (this.buttonGroup = el)} part="base" class="button-group" aria-label={this.label}>
```

**Comment by danny-andrews** [comment]
I think you're exactly right. I'm running into a similar issue when trying to call a method on one of the shoelace components in `onMount` but it's throwing an error because a ref is undefined. Hopefully I'll get to the bottom of it. Thanks anyway for the help.
