### ISSUE TITLE
Reload items within 'use:dndzone' when changing items listed below

### ISSUE THREAD

**Issue by MaxJW** [isaacHagoel/svelte-dnd-action#246]
This is possibly already a feature but I'm not sure how to implement it! I have a list of todos that are filtered when a user selects a different project (causing a different set of items to appear).

Is there a way to "reload" the dndzone with the new items listed in the div?

**Comment by isaacHagoel** [comment]
Hi,
Not sure i'm following. Can u pls create a REPL to illustrate?

**Comment by MaxJW** [comment]
Hi,
Sorry, wasn't too sure how to explain it! I have the project on my website here if this helps: https://maxwilson.co.uk/Carrotodo/
You'll see if you create a new project (side panel on the right), create some ToDos (the list in the center) and try to move them around, it won't play nice. If you refresh though it will work fine. Hopefully that makes sense 😅

Appreciate the fast response!
Thanks,
Max

**Comment by MaxJW** [comment]
Actually this might be a problem on my end honestly, when not in the first project, moving any ToDo causes it to become blank, not sure what the issue might be. Code is also available here if necessary! https://github.com/MaxJW/Carrotodo

**Comment by isaacHagoel** [comment]
mmm... it seems okay to me. i create a project. clicked on it. created tasks. dragged them around to resort them within the list. marked as done. dragged again to resort. all worked with no refresh. what am i doing wrong?
would u like to add a screen capture (pls include the console as well)?

**Comment by MaxJW** [comment]
Sorry I did a bit of tweaking, the reason it wasn't working was I had an if statement with my {#each} to hide items from the array, but in my handler I was simply doing "array = e.detail.items", which obviously removed all of the other items in the array. My bad, sorry!

**Comment by isaacHagoel** [comment]
oh, cool. so all good?

**Comment by MaxJW** [comment]
All good, thank you so much for the quick responses and help though, really great library you have here 😁
