### ISSUE TITLE
Pointer drag and drop issue with expanded item

### ISSUE THREAD

**Issue by techniq** [isaacHagoel/svelte-dnd-action#247]
In my interface, I have an expansion panel component that can be expanded/collapsed that I am now using `svelte-dnd-action` to reorder.

If the panel not expanded, dnd works great, but as soon as I try to drag a panel that is open, it disappears (either immediate when dragging, or after being dropped):

https://user-images.githubusercontent.com/177476/107232425-62c35200-69ef-11eb-9719-b93c4c5e7056.mp4

If I keep trying to drag a few, at some point this error shows up in the console as well:

![image](https://user-images.githubusercontent.com/177476/107237175-73c29200-69f4-11eb-8ac5-bcaec915f997.png)

What's surprising is keyboard interaction works as expected with an expanded item:

https://user-images.githubusercontent.com/177476/107232701-b635a000-69ef-11eb-8d21-cf504adeb172.mp4

I tried to create minimal reproduction of the issue but I haven't been able to just yet (I'll keep trying), although there is one oddity in the current example: If the item is "expanded" and you drag it, it resizes back to "collapsed", although it doesn't disappear like in my case.  It appears the internal state of the component is lost/reset when it is dnd but not with keyboard interactions.

- https://svelte.dev/repl/70509df52058467f8a2cdd49810cd487?version=3.32.1

**Comment by isaacHagoel** [comment]
Hi,
Regarding losing internal state, there is an example with maintaining internal scroll position in an item. The gist is that the library and svelte (when rerendering) treat the item data as the element in the items list you pass in. Any data that needs to be passed around needs to be there. In other words, move isExpanded into the items array.

About the actual issue. I will need to see your code or a repl that reproduces it. 
If you don't get any errors in the console before or when the item disappears for the first time, i would take a close look at the way the consider/finalize handlers update the list. Could one of them be removing the item?

**Comment by techniq** [comment]
@isaacHagoel Thanks for the info.  Let me dig in a little more tonight and see if I can reproduce it in the REPL.

One curiosity, the issue is not present (and state maintained) when using the keyboard to move items.  I assume this is handled differently intentionally?

**Comment by techniq** [comment]
@isaacHagoel Here is a [REPL](https://svelte.dev/repl/f98f4b3712f2429881f51ec7fdeb7ef4?version=3.32.2) reproducing the issue.  Click on a panel to open it and attempt to drag it.

**Comment by isaacHagoel** [comment]
i took a quick look. looks like the consider events keep firing for a bit and have the correct list of items until they don't.  i eliminated the option that it has to do with the expanding feature because locking the items to their extended mode doesn't solve it.
It most likely has to do with the use of slots and slot props.
can you please make a version of this that inlines the extensible part without using a slot for it and let me know if the problem persists?
if not, i can try it when i have some time.
we need to narrow it down to its root cause.

**Comment by isaacHagoel** [comment]
(cont.)
actually, now that i recall there were issues in the past when using slots. that was because Svelte assume it has full control and authority over the slotted content and removes or adds dom elements to it as it pleases.
the solution is to build the higher order component in a different way that avoids slots and slot props.
see https://svelte.dev/repl/028674733f67409c94bd52995d5906f1?version=3.31.0
will that work for you?

**Comment by techniq** [comment]
@isaacHagoel Thanks for investigating.  If slots can not be supported, I do not believe I can use a  higher order component in this situation as I need full DOM flexibility.  WIth that said, I did remove all the slots and reactive properties and believe I have found the root issue... if I remove `transition:slide` from the panel's content the main issue goes away:

![image](https://user-images.githubusercontent.com/177476/107362852-4f73bd80-6aa7-11eb-9f8d-639adee6a58e.png)

I saw this [issue](https://github.com/isaacHagoel/svelte-dnd-action/issues/96) but at the time did not think it was related.

Good news is there doesn't appear to be an issue with using slots (at least not that I've uncovered thus far).  There is still the oddity with the lost internal state so the dragged item is not longer expanded after being dropped, but at least it drops now :).

https://user-images.githubusercontent.com/177476/107364453-73d09980-6aa9-11eb-804e-41b27a3023f8.mp4

I'm migrating from a react / react-beatuful-dnd solution and trying to have as few regressions as possible, but I can probably work around this.

Thanks for all your help.

**Comment by techniq** [comment]
A few additional thoughts:
I don't assume it would be possible to use `display:none` or similar for the dragged item's original node while it's clone is being dragging and then reposition it after the drop (so the node isn't truly destroyed).  I know this isn't possible when dragging/dropping between lists, but it would be nice to maintain the state.

Another thought is if there is anyway to access the internal state of the component and reconstitute it.  It seems potentially possible knowing Svelte devtools can read and write state, but I'm not sure if it's instrumenting this with some code manipulation.

![image](https://user-images.githubusercontent.com/177476/107365815-51d81680-6aab-11eb-9e55-e733521cb417.png)

I believe this is how SSR rehydration and possible HMR works.  Anyways, just some thoughts, and thanks again.

**Comment by isaacHagoel** [comment]
I am glad it is not the slots. Sorry for sending you in the wrong direction
and for jumping into conclusions.
Svelte transitions (specifically "out") are a known incompatibility. I
somehow missed that it was being used.

About internal state, why can't you add `isExpanded` to the `items` array
instead of having it as internal state in this case?

svelte-dnd-action currently only deals with data and dom elelemnts. It has
no knowledge of svelte components.

**Comment by techniq** [comment]
You can control the `isExpanded` state externally (utilzing `bind:open{...}`, but it's not required so there is no guarantee it is, but I can look into doing that and see how it works out.

Any thoughts of not destroying the element (and just doing `display: none` or similar) when moving within the same list (similar to keyboard)?

**Comment by techniq** [comment]
Looks like [SortableJS](https://sortablejs.github.io/Sortable/) works this way, and I was able to setup a quick [REPL](https://svelte.dev/repl/bb527bb8a2f849e19cd5956fc76bb668?version=3.32.2) that leverages slots and transitions and doesn't loose the internal state.  I need to kick it around a little more but appears to handle all my needs thus far.

Thanks again for your time investigating this.  I think I'm going to investigate using SortableJS in an action / component.

**Comment by isaacHagoel** [comment]
Good luck!
This library seems to use the native drag and drop api which i was actively
trying to avoid :)
I think your internal state will still not persist if svelte re renders the
component for any reason.
Let me know if i can be of further assistance.
