### ISSUE TITLE
Re-usable drag handle example

### ISSUE THREAD

**Issue by geovie** [isaacHagoel/svelte-dnd-action#251]
Hey,
I've created a somewhat more re-usable drag handle example based on the example from the readme:
[REPL](https://svelte.dev/repl/397a96b791af41d7978331ad63254bc0?version=3.24.1)

The usage is simple:
```typescript
const { dragHandleZone, dragHandle } = createDragHandle();
// on drag zone
use:dragHandleZone={{ /** dndzone options **/ }}
  
// on drag handle
use:dragHandle
```

**Comment by isaacHagoel** [comment]
@geovie thanks for this and sorry for the huge delay. I wanted to write back for a while. in the meanwhile i left it in issues so that other can find it.
this is super interesting to me because this pattern can be used in order to wrap all sort of sophisticated use cases without requiring changes to the core library. 
I am planning to investigate this direction further.

**Comment by zahachtah** [comment]
I found this super useful and have copied this for my app. I found one issue that might seem minor, but that can potentially have unintended effects: 

if you click on a specific handle you can then move any item even without being over the handle div. 

It's probably something relatively simple, but any idea how to prevent that would be greatly appreciated!

also, @isaacHagoel, have you thought more about making this a part of the library?

**Comment by isaacHagoel** [comment]
@zahachtah good catch. the official example (no action) had the same issue. 
the fix is to add mouseup and touchend listeners to the handle and have them disable drag.
the same solution should work for the action. i will fix when i have a chance

**Comment by benbro** [comment]
Is there an updated version of the drag handle action with a fix for the being able to drag any item after clicking on a handle?
It will be useful to add this action as an official example to the readme.

**Comment by benbro** [comment]
I've add mouseup and touchend as suggested. The official Drag handles example is still missing this fix.
```javascript
function dragHandle(node) {
  function startDrag(e) {
    // preventing default to prevent lag on touch devices (because of the browser checking for screen scrolling)
    e.preventDefault();
    drag.set(false);
  }
  function stopDrag(e) {
    drag.set(true);
  }
  function handleKeyDown(e) {
    if (e.key === "Enter" || e.key === " ") drag.set(false);
  }

  drag.subscribe((disabled) => {
    node.tabIndex = disabled ? 0 : -1;
    node.style.cursor = disabled ? "grab" : "grabbing";
  });

  node.addEventListener("mousedown", startDrag);
  node.addEventListener("touchstart", startDrag);
  node.addEventListener("keydown", handleKeyDown);
  node.addEventListener("mouseup", stopDrag);
  node.addEventListener("touchend", stopDrag);
  return {
    update: () => {},
    destroy: () => {
      node.removeEventListener("mousedown", startDrag);
      node.removeEventListener("touchstart", startDrag);
      node.removeEventListener("keydown", handleKeyDown);
      node.removeEventListener("mouseup", stopDrag);
      node.removeEventListener("touchend", stopDrag);
    },
};
```

**Comment by benbro** [comment]
I'm trying to use this action with nested zones. There is a parent list of items - zone-0. Each item has a list of sub-items - separate zone-n for each sub-items list.
I thought of adding a type parameter to the dragHandle action and make the drag store a Set of drag-able types.
Did anyone extend this action to support multiple zones and nested zones?
```javascript
const drag = writable(new Set());

function dragHandle(node, type) {
    function startDrag(e) {
        // preventing default to prevent lag on touch devices (because of the browser checking for screen scrolling)
        e.preventDefault();
        $drag = $drag.add(type);
    }
}
```
```html
<button use:dragHandle={{type: 'zone1'}}>
<button use:dragHandle={{type: 'zone2'}}>
```
