### ISSUE TITLE
Inherited CSS variable lost on dragging

### ISSUE THREAD

**Issue by atava** [isaacHagoel/svelte-dnd-action#255]
Hi all.
First off, thank you for this library and the commitment and mindful attitude with which you are developing it.

That said, here is my current issue.
An element I'm dragging uses a CSS variable which is inherited from some of its ancestors in the DOM.
While dragging it, I saw inspecting the DOM that the element is removed from its original location and put inside the body, so it is losing that CSS variable (since it's not inherited anymore).

My question is: since the variable I'm talking about is defined in an area-like div which stands between the body and the element (it acts sort of like a canvas), is there a way to specify that the drag-and-drop action move the element to that ancestor div instead of way up to the body?

Sorry if the question feels like a noobish one (maybe placing a dragged element in the body is standard behavior).
Thanks.

**Comment by isaacHagoel** [comment]
In theory it is possible.
The main consideration is to move it to a place in which svelte won't try
to remove it as part of it re-rendering stuff and won't be confused by it's
presence.
We can try to play around with it and see what happens.
With that said, if you define the style that uses the css variable on the
direct children of the dndzone (ex: `div {color: var(--my-var);}` where the
list items are divs) those styles will  get copied to the dragged element
(vs what happens if u do it on elements that are children of the list
items).
Not sure if ny explanation is clear. If u create a REPL illustrating your
scenario I should be able to demonstrate what I mean.

**Comment by atava** [comment]
Yes, that would work because the variable would be with the element. But it doesn't fit with my particular use case, as the variable that these "areas" (the containing divs) are setting is the size of the draggable elements themselves, and I want the elements to be completely agnostic about it. Their size is something that the upper divs specify and they inherit/find it in their style definitions.

I resorted for now to just have a fallback value in body.
Thanks for your reply and idea, though, it might help in many such cases.

**Comment by isaacHagoel** [comment]
I wasn't talking about where you define the variable but on where you use
it.
I am not sure i fully understand what you mean, a repl would be nice if you
are not fully happy with the workaround you are using.

**Comment by atava** [comment]
Hi again, and sorry for the late reply.

I tried to reproduce the issue, but I couldn't. In the REPL dragging and resizing works as intended:
[dnd-with-css-variables](https://svelte.dev/repl/98d36ce63652482faa4a638ad2e3a8ed?version=3)

The issue in my project probably stems from the dragged elements containing an img tag. I thought that the width CSS variable was being lost on dragging, but maybe it is only the image that's getting to its full size again (not being constrained anymore while in the body).
If you agree on keeping the issue open just a couple days more, I may be posting here a confirmation of this (just in case). Else feel free to close it now. It's okay for me anyways. :-)

Thank you again for the support and the library.

**Comment by isaacHagoel** [comment]
I've been using items with images inside without trouble at work. Let me
know what you've found

**Comment by atava** [comment]
I'd say ultimately the problem is unrelated to the library, so I'll close this issue.
Thanks.
