### ISSUE TITLE
Overriding id per zone

### ISSUE THREAD

**Issue by antony** [isaacHagoel/svelte-dnd-action#260]
So this library does 99% of what I need it for, which is great - time to get rid of Dragula!

However, the id override is problematic. What work needs to happen to make it per-dropzone? The reason being that I would use this to sort many different types of thing, and not all of those things have a unique field called id.

It would be great if there was a way to define a key and pass it into the dropzone within the options.

**Comment by isaacHagoel** [comment]
the reason the id property name has to be the same is that items can be
dragged from one zone to another and it needs to stay recognizable as it
moves around.

**Comment by isaacHagoel** [comment]
closing for now. I'm open for further discussion. Please re-open if needed.
