### ISSUE TITLE
Possible to work with a dynamically added ID?

### ISSUE THREAD

**Issue by mitchray** [isaacHagoel/svelte-dnd-action#261]
My data source is a store with existing ```id``` which also aren't unique, so I figured I could add a new unique field ```_id``` via reactive declarations but it doesn't appear to be working right... you'll see what I mean.

Have I just created a race condition? Appreciate any guidance, I'm fairly new to Svelte

[REPL](https://svelte.dev/repl/90fae91f2738485eb727b068bb2a9d47?version=3.24.1)

**Comment by isaacHagoel** [comment]
by a brief look: the index isn't consistent as the items move around, right?
the point of the id is to stick around as the item changes positions and
lists.
can u allocate ids on initialisation and stick to them?

**Comment by mitchray** [comment]
That makes sense, its working now by adding the new IDs earlier in the pipeline

Thanks Isaac
