### ISSUE TITLE
How to change dragging style?

### ISSUE THREAD

**Issue by MTyson** [isaacHagoel/svelte-dnd-action#266]
Probably obvious... I just want to add a drop shadow to the item while its moving.

**Comment by isaacHagoel** [comment]
option 1: use the `transformDraggedElement` option.
option 2: if all you need is static styling you can target the id of the dragged element: `dnd-action-dragged-el` with (global) css.  This id is not officially part of the public API but I don't mind exposing it as a constant.

**Comment by MTyson** [comment]
Thanks!

**Comment by isaacHagoel** [comment]
@MTyson I ended up exposing the id (you can import `DRAGGED_ELEMENT_ID`). Can i close this issue? did it work for you?
