### ISSUE TITLE
Hi, is there typescript defintions ?

### ISSUE THREAD

**Issue by joseDaKing** [isaacHagoel/svelte-dnd-action#268]
Hi, is there typescript defintions ?

**Comment by joseDaKing** [comment]
Sorry there are typescript definitions but you cannot see them here but on npm, you can see them.

**Comment by isaacHagoel** [comment]
if you look at package.json u will see `"types": "dist/index.d.ts",`.
They are coming from this [file](https://github.com/isaacHagoel/svelte-dnd-action/blob/master/typings/index.d.ts) and the README includes an example in Typescript.

**Comment by joseDaKing** [comment]
Thanks for the help
