### ISSUE TITLE
[Bug] When zone created durring drag

### ISSUE THREAD

**Issue by mataslib** [isaacHagoel/svelte-dnd-action#272]
In App, I have two halves. Left static, right may change views, like so:

![image](https://user-images.githubusercontent.com/5154014/113489387-3e05cb00-94c4-11eb-9f97-0604429e0b76.png)

This error is throwed:

![image](https://user-images.githubusercontent.com/5154014/113489949-735fe800-94c7-11eb-9dee-58e9769f5403.png)

When:

1. Click item to edit it (green view is showed)
2. Start dragging that item. Green view is changed for blue one. Blue view contains another dndzone with `dropFromOthersDisabled={true}` (error throwed only when present). Zone is created - Error throwed.

Cause:

[`pointerAction.js`]
Seems to me like `dz`/`node` varriable is accessed (line 474) before it is set to map varriable `dzToConfig` (line 487).

![image](https://user-images.githubusercontent.com/5154014/113490061-2892a000-94c8-11eb-83cd-6c098908e611.png)

Propossed solutions:

1. Move lines 485 and 487 before 470. No error throwed. Not sure if this does not break smthing elsewhere.
2. Add coalesce operators and return empty obj when undefined line 474, 475, 480?, 481?.

**Comment by isaacHagoel** [comment]
hi @mataslib thanks for this and for the other ticket and PR. I am super busy. will only get to this in a few days. I hope it is okay.

**Comment by mataslib** [comment]
Hello @isaacHagoel, sure, totally ok, thanks for letting me know.  👍

**Comment by isaacHagoel** [comment]
We can't move these lines up because the `if` block on line 470 deals with changing these settings mid way. it compare the old and new values and moving the lines up will make them always equal.
I think the fix might be as simple as checking that the previous value is defined. Something like:
```
if (isWorkingOnPreviousDrag && config.dropFromOthersDisabled !== undefined && config.dropFromOthersDisabled !== dropFromOthersDisabled) 
```
we might need to address other options as well.
does it make sense to you?
can u pls create a simple REPL i can test this with?
thanks

**Comment by mataslib** [comment]
Simple Repl: https://svelte.dev/repl/cc47b30ed2ad4e12ad4510d615b0558f?version=3.24.1

I did test this, however does not fix the issue:
> ```if (isWorkingOnPreviousDrag && config.dropFromOthersDisabled !== undefined && config.dropFromOthersDisabled !== dropFromOthersDisabled) ```

**Comment by isaacHagoel** [comment]
can you please give this branch a shot? it works with your example (notice there are 2 issues with the example, 'e' on line 20 and unique ids): `272-support-dz-created-mid-drag`
I also created this draft PR for it if u want to see the changes: #274

**Comment by mataslib** [comment]
I did test `272-support-dz-created-mid-drag` in both Repl example (sorry for those issues) and my local app and no error throwed so far. Seems to be fixed, thank you. 👍
