### ISSUE TITLE
Dragging Svelte-components triggers re-render

### ISSUE THREAD

**Issue by marco-kretz** [isaacHagoel/svelte-dnd-action#278]
Hey,

I'm trying to develop a little dashboard consisting of a couple of widgets. Each of them is a custom Svelte-component. When I drag one of them it forces them to completely re-render. For example I have a widget that loads a random meme from an API. Everytime I drag it to another position it reloads completely and shows another one.
BUT if I drag another widget which forces the Meme-Widget to move, this doesn't happen.

Code snippet:
```JS
import Meme from "./widgets/Meme.svelte";
import MusicPlayer from "./widgets/MusicPlayer.svelte";
import News from "./widgets/News.svelte";
import Todos from "./widgets/Todos.svelte";

// this is my "items" array
let widgets = [
  { id: "news-widget", element: News, size: 3 },
  { id: "todo-widget", element: Todos, size: 2 },
  { id: "meme-widget", element: Meme, size: 3 },
  { id: "music-widget", element: MusicPlayer, size: 3 },
];
```

Rendering like this:

```HTML
<div
    class="row"
    use:dndzone={{
      items: widgets,
      flipDurationMs,
      dropTargetStyle: { border: "2px dashed #ccc", borderRadius: "7px" },
      dropFromOthersDisabled: true,
    }}
    on:consider={handleSort}
    on:finalize={handleSort}
  >
    {#each widgets as widget (widget.id)}
      <div animate:flip={{ duration: flipDurationMs }} class="col col-md-{widget.size}">
        <svelte:component this={widget.element} />
      </div>
    {/each}
  </div>
```

I also have a Youtube-component modeled after https://svelte.dev/repl/db36836fce4c42938ef192ef3a8a3a4b?version=3.6.2
which is completely broken after drag.

Some help on this would be nice!

**Comment by isaacHagoel** [comment]
Happy to help but i would need a Repl demonstrating the issue or something similar

**Comment by marco-kretz** [comment]
Yeah sure: https://svelte.dev/repl/363996f952c34792b209698e7eb7400d?version=3.37.0

Grid is messed up but it shows what I mean. As soon as I change the state of a widget and drag it to another position, it re-renders.
Todo-items get removed, meme does a reload.

**Comment by isaacHagoel** [comment]
right, so what you need to do is to persist the meme url or anything else u
want to persist within the `items` array that is passed to the lib.
there is a similar example with scroll position:
https://svelte.dev/repl/eb2f5988bd2f46488810606c1fb13392?version=3.29.4

the library removes the item from the list on drag start, copies it to the
dragged object (which svelte isn't aware of) and proceeds from there.
therefore there is indeed a re-render.

**Comment by isaacHagoel** [comment]
closing. feel free to re-open if the example didn't resolve it for you
