### ISSUE TITLE
Style of dragged element lost

### ISSUE THREAD

**Issue by DavidKCalnex** [isaacHagoel/svelte-dnd-action#283]
https://svelte.dev/repl/3f94de556c6d4d90aacb81f23c53914c?version=3.22.2

Dragging the element the style works on the first mouse move then is gone.

Setting innerHTML works but the style of the dragged element is lost see above REPL.

**Comment by isaacHagoel** [comment]
what was the solution? :)

**Comment by DavidKCalnex** [comment]
Sorry i opened this on the wrong account I open it under my work account vs my personal account.
