### ISSUE TITLE
Style of Dragged Element lost

### ISSUE THREAD

**Issue by Dave3of5** [isaacHagoel/svelte-dnd-action#284]
https://svelte.dev/repl/3f94de556c6d4d90aacb81f23c53914c?version=3.22.2

Dragging the element the style works on the first mouse move then is gone.

Setting innerHTML works but the style of the dragged element is lost see above REPL.

**Comment by isaacHagoel** [comment]
@Dave3of5 
Here is the solution (i did it in two different ways, one for cards, one for columns): https://svelte.dev/repl/3d8be94b2bbd407c8a706d5054c8df6a?version=3.22.2
 
Explanation:
The style on the outer most dom element of the dragged element, especially the transforms are tightly managed by the library (it uses transforms to move it around and copies other styles from the shadow item). 
If your goal is to style it, the best thing is to operate on its children.
You can do it with transformDraggedElement like you tried (I did that for cards) or with css (I did that for columns).
I should probably add this example to the README.

Does this solve your problem?

**Comment by Dave3of5** [comment]
OK I had to create a child element then add your

	:global(#dnd-action-dragged-el .column) {

Selector now it works thanks.
