### ISSUE TITLE
Duplicates are deleted

### ISSUE THREAD

**Issue by Dave3of5** [isaacHagoel/svelte-dnd-action#287]
https://svelte.dev/repl/313d90c7999f4677b1191523c92a3aa1?version=3.22.2

Dragging item1 from TODO to DOING causes the original item1 in the list to be deleted.

**Comment by Dave3of5** [comment]
I switched the ID to use UUIDs and it's sorted.

**Comment by isaacHagoel** [comment]
ids have to be unique. u had id=1 in both columns.
