### ISSUE TITLE
Mark subitem as not drag dropable

### ISSUE THREAD

**Issue by Dave3of5** [isaacHagoel/svelte-dnd-action#288]
I have a Modal dialog that is inside an dndzone is there any way of making it so that this sub modal is not dragable ?

**Comment by isaacHagoel** [comment]
Are you asking how to make a specific child of a dndzone not draggable?
Make it not a child of the dndzone (like the column title in the board
example vs. the cards)

**Comment by Dave3of5** [comment]
So I take it there is no way of having a child element of a dndzone not draggable ?

**Comment by isaacHagoel** [comment]
Not directly.  That would break a core assumption of the lib (see Readme).
Usually there is another way to organize the markup to acheive what u want.
Alternatvely you might be able to place a mousedown+touchstart+keydown
listener on the item to set dragDisabled on the entire dnd zone to false
(and return to true on release)

**Comment by isaacHagoel** [comment]
Also, if u create a repl demonstrating the usecase, i may have more
specific advice

**Comment by Dave3of5** [comment]
Nps I just moved the modal out of the draggable as you've suggested sorry for the hassle.
