### ISSUE TITLE
Can only drag elements to exactly the next or previous dropzone

### ISSUE THREAD

**Issue by f4ww4z** [isaacHagoel/svelte-dnd-action#294]
![image](https://user-images.githubusercontent.com/21199242/120956767-db140700-c786-11eb-904b-77e345a3a81e.png)

I would like to set my dropzones so that elements can only be dragged to exactly the next or previous dropzone. For example, the 'ACCOUNTING' card from the 'Draft' dropzone can only be dragged to the 'Review' dropzone, and it cannot go to the 'Assign' dropzone.

How can I set this up? thanks

**Comment by isaacHagoel** [comment]
hi, you can dynamically set `dropFromOthersDisabled` based on which zone drag started on.

**Comment by f4ww4z** [comment]
@isaacHagoel is there any example I can follow?

**Comment by f4ww4z** [comment]
@isaacHagoel if I set the trigger to `DRAG_STARTED`, only the dropzone which the item was dragged from will check my custom condition that will set `dropFromOthersDisabled`. I want other dropzones to check this too.

**Comment by isaacHagoel** [comment]
@f4ww4z sorry for the long delay. I totally missed your replies.
this is achievable using a store. 
closing for now but happy to help if this is still relevant.
