### ISSUE TITLE
Storing value of child component inside parent DnD component

### ISSUE THREAD

**Issue by bianchi-dy** [isaacHagoel/svelte-dnd-action#298]
**Context**
I have created a drag-and-drop table where each DnD component also contains a dropdown menu child component. 

**Desired outcome**
My goal is that the individual drag and drop components store whatever value was given to the dropdown menu child component.

**Issues**
Based on this `handleSort` function:
```
	function handleSort(e) {
		items = e.detail.items;
       }
```

I understand that the callback returns an event `e` which contains the resorted items according to their new order in the drag and drop component. In my current code, I store the current value of the dropdown menu in a given DnD component inside this items list, and have tried to change it by using handleSort but it still appears to link the previous order and the current order of the DnD components together. 

![svelte](https://user-images.githubusercontent.com/44487900/122195954-613bf600-cec9-11eb-8cd1-f4aea87a6dcf.gif)

Here are the relevant code snippets:

```
function handleSort(e) {
items = e.detail.items;
     }

  function handleSelect(event,i) {
    let bv = event.detail['bv']
    total = 0
    console.log('!!!',i, event.detail)
    items[i]['selectedValue'] = event.detail

    for (let j = 0; j < items.length; j+=1) {
      if (items[j]['selectedValue'] != undefined) {
        total += items[j]['selectedValue']['bv']
      }
    }
}

    <section use:dndzone={{items}} on:consider={handleSort} on:finalize={handleSort}>
      {#each items as item (item.id)}
        <div class='dnd'>
          <h2>{item.title} {item.id}</h2>
          <span><Select items={tableData} {groupBy} {getOptionLabel} bind:value={item['selectedValue']}
          selectedValue={item['selectedValue']}
          {getSelectionLabel} 
          placeholder="Select an element" 
          on:select={(event, j) => handleSelect(event, item.id)}></Select></span>
          </div>
      {/each}
    </section>
```
How do I go about saving the values in each drop down menu to their individual drag and drop components, such that these don't get linked to other drag and drop components or erased completely? Is this possible with a simple workaround or am I missing something here? Let me know if I need to provide information, since I'm not sure if my explanation was clear enough.

**Comment by isaacHagoel** [comment]
Hi,
I haven't looked into the details yet (would be super helpful if you could
make a REPL for me to play with).
In general, anything that's within the items data array will be preserved
Have you seen this example?
https://svelte.dev/repl/eb2f5988bd2f46488810606c1fb13392?version=3.29.4

**Comment by bianchi-dy** [comment]
Thanks for the REPL example! I'll check it against our case and see if it works.
