### ISSUE TITLE
Constrain drag axis

### ISSUE THREAD

**Issue by inwardmovement** [isaacHagoel/svelte-dnd-action#305]
Is it possible to constrain drag axis, for example to allow drag only on the vertical axis for vertical lists, whatever the cursor position?
I think it would give a better UX.

![image.png](https://user-images.githubusercontent.com/9438102/126470099-33a38193-834a-4512-8199-6257bdadbfd3.png)

**Comment by isaacHagoel** [comment]
It is not currently supported but shouldn't be very difficult to add.
Is it for a single list usecase?

**Comment by inwardmovement** [comment]
Yes for a single list use case as far as I'm concerned, but it should work in all cases I think (be a "general" drag and drop/UX behaviour).

Any idea how we could achieve that?

**Comment by isaacHagoel** [comment]
It will require enhancing the library. There is a piece of code (in
pointerAction.js if i recall) that updates the transform of the dragged
element based on the mouse movement. It will need to only update the x or y
coords when this option (new option) is enabled

**Comment by inwardmovement** [comment]
Are you willing to add this feature?
Do you want me to try a PR?

**Comment by isaacHagoel** [comment]
If you want to give it a shot it would be great. If not, i will try to make
time for it

**Comment by inwardmovement** [comment]
I think it's on lines 217-219 of `pointerAction.js`, but I can't manage to make it work. I tried with the first parameter at `0` but it doesn't change anything.

**Comment by isaacHagoel** [comment]
You've found the right place. Changing line 217 to 
```javascript
draggedEl.style.transform = `translate3d(0, ${currentMousePosition.y - dragStartMousePosition.y}px, 0)`;
```
results in locking the initial X coords (see capture). Are you sure you used the modified version (did u use npm link to a local copy)?
https://user-images.githubusercontent.com/20507787/126577993-5ca408ff-2b25-4712-b506-5266a7f7298f.mov

**Comment by inwardmovement** [comment]
Nice! No I didn't use npm link... I thought rebuilding with another output dir was fine.

**Comment by isaacHagoel** [comment]
cool. please let me know.

**Comment by isaacHagoel** [comment]
closing for now as "won't do unless more people need this". still open for a MR.

**Comment by ChugunovRoman** [comment]
@isaacHagoel @inwardmovement I created [PR](https://github.com/isaacHagoel/svelte-dnd-action/pull/429) by this issue
