### ISSUE TITLE
Any way to use Svelte actions in a javascript app using something like the Client Side Component API?

### ISSUE THREAD

**Issue by newlegendmedia** [isaacHagoel/svelte-dnd-action#309]
I am using a couple Svelte components imported into my existing js app and creating them using New(). I was wondering if Svelte actions like dnd-action could be imported and used in an existing js app? Seems like that might be a stretch?

**Comment by isaacHagoel** [comment]
Not a stretch at all
A svelte action does not depend on svelte. It is just a function that takes
a dom element as the first parameter and an options object as the second.
It returns an object with two functions "update" (takes new options) and
"destroy".
You can use this api from plain JS with no problems.
The only thing you will miss is the flip animations but that's not that
hard to code

**Comment by newlegendmedia** [comment]
Ok, I can see that now. There aren't actually any svelte files involved here directly. Thanks! I'll give it a try :-)
