### ISSUE TITLE
[Feature Request] Type per item

### ISSUE THREAD

**Issue by mataslib** [isaacHagoel/svelte-dnd-action#314]
Motivation (Usecase): I have dndzones: **Section** > 1-n **Columns** > n **Elements**.  I have palette of elements dndzone and those elements are draggable into Columns (it's copy on drag). So Column dndzone and Elements palette dndzone share same type. However there are special elements such as Header and Footer, which should always be placed only inside single column section (two footers/headers next to each other makes no sense). Those two elements would behave as section and have same object shape (but they will still display inside elements palette dndzone) and therefore they should share type with Section dndzone, not with Column one as other elements do. Hence the need to set the type per item, not per zone.

Implementation: There would be special property on item checked for type such as "type". Property name should be changable via setter in same fashion as id one is. It would have higher priority than zone's type. As "type" is very common property name, maybe it should be named more unique eg. "dnd-type" if we don't want to make this feature BR change.

---
PS: Excuse me for not writing you back, I got sick. I will start with PR for this one.

**Comment by isaacHagoel** [comment]
revisiting this after a long time.
doesn't changing the zone types dynamically (ex: based on the dragged element) address this usecase?
