### ISSUE TITLE
Support for dragging multiple elements

### ISSUE THREAD

**Issue by brettinternet** [isaacHagoel/svelte-dnd-action#318]
Hi, this library is fantastic. Thank you for sharing it.

Is there support for selecting multiple items for drag and drop actions?

**Comment by isaacHagoel** [comment]
No. currently only a single item can be dragged at a time.
Always open to ideas/ pull requests though.

**Comment by isaacHagoel** [comment]
@brettinternet Not sure if it is still relevant for you but it turns out it is possible  to achieve multi-drag without any new features. I have created [this example](https://svelte.dev/repl/c4eb917bb8df42c4b17402a7dda54856?version=3.24.1). Will probably add to the README soon.

**Comment by brettinternet** [comment]
Wow that's wonderful. Thanks for sharing that example, you've done an awesome job with this library.
