### ISSUE TITLE
Question: any expected weird behavior by giving the animation a different `flipDurationMs`?

### ISSUE THREAD

**Issue by brunobely** [isaacHagoel/svelte-dnd-action#325]
Playing with the REPL I noticed that I could make the interactions feel more natural by giving `use:dndzone` a low `flipDurationMs` (something like 50) and the flip animation something like 150. Would there be any expected weirdness from setting those properties to different values? I didn't notice any, but I also haven't read the entire source.

My biggest gripe with a higher `flipDurationMs` value in `use:dndzone` is that I need to hold the item onto the spot I want it to go under for a longer time before animations start, which strikes me as unnatural.

**Comment by isaacHagoel** [comment]
Hi, 
The lib uses the flipDuration as the interval in which it samples the dragged element position while dragging.
it has a min of ~100ms (it is arbitrary, didn't want to consume too much CPU) so if you pass in 50 it will still be slightly higher. 
I also like to configure the flip animations to 100-150 ms to make it feel snappy. maybe it should be the default.
anyhow, what you're doing shouldn't cause any issues

**Comment by brunobely** [comment]
Neat-- thanks for the quick reply!
