### ISSUE TITLE
Property 'onconsider' does not exist on type 'HTMLProps<HTMLElement>'

### ISSUE THREAD

**Issue by Addeuz** [isaacHagoel/svelte-dnd-action#326]
Hello, I have implemented a dnd functionality for my app with this library and when I finally figured out how to "massage" my data into the array forms needed for the library to work everything works great.

The only problem (not really a problem just annoying) is with the events `on:consider` and `on:finalize`.
Svelte is complaining about that they don't exist on the 'HTMLProps<HTMLElement>' type. My code builds and everything works but it's just annoying to have an error..

Is there something I need to do to get Svelte/TypeScript to recognize the events?

<details>
<summary>Full error message</summary>
<br>
    
    Message:
    Type '{ onconsider: (event: any) => void; onfinalize: (event: any) => void; }' is not assignable to type 
    'HTMLProps<HTMLElement>'.
    Property 'onconsider' does not exist on type 'HTMLProps<HTMLElement>'.
    
    Object:
    {
        "resource": "/home/andreas/gitrepos/dfmain/audit/src/components/account_balance/Group.svelte",
        "owner": "_generated_diagnostic_collection_name_#2",
        "code": "2322",
        "severity": 8,
        "message": "Type '{ onconsider: (event: any) => void; onfinalize: (event: any) => void; }' is not assignable to type 'HTMLProps<HTMLElement>'.\n  Property 'onconsider' does not exist on type 'HTMLProps<HTMLElement>'.",
        "source": "ts",
        "startLineNumber": 46,
        "startColumn": 7,
        "endLineNumber": 46,
        "endColumn": 18
    }

**Comment by isaacHagoel** [comment]
hi,
have you tries [this](https://github.com/isaacHagoel/svelte-dnd-action#typescript)?

**Comment by isaacHagoel** [comment]
closing for now. pls re-open if needed

**Comment by Addeuz** [comment]
Sorry for not responding, but yes that fixed it.
