### ISSUE TITLE
dropzone same as drag element

### ISSUE THREAD

**Issue by ivanjeremic** [isaacHagoel/svelte-dnd-action#329]
I come from React.js and there I was able for an edge case to have my dropzone be same time my draggable element too, so each element can be dragged but also dropped in to same type of elements(dropzones). Is this here possible too?

**Comment by isaacHagoel** [comment]
Hi,
Have you seen the example titled "crazy nesting" in the readme?

**Comment by ivanjeremic** [comment]
Just decided to stay with React it is much more flexible and robust, thanks anyway.

**Comment by isaacHagoel** [comment]
alright. good luck sir

**Comment by isaacHagoel** [comment]
Did you check the Typescript section in the readme?
