### ISSUE TITLE
dropTargetClasses is typed wrong for typescript

### ISSUE THREAD

**Issue by vipero07** [isaacHagoel/svelte-dnd-action#330]
When adding multiple classes to the dropTargetClasses property typescript complains that it isn't an array with a single string. Instead of [string] it should be typed string[]. 

This isn't critical as it doesn't prevent compilation or functionality, but it is a bit of an annoyance.

![image](https://user-images.githubusercontent.com/4421342/144624871-d8d7237d-f0db-4ea4-983b-634dd9264c0a.png)

**Comment by isaacHagoel** [comment]
@vipero07 thanks for letting me know. fixed
