### ISSUE TITLE
Flickering items after drop. (REPL)

### ISSUE THREAD

**Issue by ivanjeremic** [isaacHagoel/svelte-dnd-action#332]
I have a problem that after I drop an item it quickly flickers (loses the background color). Here is the REPL [https://svelte.dev/repl/0502bb7c2adf4f23adb6c4a356263dbb?version=3.22.2](https://svelte.dev/repl/0502bb7c2adf4f23adb6c4a356263dbb?version=3.22.2)  (Make the preview in the REPL bigger to see all items better)

I have the same issue locally too, and I was not able to find the reason. Seems like it rerenders.

**Comment by isaacHagoel** [comment]
this can happen when there is an issue with how the css selectors target the items. I haven't dug into the example because I know you have decided to stay with your current implementation of the app. Feel free to reopen if needed.

**Comment by ivanjeremic** [comment]
I came back to rewrite the app in svelte, this issue is still very important to me and I would like to fix it.

**Comment by isaacHagoel** [comment]
remove `hover:scale-105 duration-300 ease-out` and the blinking stops. this is not related to the lib

**Comment by ivanjeremic** [comment]
> remove `hover:scale-105 duration-300 ease-out` and the blinking stops. this is not related to the lib

The same project in tailwind react + react-dnd has no flickering after drop.

**Comment by TheophileMot** [comment]
@isaacHagoel I've been experiencing flickering also, but I can't tell whether it's this library or the component library I'm using (Carbon).

This is what happens on drag and drop:

![Feb-14-2022 14-56-33](https://user-images.githubusercontent.com/34871447/153937491-66a9e23d-fa19-40de-9b4c-52d0b19658d3.gif)

Here is a [REPL](https://svelte.dev/repl/abd3a1f9a0a64906bc423964bbdbcf9f?version=3.46.4). Any ideas?

I'll cross-post this to the `carbon-components-svelte` repo.

**Comment by ivanjeremic** [comment]
I still experience this issue and I see others as well, maybe reopen the issue?

**Comment by TheophileMot** [comment]
@ivanjeremic It is related to the transition that's played on the hover state. If you remove that, the flickering goes away. (See Isaac's comment above.)

It would be great to be able to use transitions, though. @isaacHagoel Is there a way to do this without having the transition/animation reset when you start dragging?

![Apr-20-2022 13-16-46](https://user-images.githubusercontent.com/34871447/164287132-8d6db524-a9b4-4424-93d5-02f540a3583b.gif)

**Comment by ivanjeremic** [comment]
> @ivanjeremic It is related to the transition that's played on the hover state. If you remove that, the flickering goes away. (See Isaac's comment above.)
> 
> 
> 
> It would be great to be able to use transitions, though. @isaacHagoel Is there a way to do this without having the transition/animation reset when you start/stop dragging?
> 
> 
> 
> ![Apr-20-2022 13-16-46](https://user-images.githubusercontent.com/34871447/164287132-8d6db524-a9b4-4424-93d5-02f540a3583b.gif)

Like you said only if I remove the transition but this is not a solution since I need transition to work.

**Comment by ivanjeremic** [comment]
I solved that now after a long pause on the project by just setting these classes ```js
class:ease-out={easeOut}
 class:duration-300={easeOut}
``` to `false` inside `handleDndConsider` and back to true in `handleDndFinalize`
