### ISSUE TITLE
Is there a way to have a non-draggable element in the dndzone?

### ISSUE THREAD

**Issue by Fedeorlandau** [isaacHagoel/svelte-dnd-action#334]
Hello folks, thank you for this amazing library.

I was wondering if there is a way to make a child of dndzone not draggable, check this:

https://svelte.dev/repl/79d20aa7e7264fbbbc9145a3f98a2b87?version=3.22.2

![image](https://user-images.githubusercontent.com/10283686/145228923-bc513332-003d-480a-9c2e-1d0fc419b36b.png)

The issue is that the `<div>` enclosing the input and the button is draggable and it's causing a few issues. 
Why do I need this? because I'd like to keep the dndzone full height and this "new item" div always at the bottom of the last item. 

Regards!

**Comment by Fedeorlandau** [comment]
Found this question, https://github.com/isaacHagoel/svelte-dnd-action/issues/327 which is pretty much what I'm trying to accomplish.

**Comment by isaacHagoel** [comment]
Hi, 
First of all thanks for making pull requests!
I am trying to understand the usecase for this.
1. Why not add the footer element the same way that the header (TODO, DOING etc) is added (outside of the zone)?
2. Do you ever need/want those disabled items to be in the middle of the list?

For #327 I offered a solution in the last comment but I don't know if the ticket creator gave it a shot.

**Comment by Fedeorlandau** [comment]
Hi there. I just updated my PR to introduce this non-draggable elements into the drop-zone. I've reverted the disableDrag option on the items because I need to update the keyboardAction file which I forgot lol.

1. Because if you have an empty column without a min-height it's pretty hard to drop the items there. If you add the min-height to give the drop zone more room then the "Add new item" card has a bad "margin-top" (which is the min-height of the dropzone). It's basically for giving more room on the dropzone to drop items.
2. I've reverted the disabledDrag option on items. It doesn't make sense at this point.

You're welcome!

**Comment by isaacHagoel** [comment]
instead of adding an element in order to control the height (is there any other reason we are adding it there?), can we instead add an option to treat the dropzone as if it is bigger?
something like `zoneMargins: 0 0 0 100px` or whatever (defaults to all zeros).
then in the calculations that determine whether the centre of the dragged element is inside we can simply offset the rect coordinates by the given numbers.
what do you think?

**Comment by Fedeorlandau** [comment]
@isaacHagoel  that makes totally sense. Adding that element inside the dndzone is more of a hackish solution for the height issue. There is no other reason for it.

I'll explore adding that in a few hours. Feel free to close the PR :)

**Comment by isaacHagoel** [comment]
@Fedeorlandau hi, any updates on this?

**Comment by Fedeorlandau** [comment]
Hi @isaacHagoel I couldn't find a way to increase the min-height for it. Sorry.
