### ISSUE TITLE
Help me. drag item dispear

### ISSUE THREAD

**Issue by yangshangbo** [isaacHagoel/svelte-dnd-action#339]
i created a online example:
https://codesandbox.io/s/youthful-architecture-y0vvm?file=/App.svelte

I drag link - 2 to link 1 or drag link 1 to link 2, it works nice.
then when i drag Sub Menu - 1 to Sub Menu - 2, it works also. but when i drag Sub Menu - 2 to Sub Menu - 1, the Sub Menu - 2 dispeard. 
how to fix this problem?

**Comment by isaacHagoel** [comment]
Hi,
It is a pretty large example. will try to make time to debug it over the weekend.
In the meanwhile you might want to try importing and using `setDebugMode` from the library and looking at console's debug output. as you drag the problematic around. 
The fact that the other items don't make room for it as you drag it over them is highly suspicious.

**Comment by yangshangbo** [comment]
> Hi, It is a pretty large example. will try to make time to debug it over the weekend. In the meanwhile you might want to try importing and using `setDebugMode` from the library and looking at console's debug output. as you drag the problematic around. The fact that the other items don't make room for it as you drag it over them is highly suspicious.

Thank you for your help. i add {#if} block at the root of Menu component.it resovled the problem.

**Comment by isaacHagoel** [comment]
@yangshangbo cool. where exactly did u need to add the if block?

**Comment by yangshangbo** [comment]
> @yangshangbo cool. where exactly did u need to add the if block?

i updated the code on the codesandbox.
