### ISSUE TITLE
Is there something similar to 'ondragenter' event?

### ISSUE THREAD

**Issue by ivanjeremic** [isaacHagoel/svelte-dnd-action#345]
I need to fire a function when the dragged element is over another element in the list, is there something in svelte-dnd-action
I can do? The vanilla events do not work.

**Comment by isaacHagoel** [comment]
U have the consider events. What are you trying to implement (from the user
perspective what are you trying to make happen)?

**Comment by ivanjeremic** [comment]
`ondragenter` works differently, it is fired when when the element I drag enters another element in the dndzone, `on:consider` is firing too but it fires as soon as I pick up my element and start dragging, also it gives me only data about the dragged element instead of the element I'm over.

```
function handleDndConsider(e) {
    items = e.detail.items;
    console.log("items", e.detail.info);
  }
``` this is always logging the data of the element I hold/drag and not the element I `dragenter`. this is a very important feature of every dnd lib no matter which framework, is there any way to get the data of the Item I enter.

**Comment by isaacHagoel** [comment]
Your array of items has the shadow element which is the element you're
hovering over. It has the id of the dragged element (which you get in the
handler) and a marker (see readme). If you tell me what you are trying to
achieve from a user/ functionality perspective i might be able to help you

**Comment by isaacHagoel** [comment]
closing due to lack of response.
let me know if you still need help with this
