### ISSUE TITLE
Async load with sveltekit

### ISSUE THREAD

**Issue by thousandsofraccoons** [isaacHagoel/svelte-dnd-action#346]
Hello, I found that the library has been bundled and loaded right away, it affects the Lighthouse score. 
The first seconds of page load of the library are not critical, so I thought to load it asynchronously, smth like this:

```
  let dndzone
  async function getDndZone() {
    dndzone = await import("svelte-dnd-action")
    return
  }
  

  onMount(async () => {
    await getDndZone()
  })
  {#if dndzone}
    blahblah
  {/if}
```

As you might expect - this idea failed with 
```Uncaught (in promise) TypeError: ctx[9].call is not a function``` 

What can I do to remove the library from the initial bundle?

**Comment by isaacHagoel** [comment]
like this?
https://svelte.dev/repl/d7e1e907b3e445d6a7aff9c24c556a02?version=3.46.2

**Comment by thousandsofraccoons** [comment]
@isaacHagoel thank you, Isaac, it works well. Although it causes more damage than synchronous loading due to increased CLS. So I tried a workaround like this: https://svelte.dev/repl/2167c514c497450e929f7ef138529293?version=3.46.2 

I wonder if it's possible to create a synchronous facade for the library that would be exported in the usual way, and inside would call the rest of the logic asynchronously and add listeners after all content on the page has been rendered?

**Comment by thousandsofraccoons** [comment]
Answer to this question was found in Russian-speaking svelte community in Telegram - https://svelte.dev/repl/3f592b0c6286491ebde67b7a770fd3cb?version=3.46.2

This doesn't cause CLS

**Comment by isaacHagoel** [comment]
@thousandsofraccoons well as David Wheeler said  “All problems in computer science can be solved by another level of indirection." 😄 
Thanks for sharing the solution. Does it actually make the page interactive faster or does it "just" make lighthouse happy (I know it is important for SEO)?

**Comment by thousandsofraccoons** [comment]
@isaacHagoel it just makes lighthouse happier :)
