### ISSUE TITLE
Items disappear on move

### ISSUE THREAD

**Issue by kevin192291** [isaacHagoel/svelte-dnd-action#347]
Hello,
I am using the latest version of svelte-dnd-action (4.0.0).
the trouble is that when I attempt to move an item, it disappears. I have no clue why this
started to happen. I have posted a public repo of my code that I am just playing with here: https://github.com/kevin192291/svelte-dashboard-boilerplate
If you click the Menu (top right) and hit dashboard, you will see 4 cards that should be draggable. I have no clue why this started to happen. The code is here: https://github.com/kevin192291/svelte-dashboard-boilerplate/blob/master/src/routes/dashboard/index.svelte

Any help at all would be greatly appreciated!!!

Thanks,
-Kevin

**Comment by isaacHagoel** [comment]
it would help a lot if you reproduce the issue in a REPL and send me a link.
usually disappearing items mean faulty consider/finalize handlers.

**Comment by isaacHagoel** [comment]
closing this due to lack of response. 
@kevin192291 feel free to reopen if you still need help
