### ISSUE TITLE
dragging breaks binding

### ISSUE THREAD

**Issue by TheophileMot** [isaacHagoel/svelte-dnd-action#351]
It seems that dragging an item can break bindings to its properties. For context, I have some draggable components that fetch data. If the items look like this:
```
	let items = [
		{ id: 1, options: { title: 'A' }, data: {} }, 
		{ id: 2, options: { title: 'B' }, data: {} }, 
		{ id: 3, options: { title: 'C' }, data: {} }, 
	];
```
then dragging the items will prevent any future updates of `data`. As a workaround, I found that the binding is retained for subobjects, thus:
```
	let items = [
		{ id: 1, options: { title: 'A', data: {} } }, 
		{ id: 2, options: { title: 'B', data: {} } },
		{ id: 3, options: { title: 'C', data: {} } },
	];
```
(This is fine for now, but I'd rather not have to put `data` inside another object; it doesn't really belong in `options`.)

Here's a demonstration of the behaviour ([try it on the REPL](https://svelte.dev/repl/b988023cfed546e08be22276beb84569?version=3.24.1)):

![Feb-11-2022 18-47-15](https://user-images.githubusercontent.com/34871447/153685636-e8c6f304-ca87-418e-9bb6-c303802d6461.gif)

Is this a bug, or am I missing something?

**Comment by isaacHagoel** [comment]
sorry for the delay. this is strange. It doesn't reproduce for me on a REPL version 3.24.1. Does it reproduce for you?
i have to ask though, why do you need to bind at all? I am probably missing where it is being put to use

**Comment by TheophileMot** [comment]
It's mysterious, isn't it? The REPL still reproduces for me. But you're right, the structure of the code doesn't entirely make sense; in the meantime, I rewrote everything in a much more reasonable way, and my new code is working fine. With that in mind, feel free to close this.

**Comment by isaacHagoel** [comment]
thanks. will close for now
