### ISSUE TITLE
Q: Vertical positioning for timetable component?

### ISSUE THREAD

**Issue by vlntsolo** [isaacHagoel/svelte-dnd-action#354]
Hi! I was looking for a neat Svelte dnd implementation and looks like I found it. Thanks! Just a quick question.
My component requires something similar to calendar daily timetable. So I wonder if it's possible to allow absolute positioning inside drop container? So that I could move the div and track its new start and end Y coordinate?

Looped through the issues and found this thread. And it might work.
[Issue 257](https://github.com/isaacHagoel/svelte-dnd-action/issues/257)

Did I miss something?

**Comment by vlntsolo** [comment]
Sure, here's the sketch. 

![](https://i.ibb.co/RSSWx6L/Screenshot-from-2022-02-18-13-05-40.png)

`
In general, dragging absolutely positioned elements is usually quite easy to implement from scratch (if there is no list re-sorting involved)
`
Agree, I just didn't want to reinvent the wheel.  Will look into it.

**Comment by isaacHagoel** [comment]
thanks. How should absolute positioning come into play?

**Comment by vlntsolo** [comment]
I'd like to disable automatic alignment of the block in the drop zone. So i could drop it anywhere alongside the container. Thus I will have something like Google calendar, to position event on the timeline. Is it possible to tweak it somehow? I've noticed that (this solution)[https://github.com/isaacHagoel/svelte-dnd-action/issues/257] doesn't play well with mobile screens

**Comment by isaacHagoel** [comment]
if the REPL from #257 works for you besides the lack of mobile support,
this could be fixed quite easily.
See the TODOs in the code. It currently doesn't listen on the touch events
at all (need to listen on touchmove and maybe touchstart and touchend,
notice you need to use e.touches[0] instead of e)

**Comment by vlntsolo** [comment]
Thanks for the hints. I'll share final code once done with modifications.
