### ISSUE TITLE
dropTargetClasses option glitches with nested lists

### ISSUE THREAD

**Issue by jesteracer** [isaacHagoel/svelte-dnd-action#355]
When using dropTargetClasses inside nested lists the options works fine if you work on the deepest level, but, glitches when working on the top level (I only tested this in two level deep model)

Here is a working repl
https://svelte.dev/repl/03df0475706d4496900e96b895a119ba?version=3.22.2

there is a global class (.target-example-glitch) that is applied via option on all the DND components
and a here is a gif. 

![CleanShot 2022-02-22 at 19 37 36](https://user-images.githubusercontent.com/823333/155178034-1bc576d5-e330-42d6-9b0c-3682d8ff0da6.gif)

**Comment by isaacHagoel** [comment]
looks like a bug. i will try to make time to dig in soon.

**Comment by isaacHagoel** [comment]
ha, this was an interesting one. 
fixed in version 0.9.16.
