### ISSUE TITLE
Disable drag and drop

### ISSUE THREAD

**Issue by pjebs** [isaacHagoel/svelte-dnd-action#359]
Is there a way to disable the entire dragging functionality based on for example a prop change.

`dragDisabled` seems to do something else.

**Comment by webdagger** [comment]
Works fine in this [repl](https://svelte.dev/repl/daa6408755704851984ee79de944eaaa?version=3.22.2)

**Comment by isaacHagoel** [comment]
dragDisabled and dropFromOthersDisabled can be combined

**Comment by pjebs** [comment]
Beautiful.
