### ISSUE TITLE
performance on mobile touch device

### ISSUE THREAD

**Issue by pjebs** [isaacHagoel/svelte-dnd-action#361]
I have a grid with dnd action as the main content.
My app is a "web-app" for mobile devices.

The site is finding it very difficult to differentiate between drag attempts of the row items and scrolling the page.

Is there a setting to increase a timer value so it knows when someone is attempting to scroll vs drag?

**Comment by isaacHagoel** [comment]
Which timer? The sampling interval while dragging? It is affected by
'flipDurationMs'.
Not sure it it would help though. Can you make a REPL that shows the issue?

**Comment by pjebs** [comment]
Here is an example: https://svelte.dev/repl/5cb0833984464c7cb203997a362fb90c?version=3.46.4


If you don't have a mobile device available, you can go to Chrome's dev settings and change it to "iPhone SE" mode for example.

You will see that since the list is long, you can't drag the rows and scroll the page easily.

**Comment by pjebs** [comment]
If it just want to scroll (no drag), it's practically impossible.

**Comment by isaacHagoel** [comment]
Well the draggable area covers the full viewport. How could the lib (or
anyone) tell whether the user is trying to scroll or drag?
One possible solution is to trigger drag only on long press but even that
won't be perfect...
What did u have in mind?

**Comment by pjebs** [comment]
I guess the drag begins on a long-press is what I had in mind too.

**Comment by isaacHagoel** [comment]
There is a long press example in one of the other issues. It needs to be
enhanced a bit to support touch (listen on touchstart and touchend). I can
try to find it when next to a computer

**Comment by pjebs** [comment]
Is it hard to implement that into the library itself since mobile websites take probably 50%+ of the traffic now-a-days?

**Comment by pjebs** [comment]
I found one of your repl: https://github.com/isaacHagoel/svelte-dnd-action/pull/269#issuecomment-817119047

It seems to work really well with mouse but it doesn't work at all with touch.

**Comment by isaacHagoel** [comment]
Normally the ux designer will leave some space to the right of the dnd
container to allow the user to scroll afaik

**Comment by isaacHagoel** [comment]
Easy to add. Need me to do it or can u figure it out?

**Comment by pjebs** [comment]
It seems beyond my abilities to implement the touch modifications to your example.

**Comment by isaacHagoel** [comment]
i added some basic touch support
https://svelte.dev/repl/912fe57ee4af4f08a49e3f3ff16a1abb?version=3.46.4
but i had to preventDefault on touch start which beats the whole idea of
scrolling.
I suggest adding drag handles instead

**Comment by pjebs** [comment]
I see. The example seems to error out too.

Anyway, thanks for trying your best.

**Comment by pjebs** [comment]
Do you think this PR is usable for this purpose?

**Comment by isaacHagoel** [comment]
it doesn't error out for me. what error do you get?
this PR is currently in limbo. you are welcome to pick it up (see the discussion).
with that said, i don't think longpress would actually solve your problem

**Comment by pjebs** [comment]
Do you it might be easier to add some kind of wrapper where I intercept the touch down and modify it into a mouse down?

**Comment by isaacHagoel** [comment]
Not sure i am following
