### ISSUE TITLE
Error when container component is destroyed during pointer drag

### ISSUE THREAD

**Issue by mzmcgrat** [isaacHagoel/svelte-dnd-action#362]
When a dnd parent component is destroyed while one of its elements is being dragged via the pointer, an error is thrown:
Uncaught TypeError: dropZones is undefined

Here is a REPL that demonstrates this error:
https://svelte.dev/repl/6e3faa18088f4e96bc9cde3b56eb27ec?version=3.46.4

To replicate, start to drag any element within the first 5 seconds (I arbitrarily chose this event), and hold without releasing until 5 seconds has elapsed.  When Component1 is switched with Component2, the error is triggered upon pointer move or mouseup.  I set a simple 5 second timeout to switch the dnd parent component for another one, but in general, the event could be triggered by anything. For example:

- The user is dragging an element and uses the keyboard to navigate away from the route with the dnd element, causing it to be destroyed
- The user uses a mouse button to do the same as above
- An external event causes the parent component to be destroyed or switch with another during pointer drag

I would expect that the drag would be canceled when the container is destroyed, since the drag was never completed.

**Comment by isaacHagoel** [comment]
So if any of the zones is destroyed during drag, should the dragged item
disappear and drag be cancelled?

**Comment by mzmcgrat** [comment]
My use case currently only involves dragging items to reorder within a single zone, but I would imagine that if a drop zone is destroyed, any item being dragged should not be able to drop in it (seems like obvious behavior to me), and that if the item's source zone is destroyed, then the item should disappear and the drag be canceled (others may disagree).

However, if on:consider on the destroyed zone/component has already been triggered, then that might create some issues if the event handler has already mutated the corresponding items array.  I'm not expert enough on svelte lifecycle hooks to know whether something like an on:canceled event would help.  Maybe other drag and drop libraries have some guidance for expected behavior here.

In any case, I think it's up to the developer to make sure that only on:finalize events signal permanent changes, or to include their own logic for destroyed components when on:finalize hasn't triggered yet.

**Comment by isaacHagoel** [comment]
Thanks for the input. I will try to make time to look at it this week

**Comment by isaacHagoel** [comment]
I played with it a bit today. It is easy to solve for the single zone case but not so for more complex scenarios. 
I don't think it is a common issue, so I believe there is no urgency here and I can take some time and give it more thought.

**Comment by 99bits** [comment]
This issue seems to be present also in the Accordion that I am trying to make.

**Comment by isaacHagoel** [comment]
Well that's your answer then. Don't remove dropzones during drag, just
shrink thier height to zero. Even after this issue gets fixed removing zone
is likely to cancel the drag operation altogether

**Comment by isaacHagoel** [comment]
@mzmcgrat this is now fixed
@99bits try the accordion with the latest version (0.9.18), removing and readding the zone might still not produce the desired result, i am not sure.. ideally you would have an accordion that doesn't do it but... it might just work
