### ISSUE TITLE
Use double-click to move item to another list?

### ISSUE THREAD

**Issue by bluepuma77** [isaacHagoel/svelte-dnd-action#364]
Thanks for this great library!

Is there an easy way to use a double-click to move the clicked item to the bottom of another list?

I only have 2 lists with lots of items, it would be easier with double click if the user needs to move half of the items.

<img width="200" alt="svelte-dnd-action" src="https://user-images.githubusercontent.com/5221187/159001838-6afa5f54-4f7d-47ac-aa01-98ba26e3434e.png">

[Svelte REPL of two lists](https://svelte.dev/repl/dea50614b5154f31a9e31b7fccd2b380?version=3.46.4)

**Comment by isaacHagoel** [comment]
you can do it for sure regardless of this lib and it won't get in your way.
What you need to do is add a dblckck event handler on each item which
reports to the parent that the item was double clicked, The parent can then
move it to the other list.
I hope it makes sense.

**Comment by bluepuma77** [comment]
Thanks @isaacHagoel, it makes sense. Just how do I get the item (id) within the `dblclick`?

It seems you added some special handling for `on:click` within your library. Should I add similar for double-click?

**Comment by isaacHagoel** [comment]
@bluepuma77 https://svelte.dev/repl/9b2589b30fd9413fb2db612fd80bdb59?version=3.46.4

**Comment by bluepuma77** [comment]
Thanks a lot!

That's the piece of info I was missing: how to get the item id
```
 <div on:dblclick={e => handleDblClick(item.id, e)}>
```
