### ISSUE TITLE
Added non-passive event listener to a scroll-blocking 'touchstart' event

### ISSUE THREAD

**Issue by Addeuz** [isaacHagoel/svelte-dnd-action#367]
We use this library to create 10 different sections with 8-15 items in each section.
And the drag and drop aspect works great. But we get this warning when logging in "Verbose" mode in chromium based browsers:
![image](https://user-images.githubusercontent.com/12641358/161557349-e433afda-55be-4cb6-b115-9e3b6bfbe6de.png)

This is the url: https://www.chromestatus.com/feature/5745543795965952

We haven't had any issue with the scrolling as the warning suggest we should have. Just wanted to maybe put some attention to it if it needs to be solved.

And also, "dragging" an item makes the number (774) go up drastically. I guess it has something to do with the rerendering.

**Comment by isaacHagoel** [comment]
the lib adds a non passive listener on touch start to prevent the screen from panning while you drag on mobile.
i am not familiar with any other way to achieve this effect. I know the browser complains about it. 
closing this for now - if u have an idea for how to do this better pls do reopen.

**Comment by seanke** [comment]
Sorry I know this is an old issue. I was just wondering if it would be worth telling the browser that the touchstart event should be non passive, so that the library doesn't cause these warnings.

`draggableEl.addEventListener("touchstart", handleMouseDown, { passive: false });`
