### ISSUE TITLE
[Feature Request] Adding a class to the dragged element

### ISSUE THREAD

**Issue by KevsRepos** [isaacHagoel/svelte-dnd-action#370]
There should be an option to append classes to the currently dragged element. The current way with the `transformDraggedElement` seems nonsense to me. Just adding an option like `draggingElementClasses: Array<string>` would be much easier.

**Comment by isaacHagoel** [comment]
transformDraggedElement is for a different usecase. The dragged element has
an id u can use

**Comment by KevsRepos** [comment]
Would it be possible to clarify in the docs on how to use this? Setting styles to this id `#dnd-action-dragged-el`, `:global(#dnd-action-dragged-el)` seems to have no effect on the dragged element.

**Comment by isaacHagoel** [comment]
The global version should work unless it competes with one of the styles
that are copied from the shadow element.
Repl link pls

**Comment by isaacHagoel** [comment]
:global(#dnd-action-dragged-el) {
    background-color: #aa0000 !important;
}

**Comment by KevsRepos** [comment]
Thank you. But why does it only work with the `!important` flag? Features like that should not rely on it.

**Comment by isaacHagoel** [comment]
it is not a feature per se. It is more of a backdoor.
The feature is automatically copying styles so that the dragged element
looks like it would when dropped.
The important overrides it

**Comment by KevsRepos** [comment]
I think this lib should have more/easier options to inject styles and classes and should not be opinionated about styling at all. The lib should not force devs to user bad-practice backdoors to give  elements a proper styling.

**Comment by isaacHagoel** [comment]
Thanks for sharing your opinions with me

**Comment by isaacHagoel** [comment]
Btw, you have the morphDisabled option. Not sure you've seen
