### ISSUE TITLE
ESLint warning `'HTMLAttributes' is defined but never used.`

### ISSUE THREAD

**Issue by probablykasper** [isaacHagoel/svelte-dnd-action#373]
When I add this to my `global.d.ts`:
```ts
declare type DndEvent = import('svelte-dnd-action').DndEvent;
declare namespace svelte.JSX {
	interface HTMLAttributes<T> {
		onconsider?: (event: CustomEvent<DndEvent> & { target: EventTarget & T }) => void;
		onfinalize?: (event: CustomEvent<DndEvent> & { target: EventTarget & T }) => void;
	}
}
```

I get the following warning:
> 'HTMLAttributes' is defined but never used. eslint[@typescript-eslint/no-unused-vars](https://typescript-eslint.io/rules/no-unused-vars)

## To reproduce

1. `npm init svelte my-app` (Select "Skeleton project" and enable TypeScript, ESLint and Prettier)
2. Add the typings to `src/app.d.ts`
3. `npx eslint src`

**Comment by isaacHagoel** [comment]
If you are using the events and eslint still complains there isn't much the
lib can do about it. I suggest suppressing this warning

**Comment by probablykasper** [comment]
Fair enough, will just suppress it then.

In case anyone else finds this:
```
declare type DndEvent = import('svelte-dnd-action').DndEvent
declare namespace svelte.JSX {
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  interface HTMLAttributes<T> {
    onconsider?: (event: CustomEvent<DndEvent> & { target: EventTarget & T }) => void
    onfinalize?: (event: CustomEvent<DndEvent> & { target: EventTarget & T }) => void
  }
}

```
