### ISSUE TITLE
get dragOver item  details inside on:consider & on:finalize

### ISSUE THREAD

**Issue by ivanjeremic** [isaacHagoel/svelte-dnd-action#376]
We need details (all properties) like `id` and the rest of the item properties we are currently dragging over,

I currently don't see any way to do this, correct me if I'm wrong. Getting the whole Array back is not very helpful.

I have a REPL where I describe what I want in the handler with a simple comment.
[https://svelte.dev/repl/87f8f6076a12491ba783ac99101b8ba2?version=3.24.1](https://svelte.dev/repl/87f8f6076a12491ba783ac99101b8ba2?version=3.24.1)

**Comment by isaacHagoel** [comment]
Hi,
Have you tried getting the `id` and `items` and find the index of the id in the array?

**Comment by ivanjeremic** [comment]
@isaacHagoel I know that the item is somewhere in the Array but there are use-cases where this does not work, I will explain it to you why for example `react-dnd` you can read things like this.

There are use-cases where you don't know beforehand which id you are over and you also should NOT know but instead the dragged item should know it.

Imagine you are building a OS Desktop UI with files and folders and when dragging a file in a folder It should get Folder id, I know at this point you think but the folder should be a new `dndzone` but no! It should not be a new `dndzone`  I don't want to actually drop it in the folder with `svelte-dnd-action`, I want just to do some logic not related to `svelte-dnd-action`.

```js
function handleDndFinalize(e) {
    items = e.detail.items;
    apiService.move(draggedID, folderID); // the item I'm entering with the dragged element
}
```
If you now think again but Folders should be a `dndzone` NO they can not, because the Array I get back is from a Software I cannot modify and in this Array (Apps & Folder) are on the same level and even if I could modify the Array remember I can not know the ID but instead the dragged element needs to know it.

```js
const desktop = [
  {
    id: "fromSoftware-4568552",
    title: "I'm App 1",
    kind: "App"
  },
  {
    id: "fromSoftware-8774485",
    title: "I'm App 1",
    kind: "App"
  },
 {
    id: "fromSoftware-2121214",
    title: "I'm App 1",
    kind: "Folder" // <------ FOLDER ON SAME LEVEL
  },
]
```

I really hope I was able to demonstrate to you that there are legit use-cases where you need information like this, this is also the reason events like the core `ondragenter` or how it's called where invented it says: Well `ondragenter` "DO" something you want but it does not say `ondragenter` YOU NEED TO DO SOMETHING DROP RELATED you could for example also just print it out somewhere in the app like `ondragenter`  
```
{#each items as item (item.id)}
  {#if item.kind === "App"}
   <div
     on:dragenter={() => `alert("just entered App with id: ",  item.id)`}
   >I'm an App</div>
  {:else}
    <div
      on:dragenter={() => `alert("just entered Folder with id: ",  item.id)`}
    >I'm an Folder</div>
  {/if}
{/each}
```

If there is any way to get the properties in that way please tell, me otherwise I'm open to help too if you could show me where exactly in the lib it could be exposed I'm willing to expose it and contribute. 

Thanks

**Comment by isaacHagoel** [comment]
So to make sure i get it right, you want to know when an item is over
something that cannot move and shouldn't be displaced by the item over it.
Correct?
Or just when an item was dropped over something that cannot move?
Or something else?

**Comment by ivanjeremic** [comment]
Ok let's start by an easy example I just created on the REPL, Here you can see what I want, [https://svelte.dev/repl/b2de261c34cb4aedb99e3d88e0fe5bcc?version=3.24.1](https://svelte.dev/repl/b2de261c34cb4aedb99e3d88e0fe5bcc?version=3.24.1)

Try to solve this, you will see the fact that the whole array is here doesn't help me.

**Comment by isaacHagoel** [comment]
like this?
https://svelte.dev/repl/1b897023173246609910c1e2f856baff?version=3.24.1

**Comment by ivanjeremic** [comment]
Almost, it is triggering when it is on the new index but is it also possible to trigger when I'm over another item?

**Comment by isaacHagoel** [comment]
The lib doesn't distinguish between the two. When the center of the dragged item is over another item the event will fire.

If you want the item below to not move then simply assign 
`items = items` instead of `items = e.detail.items` (and the code i provided will need to change a bit but can still work).

**Comment by ivanjeremic** [comment]
In my case (The Desktop Example) I would need everything to move when rearranging them but somehow also not when I want to drop something into a folder, it is really hard to do it without fine grained events on certain elements, for example I could  place a tiny square div in the middle of my folder component which has an `dragenter` which fires only the drop if I want and moving more out would rearrange them. It almost feels too abstracted away which does not allow fine grained Control.

I need to test it out in my project and see what I can do and come back again with feedback on this.

**Comment by isaacHagoel** [comment]
So you mean something like the desktop on Android?
From playing around with it, it seems like the trigger for items to move is when the dragged item is placed in the space between them rather than over them.

**Comment by ivanjeremic** [comment]
Yes correct like mobile operating systems, I played with it too and it is correct it is triggered in between but when on both folders and apps the difference is folder allow me to stay directly over them without triggering and moving in between rearranges if I decided not to drop.

**Comment by isaacHagoel** [comment]
I don't think this lib is best suited for that.
It aims at a different use case.
If I were you I would probably fork it and modify heavily or create a custom dnd implementation from scratch.

**Comment by ivanjeremic** [comment]
It sounds more complicated than it really is this library is pretty close to it, the library only needs to expose 2-3 more things to have a much more use cases. But if you say this is something that doesn't belong in this dnd library you can close this issue. 

Thanks for your help.

**Comment by isaacHagoel** [comment]
What 2-3 more things do you need?

**Comment by ivanjeremic** [comment]
First is let us by attaching id's or custom actions decide which elements are triggers of rearrangement or whatever is best.

Second be able to use `on:consider` and `on:finalize` in an `each` block for the same `dndzone` too.

```js
<div
  class="grid-cols-wappgrid grid gap-4"
   use:dndzone={{items,flipDurationMs}}
   on:consider={handleDndConsider}
   on:finalize={handleDndFinalize}
>
  {#each items as item (item.id)}
    <div
     on:consider={otherHandler}
     on:finalize={otherHandlerFinalize}
    >Item</div>
  {/each}
</div>
```

**Comment by isaacHagoel** [comment]
these go against the design of the lib but even if u had them how would that help you build the desktop interface?

**Comment by ivanjeremic** [comment]
> these go against the design of the lib but even if u had them how would that help you build the desktop interface?

Well like I said in the world of building Apps which have dnd there a so many edge cases where I think flexibility is important when the App is complex. 

In the case of my App I need to fire events like `ondragenter` on deep nested elements in the loop for the same `dndzone` and also outside on other elements, for example I have a Swiper where each page holds Apps like a mobileOS I have left and right on each page a small 3rem div with full height, I want to attache on that div something like a `ondragenter` event like I was able in plain HTML or plain JSX which lets the pages be Swiped when entered with a dragged elements.
