### ISSUE TITLE
How to track the mouse position when dragging

### ISSUE THREAD

**Issue by zwz** [isaacHagoel/svelte-dnd-action#377]
I want to track the mouse position so as to draw a line from the original position to the current position when dragging.
I tried `transformDraggedElement` and add `mousemove` event listener onto the dragged element.
It almost works, except that `transformDraggedElement` is not called when I drag the element fast enough to non-dnd-zone.

I wonder if there is a better way to track the dragging position.

**Comment by isaacHagoel** [comment]
Have you tried using the trigger in the consider event?
When drag starts (and source is pointer) you can attach the mouseMove
listener.
The id in the event can tell you where to start the line from (an item in
your list right?)

**Comment by zwz** [comment]
@isaacHagoel 
I tried using the trigger in the consider event
```
function handleConsider(e) {
   ...
   console.log(document.getElementById(e.detail.info.id))
   document.getElementById(e.detail.info.id).addEventListener('mousemove', mousemove)
   ...
}
```
I found `mousemove` is not called.
I also found the element in `consider` event is not the same element in `transformDraggedElement` event, where the id is "dnd-action-dragged-el".

The issue is not where to start the line from, but where to end the line to, when dragging.
