### ISSUE TITLE
Making a section draggable, changes its CSS

### ISSUE THREAD

**Issue by skandabhairava** [isaacHagoel/svelte-dnd-action#378]
![image](https://user-images.githubusercontent.com/58636952/172154041-2a8fc3a7-35cb-4eb0-a9c7-0f7a93de1774.png)

I have a 2D matrix representing this grid. Each letter container gets placed in a row, and the row gets placed in columns.
When I wrap the `each` loop which places the letter containers with dndzone... 
```js
    <section use:dndzone={{items: row_list, flipDurationMs: flipDurationMs}} on:finalize={handleSort}>
        {#each row_list as letter, i (letter.id)}
            <!-- <div animate:flip={{duration:flipDurationMs}}> -->
                {#if (i === 1 || i === 3) && (col === 1 || col === 3)}
                    <BlockLetter/>
                {:else}
                    <Letter letter={letter}/>
                {/if}
            <!-- </div> -->
        {/each}
    </section>
```
The grid's disappears, and all im left with is a column. How do I fix this??
I dont have muuuch experience with Css
![image](https://user-images.githubusercontent.com/58636952/172154454-e6ddfff5-3565-4afd-aa33-164c24ede614.png)

Thanks in Advance!

**Comment by isaacHagoel** [comment]
Can you please make a REPL that reproduces the issue so i can have a look?
