### ISSUE TITLE
Disable drag for selected element

### ISSUE THREAD

**Issue by farhan-syah** [isaacHagoel/svelte-dnd-action#384]
I want to implement something like this: All the items are draggable besides a certain element (in this case my last element). I have made it worked by filtering the items using the handler functions. That worked fine. However, the element still can be dragged, and I couldn't find a way to properly disable it. 

Is there any may to make it possible in the future? Perhaps, by checking if the child element has disabled='true' status, we simply create a normal element instead of draggable element.

![image](https://user-images.githubusercontent.com/45132618/175809862-f63e8cb9-a74a-4d35-af19-d961c66b67f9.png)

**Comment by isaacHagoel** [comment]
Ideally you would make that part of the background or not a child of the
dndzone (can be a sibling)
not sure what it would mean to disable a specific item. what should happen
when i drag another item over it?

**Comment by farhan-syah** [comment]
Yes, separating the item like that will work if it is a simple horizontal or vertical layout. 

[Item 1 - Item 5] - draggable, all this behave as usual
[Item 6 ] - not draggable - mean, it couldn't be dragged

Right now, everything worked, except, user can still drag the items around (although nothing will happen, even if they did drag the Item 6)

![image](https://user-images.githubusercontent.com/45132618/175810506-80e1aa58-ebab-4466-8abb-0e3ac1cb891a.png)

**Comment by farhan-syah** [comment]
Never mind, I have tried making it work by making it as a sibling as you suggested, only this time, I removed the animate:flip.  The previous issue I get is when I keep the animation.

`An element that uses the animate directive must be the immediate child of a keyed each blocksvelte(invalid-animation)`

**Comment by null-dev** [comment]
For anybody trying to do this, you can attach a `mousedown + touchstart` handler on the item you don't want to drag and call `event.stopImmediatePropagation()`.

Note that as Isaac mentioned, the item can still be moved by dragging other items on top of it.

**Comment by isaacHagoel** [comment]
@charisra this is currently being discussed in #544
