### ISSUE TITLE
Changing data's `id` is messing with my code

### ISSUE THREAD

**Issue by whatwhywhenandwho** [isaacHagoel/svelte-dnd-action#385]
The library is changing data's `id`, which is messing with my code that's relying on it. It would be super awesome if this:

    export let ITEM_ID_KEY = "id";

wouldn't be hardcoded, but configurable. It's fine(ish) if a default is `id` (however, something like `svelteDndActionId` would most likely make it nuclear level safe), but please let us decide on this.

Otherwise, amazing work.

**Comment by isaacHagoel** [comment]
See [here](https://github.com/isaacHagoel/svelte-dnd-action#overriding-the-item-id-key-name)

**Comment by whatwhywhenandwho** [comment]
How did I miss that 🙄
Sweet, worked.
Thank you.
