### ISSUE TITLE
Exclude particular div from being dragged

### ISSUE THREAD

**Issue by thousandsofraccoons** [isaacHagoel/svelte-dnd-action#386]
Hello, as always, thank you for the library. I have a question - can I exclude a specific div from being dragged? So I've got a column where all divs are draggable and one div is located outside of the loop and it is kinda button. If I attempt to drag it - everything gets broken of course, so I'd like to override it.

Thank you

**Comment by thousandsofraccoons** [comment]
What I trying to achieve is add item button in the column.
![image](https://user-images.githubusercontent.com/33694447/178094338-72a432df-9895-4f3b-9355-dfcbc13ea6c6.png)

**Comment by isaacHagoel** [comment]
Do it like the column title just below

**Comment by PlopTheReal** [comment]
That would be nice to have it within the dnd zone. The reason is that within such example, having a none draggable item in the draggable list let some space so it's easier to drop items into an 'empty' column. 
I'm looking into it but so far I'm forced to set the dnd zone entirely none draggable when user interacts with that "non draggable" slot. I guess other use cases could benefit of some "non draggable" items within the dnd zone.

**Comment by benbro** [comment]
I'm trying to exclude an item from both being dragged and being reordered. I can prevent it from being dragged by using drag-handler on all other items but it still can be reordered.
I can revert a change in handleFinalize but when trying to modify a change in handleConsider it breaks the logic of the action. Is there a way to modify items inside handleConsider or another way to exclude an item from drag-and-drop?

**Comment by isaacHagoel** [comment]
Have you tried setting dragDisabled:true (on the entire zone) when the user
mouseDowns on this item?
(I hope I understand the question correctly)

**Comment by benbro** [comment]
I'm using drag-handles and made this item not drag-able. 
I also want the user to not be able to drop on this item. If I have items=['a', 'b', 'c'] I want item 'a' to always be first in the list.
As an example, in google forms you can reorder questions but you can't put a question before the form title.
As a workaround I check if item 'a' is first in handleFinalize and reorder if not. It will be much nicer if the user can't drop on item 'a' in the first place.
I can move the first item before the dragzone div but that will complicate the rest of the app code.

**Comment by isaacHagoel** [comment]
Wait so why not do the same in the consider handler? Set items to a list in
which a is always first even if the lib tells you it shouldn't be

**Comment by isaacHagoel** [comment]
Cool
