### ISSUE TITLE
Drag item to stack on top of another item

### ISSUE THREAD

**Issue by rajaiswal** [isaacHagoel/svelte-dnd-action#390]
Hi @isaacHagoel! Thanks for creating this awesome library! I have been experimenting with it for my use case and ran into some limitations that I'm wondering you could point me in the right direction:

1. Is there a way I can drag an item on top of another item and one of them disappears when I release the drag? This would ideally happen when the dragged object is exactly over another object and the flipping animation has not triggered yet. My goal is to create a merging effect where one can merge one item with another by dragging over it.
2. Is there a way to get the `id` of the item that is under the item being dragged? And also get the `id` of the item that just underwent a flip animation when being dragged over by another item?

Thanks!

**Comment by isaacHagoel** [comment]
1. Maybe you could make each item itself also a dnd zone and when one item is dropped into another u can implement the merge logic. there are some examples for nested zones linked in the readme
2. By default the lib would try to assign new indexes to items under the dragged item. it does have some internal events that in theory you can listen on but maybe my answer to 1 would prevent you from needing this
