### ISSUE TITLE
Transition the dragged element

### ISSUE THREAD

**Issue by victormihalache** [isaacHagoel/svelte-dnd-action#391]
I'm looking at the [Styling the dragged element](https://svelte.dev/repl/3d8be94b2bbd407c8a706d5054c8df6a?version=3.22.2) example and I'm wondering if there's a way to make it so the change between the "non-tilted" and the "tilted" state has a transition, is there a way?

**Comment by isaacHagoel** [comment]
sorry for the long delay. i missed this issue somehow. not sure if it is still relevant. you can do anything that normal JS can do. what kind of transition did u have in mind?

**Comment by isaacHagoel** [comment]
Yes. You can do it with css only. Add a transition on the transform and set
the initial rotate to 0 in your normal css that targets the item. Set a
global css rule that targets the dragged eleenent by its id and set the
rotate to whatever you want.
