### ISSUE TITLE
Cannot read properties of undefined (reading 'style')

### ISSUE THREAD

**Issue by webdagger** [isaacHagoel/svelte-dnd-action#393]
Hello,
When dropping from another zone I get this error.

```
function unDecorateShadowElement(shadowEl) {
  shadowEl.style.visibility = "";
  shadowEl.removeAttribute(SHADOW_ELEMENT_ATTRIBUTE_NAME);
}
```
But I am not attempting to do any styling with `SHADOW_ITEM_MARKER_PROPERTY_NAME` and this error is bizarre because it sometimes works and other times it does not work. 
Sorry, I don't have a repl, just need some ideas on what you may think I am doing wrong.

**Comment by isaacHagoel** [comment]
what is the actual error message you are getting (what is the failure in the code you pasted above)?
are you using any out transitions like fade-out?

**Comment by webdagger** [comment]
![Screenshot from 2022-08-02 18-01-22](https://user-images.githubusercontent.com/5221791/182544029-65a3f6f1-cebc-4164-9526-c84c84d5fe1e.png)

Cannot read properties of undefined (reading 'style') 
No, not using any transitions.

**Comment by isaacHagoel** [comment]
I'll need a repl or code example
