### ISSUE TITLE
How to use with a Svelte writable store

### ISSUE THREAD

**Issue by 3daddict** [isaacHagoel/svelte-dnd-action#396]
I have been trying to figure out how to properly use this with a Svelte writable store and I could not find any examples in the readme.
Here is the example I am trying to get working: https://svelte.dev/repl/bcc5885c6e91480188fefe524bca49d3?version=3.49.0
Is anyone able to guide me in what I am doing wrong?

![image](https://user-images.githubusercontent.com/29803478/184799293-0e95c6bd-6a82-490e-8145-841df11520b1.png)

**Comment by isaacHagoel** [comment]
[fixed version](https://svelte.dev/repl/59b6f80f861b47448650e78452703a6c?version=3.49.0)
1. u didn't return "set" from the store 
2. you called $gradeReport.set instead of just gradeReport.set in the handler

**Comment by 3daddict** [comment]
Thanks @isaacHagoel,
Yes, that solved the issue I was having. Thanks for the help!
