### ISSUE TITLE
border disappears when dragging...

### ISSUE THREAD

**Issue by rchrdnsh** [isaacHagoel/svelte-dnd-action#398]
I have a REPL:

https://svelte.dev/repl/0fe28dc7e0ee49aba49a8606f5f1b033?version=3.49.0

Where each block of text is a draggable element. The border for each element only shows up when you hover or click into it. When a person starts dragging, however, the border disappears. I would expect the border to stay visible to help a user drag and drop the element correctly...

Maybe the component needs to be able to handle this kind of situation, or maybe there is some css I can add to make the border visible when dragging, like a pseudo class that I am unaware of?

Anyway, thank you :-)

**Comment by isaacHagoel** [comment]
I didn't review the REPL in details but [this](https://github.com/isaacHagoel/svelte-dnd-action/blob/d76d8fa8dbc63d062420fd32b55cc7463ebfba1f/src/helpers/styler.js#L95) is how the properties get copied. What are you using for the border?

**Comment by rchrdnsh** [comment]
hmmm...I see...I initially set the border color to white or 0 opacity, etc...then on hover and active and or focus states it is visible...I would like to maintain those style choices while being able to style the border of the element while it's being dragged...it seems that it inherits the initial border when dragging, not the border when hovering or active, etc...

it would be super awesome to be able to set the border while dragging by itself...maybe a custom prop that is exposed or a style object or something like that...for example, what if i want the element to have a blue border, but only when dragging it...would something like that be possible?

**Comment by rchrdnsh** [comment]
I see there are `droppedTargetStyle` and `droppedTargetsClasses` ? Maybe adding a prop for the item that is being dragged as well?

Maybe something like `draggedItemStyle` and/or `draggedItemClasses` or `draggingItemStyle` maybe? And the item will inherit the base class styles by default but any styles added to this prop would override the defaults that were copied?

**Comment by rchrdnsh** [comment]
found a workaround in another issue, did this and it worked:
```
:global(#dnd-action-dragged-el) {
    background-color: #aa0000 !important;
}
```
...but this feels...i dunno...would much prefer a style object as a first class citizen...in my case, keeping the border visible, but also adding a box shadow, but only when dragging.

I'll close it out for now, but that would be lovely to have a `draggedItemStyle` or something similar :-)

**Comment by isaacHagoel** [comment]
I agree that it could be a nice to have feature. I am open to PRs, not sure if I will have time to add it myself in the near future
