### ISSUE TITLE
possible to drag an element from outside any dnd zone into one?

### ISSUE THREAD

**Issue by rchrdnsh** [isaacHagoel/svelte-dnd-action#399]
I'm trying to make a ui where the user can drag and drop a content block into the editor, which is the dnd zone. I don't want the thing that is being dragged to be in a draggable zone, however, as I want a copy of the element to be created as the user starts to drag from it, but I don't the user to be able to drag that element around in its parent container.

Not sure if I explained that too well, but if you are getting what I'm saying would something like that be possible? Can I make any element on the page be draggable if it is not in a dnd container?

**Comment by rchrdnsh** [comment]
Here is an example I found, where the items that CAN be dragged in the dnd zone are not themselves in a dnd zone...my use case would not be putting into the trash, but making a new content block with the selected item.

https://react-dnd.github.io/react-dnd/examples/dustbin/single-target

**Comment by isaacHagoel** [comment]
you can achieve this.
make the area with the items a dndzone but set dropFromOthersDisabled=true and in your consider and finalize handlers set items to itself (ignore the content of e.detail.items) that way the order of the items will never change

**Comment by rchrdnsh** [comment]
k, so I tried all of that...i think...not sure if correct, but it's still not behaving the way that I would want it to...

The dragged items disappear from the place they were dragged from, rather than staying there...I think what I want is maybe for a copy of the thing to be made?

To test it for yourself drag the H1 from the top row of buttons in the main content area...it will create a new h1 element, but the H1 spawn? button is now gone...i would want to be able to drag 100 H1's from that button into content area if so desired...not sure how that might be achieved...

it IS true that I cannot drag to re-order in the top horizontal button bar at the moment, which is good :-)

Here is the REPL as it stands:

https://svelte.dev/repl/3351929dcd9b411f800e9ea05620b848?version=3.49.0

Thanks! XD

**Comment by isaacHagoel** [comment]
have you seen the dragula-copy-on-drag example?
the bottom list here
https://svelte.dev/repl/924b4cc920524065a637fa910fe10193?version=3.24.1

**Comment by rchrdnsh** [comment]
hmmmm...it rings a bell...i might have see nit and thought it was not doing quite what I was looking for? can't remember...

anyway, thanks for reminding me...

The dragula example's code is a bit beyond me on first glance, but I will go through it and if I get stuck will ask again,

thanks

**Comment by rchrdnsh** [comment]
ok, so I tried to essentially copy and paste the dragula version (bottom one) from the example you linked to and there are no errors, but it's still not working properly and the HTML nodes on the top bar are still not being copied, but being dragged into the main area...I admittedly don't fully understand the code, so I don't know what might be going wrong here.

In the REPL the JS I copied starts on line 6 and the html starts on line 228...

https://svelte.dev/repl/3351929dcd9b411f800e9ea05620b848?version=3.49.0

As an aside I am not super great at JS or programming in general, and I am self taught, so I could be missing something simple.

**Comment by isaacHagoel** [comment]
i will try to block some time and make a working example for you. how
urgent is this?

**Comment by rchrdnsh** [comment]
not urgent, just working through an idea for a project in the near future ...a svelte CMS!  XD

but yeah, if you're busy, no hurry :-)

**Comment by isaacHagoel** [comment]
I gave it a quick look.
you placed the dragula code to the main file, correct?
in this file the only dnd zone iterates over `nodes` yet the handlers
assign (and search in) `items`.
All this handler does is the first time around (drag start) it creates a
copy of the item being dragged and adds it to the list in the original
index (so that it doesn't gets removed) and remove the placeholder item
from the list (so there is no empty space when the item leaves).
In every subsequent drag event it ignores what the lib tells it about what
the order of the items should be.

**Comment by rchrdnsh** [comment]
yes, the dragula code is in the `App.svelte` file.

the only dropzone conceptually should be the zone that iterates over the `nodes`, as this is the "document editor window", where the nodes can be actually changed.

the items in the top row of the ui are the buttons that will make NEW nodes for the document, but the top row is not supposed to be a dropzone itself, as that would not make sense foe the structure and usage of the ui.

so, the `nodes` array is the actually document itself, which is different than the html prototype buttons, which are not the same concept, and would not be named the same thing conceptually. Those are what are called `items` in this context, although they were called `html` until the dragula code told me it wanted this group to be named `items`, which I would not actually choose as the name if given the choice. I hope that makes sense.

To try and illustrate the concepts a bit better, here is a video of the webflow ui, in which the user picks a new element to add to the web page and drags and drops that element into the web page...the list of available elements in the left panel is not a dropzone, only the web page itself is...this is the kind of mental model that i am working from:

https://user-images.githubusercontent.com/7884263/187256430-a95e5d6f-51c2-4099-8383-9434abfcd211.mp4

for my version the element bars on the top and left of the screen are supposed to be the same idea as the webflow example, and the main document area is the only "dropzone" in my mind...

I would have imagined there would be a way to designate the element buttons in the element bars as `draggable="true"` and then the only dropzone would be the "document editor window" itself, but I gather that is not the case with this library?

Still wrapping my head around it

**Comment by rchrdnsh** [comment]
I'm also trying to learn the Drag and Drop API as well, so I made this so far to illustrate the idea a bit better...

The boxes in the top row are outside the dropzone, and when I drop one in it copies the element and it's children into the dropzone...still drag and drop to sort inside the dropzone yet, or any animations, etc... but this is the general idea I have in my head, if it helps...

https://svelte.dev/repl/2376bb89b0ea4a5084955ee4fe8a62a7?version=3.49.0

**Comment by isaacHagoel** [comment]
as i said. I will try to find some time in the next day or two to make a
simple working example for you.

**Comment by isaacHagoel** [comment]
see [here](https://svelte.dev/repl/35686b7dd8424f329fb01a8880fb7a25?version=3.49.0)

**Comment by rchrdnsh** [comment]
huzzah!

so, a couple things...

I did not add the key to the `[#each}` block, which is something about svelte i did not really understand
The other thing I did was treat `dropFromOthersDisabled: true` as a prop of the component rather than an key value pair of the `dndzone` action, which I also did not understand very well.

but, regardless, it works now!

Thank you very much Isaac for your help XD

https://svelte.dev/repl/3351929dcd9b411f800e9ea05620b848?version=3.49.0

**Comment by rchrdnsh** [comment]
oooh...one more question, if you don't mind :-)

Trying to make these function into more generic, reusable ones but it does not seem to work quite yet...

```js
  function handleConsider(event, things) {
    const {trigger, id} = event.detail.info;
    if (trigger === TRIGGERS.DRAG_STARTED) {
      const idx = things.findIndex(item => item.id === id);
      const prefix = id.split(':')[0] + ":";
      const newId = makeId(prefix);
      event.detail.items = event.detail.items.filter(item => !item[SHADOW_ITEM_MARKER_PROPERTY_NAME]);
      event.detail.items.splice(idx, 0, {...things[idx], id: newId});
      things = event.detail.items;
     } else {
        things = [...things];
    }
}
	
function handleFinalize(event, things) {
  things = [...things];
}
```

...then I use them as such:

```html
<div
  use:dndzone={{
    items: html,
    flipDurationMs,
    dropFromOthersDisabled: true,
    centreDraggedOnCursor: true,
    dropTargetStyle: {outline: 'none'}
  }}
  on:consider={(event) => handleConsider(event, html)}
  on:finalize={(event) => handleFinalize(event, html)}
>
```

...but it's not working properly when I do it this way. If I simply copy the functions and switch out the array of objects in the function itself then it works...wondering what I need to change to make this a thing...

Thanks XD

**Comment by isaacHagoel** [comment]
that's because the Svelte compiler is not smart enough to trigger reactivity when you do the assignment in such a way.
worth trying passing a setter as a third param and calling that from within handleConsider rather than assigning directly. `on:consider={e => handleConsider(e, things, newThings => {things = [...newThings]}}`
haven't tried but it could work.
