### ISSUE TITLE
Dragged element shifts to the sides while being dragged across nested zones

### ISSUE THREAD

**Issue by aldanasjuan** [isaacHagoel/svelte-dnd-action#400]
Hi Isaac,

I've been testing the library for a relatively basic use case. Just dragging items from one zone to multiple 1-item-zones (similar to the scrabble example). 

The issue I found was that when the zones are in an indented or nested container, the item being dragged shifts to the left or right. Sometimes it snaps briefly to it's original position. I also noticed the shifting issue on your 'crazy nesting example'.  I'll post some videos that will hopefully explain it better than me.

Here's a video of the nesting example: https://youtu.be/t0luA6p-HHM

And here's a video of my own example: https://youtu.be/abSGpZH1QsM

As you can see on my video, if the zones are all aligned vertically, the drag item doesn't shift anymore (at the end of the video). 

**More Debug info**

I added some logs to your pointerAction.js, specifically on the handleMouseMove function, to see if the values you were assigning to the transform3D where somehow changing but nothing, the cursor X and Y are all the same and the dragStart values look the same but the rect somehow changes on the X axis. You can see on the logs that those  values don't really change. 

Here's a video of those logs: https://youtu.be/GRcfJiM_nMo

I see that the issue happens when you run either handleDraggedEntered or handleDraggedLeft functions, so I logged the element's parent on those functions and on handleMouseMove and noticed that the parent is different in each of those function calls, which may be normal if the event gets dispatched by different elements, I'm sure you know best  (you can see it at the end of the video, there are different parents on each call).
So my guess (I hope I didn't waste your time with all of this) is that the transform takes the parent's coordinates into account, therefore change the left/x property on the bounding rect, resulting in the shift. I don't know your code that well so I'm hoping there's a way to check if this is the case and to account for the parent's x coordinate (or y as well, I haven't had an issue there).

Thanks for the time you've put into the library, I do appreciate it a lot. I'd glad to help out more but I'd like to hear your thoughts first.

**Comment by isaacHagoel** [comment]
so with the crazy nesting example it looks like the size of the element changes which is the expected behaviour. It would morph to match how it is going to look like when dropped.
The way it works is that the lib puts a "shadow element" in the target zone (which is then hidden so it looks like an empty space) and then it copies styles from that shadow element to the dragged element. you can see the code for it [here](https://github.com/isaacHagoel/svelte-dnd-action/blob/d76d8fa8dbc63d062420fd32b55cc7463ebfba1f/src/helpers/styler.js#L70)
