### ISSUE TITLE
Item being dragged doesn't get updated if it uses index of each

### ISSUE THREAD

**Issue by uyha** [isaacHagoel/svelte-dnd-action#402]
REPL: https://svelte.dev/repl/9520cedfd83344b6bdf3bc6b11c51469?version=3.23.2

I want to use index of `#each` in my component, but I notice that if the item being dragged uses that index, it won't be updated until the drag is finalized. Is there a way to make the component update when is it being dragged also?

**Comment by isaacHagoel** [comment]
Have you tried the `transformDraggedElement` option?

**Comment by uyha** [comment]
I have tried after you mentioned it but could not figure how to use it in this case. It feels like I can make it work by updating the DOM directly but doesn't that defeat the purpose of Svelte being reactive? Also, if I have a component which uses the index but have a deeply nested structure, manipulating the DOM is also a pain.

**Comment by isaacHagoel** [comment]
doesn't this example do what you are after?
https://svelte.dev/repl/438fca28bb1f4eb1b34eff9dc6a728dc?version=3.50.1
regarding reactivity - this lib (and any other Svelte action) is vanilla JS, it is not Svelte. Svelte simply provides a nice integration mechanism. Once dragging starts the dragged element is not in the Svelte-verse.

**Comment by uyha** [comment]
Yes, kind of, but the problem is instead of plain HTML, I need to update the information inside a component, this component has its own layout. Like I mention above, just changing the HTML by navigating the DOM element is possible but is a pain. 
Thank you for explaining the nature of this library, I was not aware not that.
