### ISSUE TITLE
Transform element dragged from another dnd zone

### ISSUE THREAD

**Issue by madeleineostoja** [isaacHagoel/svelte-dnd-action#403]
I'm trying to find a solution to transforming a dragged element once it enters another dnd zone of the same `type`, is that something the current API of `svelte-dnd-action` can address? Because I can't figure it out. `transformDraggedElement` seems to only be called from the originating dnd zone and can't differentiate when the element enters another dnd zone (can it?).

To further explain the use-case for this, I have: 
1. A grid of photos which is a dnd zone (to rearrange items)
2. A list of galleries which is a dnd zone (to rearrange items)
3. Individual galleries in the list of galleries are **also** a dnd zone with the same `type` as the grid of photos, so I can drop photos into the gallery list to move them to that gallery

What I want:
- To transform a photo when it is dragged over a gallery item, to show it can be moved/dropped there.

Video demonstrating what I mean:

https://user-images.githubusercontent.com/6374876/193975018-159e581e-968b-4b15-9af6-00585a0623e2.mov

**Comment by isaacHagoel** [comment]
In theory it should work. Can you pls create a REPL that reproduces the
issue?

**Comment by madeleineostoja** [comment]
Sure thing, started working on a repl but I'm getting an error I'm not seeing in my dev environment, I'll debug it when I get a mo unless you know what I'm doing wrong offhand

https://svelte.dev/repl/2b0ac0549af5432a9cfc2bbac3dc3b53?version=3.50.1

**Comment by madeleineostoja** [comment]
Okay I think I've figured it out, this is another face of #374. Since the item I'm dragging into doesn't have/display children, it doesn't morph when dropping (and I've disabled morph because of that), so `transformDraggedElement` is never called because it's only called if morph isn't disabled ([here](https://github.com/isaacHagoel/svelte-dnd-action/blob/2cb159806449d3007c9fe7fb84538c3d0bfc4127/src/helpers/styler.js#L88) and [here](https://github.com/isaacHagoel/svelte-dnd-action/blob/2cb159806449d3007c9fe7fb84538c3d0bfc4127/src/pointerAction.js#L517))

**Comment by isaacHagoel** [comment]
The REPL doesn't give me an error message, how do you make it error out?

**Comment by madeleineostoja** [comment]
Drag an image into a gallery list item

![Screen Shot 2022-10-12 at 10 33 46 AM](https://user-images.githubusercontent.com/6374876/195202650-4f87e1a9-530a-4a52-9555-49884947cd89.png)

**Comment by isaacHagoel** [comment]
I will always ask for a REPL :)

**Comment by madeleineostoja** [comment]
It's the same repl? https://svelte.dev/repl/2b0ac0549af5432a9cfc2bbac3dc3b53?version=3.50.1

**Comment by isaacHagoel** [comment]
the first thing that pops is that the internal zone is missing a consider
handler

**Comment by madeleineostoja** [comment]
Hmm I'm not sure what to make a consider handler do in this case, since I'm not visually rearranging any elements in the internal zone or anything. It's just acting as a simple drop target to change a prop on the dropped item.

**Comment by isaacHagoel** [comment]
from the README under rules:
> The host component must refresh the items that are passed in to the
custom-action when receiving consider and finalize events (do not omit any
handler).

**Comment by madeleineostoja** [comment]
Is there any way you can think of to achieve what I’m trying to do (in that first video) with svelte-dnd-action?

**Comment by isaacHagoel** [comment]
So you want the image to morph when it is dragged to the list?

**Comment by madeleineostoja** [comment]
Yup

**Comment by isaacHagoel** [comment]
I'll try to find time during the weekend to make a repl

**Comment by isaacHagoel** [comment]
something like this?
https://svelte.dev/repl/bd7d52de937f4f64b260575d0c74a2a1?version=3.51.0

**Comment by madeleineostoja** [comment]
Hmm that repl is just adding the images to the list, in the video (and my app) each item in the list is its own dropzone, and dropping an image into it removes it from the gallery, acting like a “bucket” it goes into.

Is there a reason that ‘transformDraggedElement‘ isn’t called if ‘morphDisabled‘ is true? I _think_ changing that behaviour would fix a big part of this issue, as per https://github.com/isaacHagoel/svelte-dnd-action/issues/403#issuecomment-1272274177 and https://github.com/isaacHagoel/svelte-dnd-action/issues/374

**Comment by isaacHagoel** [comment]
I created a simplified example. How would it matter if there are nested
zones?
Transform is conceptually part of morphing, why should it be called
regardless?

**Comment by isaacHagoel** [comment]
After sleeping on it i think that it might make sense to call transform even when morph is disabled. Can you please explain again why you needed to disable morph but still want to call transform?

**Comment by madeleineostoja** [comment]
For two reasons:

a) The primary dropzone (gallery of images) needs morph disabled for UX reasons, automatic morphing results in a janky user experience as the dragged element resizes while getting dragged around a masonry style grid (I'm using a custom shadow element to show the resulting placement instead, which is much cleaner in my app)

b) The secondary dropzone (gallery list item) doesn't have anything to automatically morph to, its items are effectively hidden and it just acts as a bucket that can swallow up images from the gallery. I'd like to call a custom morph (`transformDraggedElement`) to show that behaviour instead, eg: on drag over change dragged element preview to "move to gallery" label or something

In general I feel like automatic morphing (`morphDisabled: false`) is fine for basic use cases, but there are use cases where you'd want to disable that default transformation, while applying your own custom transform (`transformDraggedElement`). You can always explicitly have both enabled if you want a morphing baseline.

**Comment by isaacHagoel** [comment]
Alright. Feel free to make a PR, otherwise I'll try to make time for it
next week

**Comment by eduardomartines** [comment]
@madeleineostoja Hey man, I'm trying to do something very similar, did you finish the video example? If there is a REPL would be awesome! TY
