### ISSUE TITLE
Touch / mobile usage : solutions to distinguish slide/swipe and drag?

### ISSUE THREAD

**Issue by PlopTheReal** [isaacHagoel/svelte-dnd-action#406]
Thanks a lot for this wonderfull library.
I'm using it within the following project (a trello like app,  but easy to share):  https://v3.linkednode.com/kanban/CkCPMDIcQ-
On that app, you can slide in all directions but that tends to conflict with the dragging of cards.

I was wondering if that would be possible to start considering the dragging for instance after some delay? This would let the user be able to either slide or drag based on how long he presses on a draggable item. It seems this is how they do it withing the Trello mobile app (not web).

Many thanks for your help! And feel free to play / use / give feedback regarding the app itself! 💯

**Comment by isaacHagoel** [comment]
hi, maybe [this](https://github.com/isaacHagoel/svelte-dnd-action/issues/338#issuecomment-996551637) would help.
u'd probably want to detect that the app is running on mobile and only do it then.

**Comment by PlopTheReal** [comment]
Brilliant, that's should do the job. I'll test that asap and let you know.

**Comment by PlopTheReal** [comment]
That was a bit tricky I ended up controlling the overflow on drag to disable the scroll (works cross browser and that bloody Safari crap). PreventDefault wasn't working for me for some reasons.
