### ISSUE TITLE
Nested Items disappearing/desynchronizing

### ISSUE THREAD

**Issue by Indeedornot** [isaacHagoel/svelte-dnd-action#409]
Hi!
I am trying to implement it in my project and I was able to do it for single groups, however nested groups do seem to now want to play nicely

Here is even an example from an example you provide in the readme as for what happens for me [Board (nested zones and multiple types), scrolling containers, scrolling page](https://svelte.dev/repl/e2ef044af75c4b16b424b8219fb31fd9?version=3.22.2)

As a side question - does `id` have to be a number and do all ids have to be exclusive even for different groups

https://user-images.githubusercontent.com/49447848/200950437-fda1d35d-ea48-4e71-aca1-f4e00e03343f.mp4

**Comment by isaacHagoel** [comment]
Hi, good catch. This issue was introduced in version 0.9.18. Please use version 0.9.17 until there is a fix available.
To your question, IDs don't have to be numbers, strings are what I would normally recommend. They have to be unique within the same type across all dndzones but I recommend just making them globally unique (it's easy so why not)

**Comment by Indeedornot** [comment]
Thank you!, Yes the issue does not appear in version 0.9.17. I'll leave it up to you whether you want to close the issue (as a workaround has been found) or keep it for use and reference with later fixing

**Comment by isaacHagoel** [comment]
@Indeedornot so I was going to debug it but then I realised that it does not happen with recent versions of Svelte.
I tried 3.44.3 as well as latest and it works fine (I think older version has a bug that triggers a destroy event when it shouldn't happen). Which version of Svelte are you using?

**Comment by Indeedornot** [comment]
The repl uses v.3.0.0 by default, I downloaded it and put svelte-dnd-actions at 0.9.21 and went through svelte versions. It seems to be change between 3.22.3 and 3.23 that fixes the issue.

Im purposefully not using my project for the example as to not introduce any different things to the discussion. (funnily enough was using svelte 3.52 and dnd-actions 9.21 at some point together, so seems like the issue was with my code (which for the most part i believe i've fixed), and the issue on repl just happened to exist at the same time XD)

So seems like it's simple using 3.23 for dnd-actions up from 9.18 (I dont know how packaging works, but maybe you could svelte 3.23 upwards as a required dependency for 9.18 upwards)

**Comment by Indeedornot** [comment]
Might also want to update examples in the readme to use at least 3.23

`https://svelte.dev/repl/e2ef044af75c4b16b424b8219fb31fd9?version=3.22.2` to `https://svelte.dev/repl/e2ef044af75c4b16b424b8219fb31fd9?version=3.23.0` etc.

**Comment by isaacHagoel** [comment]
Thanks for finding the specific version.
Would you like to make a PR for the README update? I don't mind doing it myself but if you do it, it will show you as a contributor to this lib. 
If you do do it maybe let's use the latest version of Svelte in the REPL links.

**Comment by Indeedornot** [comment]
I've opened a pull request bumping up examples to the latest version of svelte-3 (version=3 autocompletes subversion to the latest in the link).

Only thing I would recommend doing is setting svelte as dependency with version of at least 3.23, however I do not believe that is a big requirement

Thank you for your help

**Comment by isaacHagoel** [comment]
that's a good idea. pls update the PR and also please bump the lib version
in package.json and update release-notes.md

**Comment by Indeedornot** [comment]
I've updated the pull request

**Comment by isaacHagoel** [comment]
@Indeedornot thanks! merged and published
