### ISSUE TITLE
Origin of the dropped element (source drop-zone)

### ISSUE THREAD

**Issue by Swoopy** [isaacHagoel/svelte-dnd-action#411]
Is it possible to identify the origin of the dropped element from the finalize event? As I see it contains only the target drop-zone element. It would be great to know, where the dropped element came from.

**Comment by isaacHagoel** [comment]
when the element gets dropped both the origin and target zones get a finalize event. 
the lib doesn't have a concept of `id` per dropzone at the moment.
it should be easy enough to capture the id of the origin zone in a store yourself (in the app code) and read in from the target zone upon drop. Let me know if you need me to explain in more detail

**Comment by Swoopy** [comment]
Ok, I got it. Thank you!
