### ISSUE TITLE
Question: Copy item from one list to another

### ISSUE THREAD

**Issue by simoneferrari** [isaacHagoel/svelte-dnd-action#413]
Hi, I have tried various things but could not figure this out.

I have a scenario where I don't want to move items from a list to another but copy them. 
When dropped items would then get a new id.

Items in the original list cannot be re-ordered either. 

Is this possible?

**Comment by isaacHagoel** [comment]
Not sure i understand what you mean. Can you describe it in more detail
please?

**Comment by simoneferrari** [comment]
Sorry for not being clear.

Right now it seems to me you can 
- drag items within a list to re-order them
- drag items out of a list into another and at a specific point in the new list
- the copy and drag example shows how you can make a copy in the original list while dragging the original item into a new list

In my case I want to
- drag a copy of an item from a list and drop it into another list. Id of this item would be set at time of dropping on the new list based on ids of existing items in that list

Essentially the use case is that I have a "template" list and various other lists. I want to be able to "assign" templates to those lists by dragging the templates into them, but at time of dropping, new items are created based on the template.

Hope I was clear this time.

**Comment by isaacHagoel** [comment]
got it.
In the examples the id is copied on drag-start to prevent conflicts (ids
have to be unique).
I suggest that keep it that way but on drop you replace the ids in the
target and origin list with whatever you need them to be.
Would that work?
