### ISSUE TITLE
How to define conditions to enable/disable dragging items to different drop-zones?

### ISSUE THREAD

**Issue by Swoopy** [isaacHagoel/svelte-dnd-action#415]
Hi!
Can you give me some example how can I enable/disable item dragging to different zones on the fly. Like in a JIRA kanban, where I can't move an item from 'To do' to 'Done' directly. When I grab an item, I would like to show in which zones I can drop the item based on item properties. I've tried to change the 'dropFromOthersDisabled' property on the fly via the onConsider event of the the targeted zone, but it doesn't work.  I guess I've missed something.
Thank you!

**Comment by isaacHagoel** [comment]
Changing dropFromOthersDisabled should work. Repl link?

**Comment by Swoopy** [comment]
https://svelte.dev/repl/ec47fca4f4aa49558ea669e44c20c34d?version=3.53.1
Green cards should be movable to all column, grays should be stay in column 1.

**Comment by isaacHagoel** [comment]
I see, so I would suggest setting the other dropzones to
dropFromOthersDisabled=true and change it to false if a green card is
picked up (can be detected on drag start). On drop change them to true
again.
Will that not work?

**Comment by Swoopy** [comment]
Yes it work. However the HTML drag events aren't work in the REPL, so I used the on:mousedown event to open the right zones, and a function on finalize event to close the zones. It means the closing function is triggered twice. HTML drag events should work, but maybe a dedicated startDrag/stopDrag event which would be triggered only once would be nice.

There is a strange behavior with the zone highlighting. If the zone is empty by default, there is no highlighting. If I put an item in it, everything works fine, even if I put out all of the elements after. See it in the REPL. Maybe it's just the styling.

**Comment by isaacHagoel** [comment]
you can use the `trigger` property in the consider/finalise events.
with highlighting it sounds like a bug. REPL?
