### ISSUE TITLE
Q: Virtualization of draggable items

### ISSUE THREAD

**Issue by Indeedornot** [isaacHagoel/svelte-dnd-action#417]
Hi!
In a project that I currently am working on I've stumbled onto an issue of overrendering. I've looked into available virtualization solutions, however all of them work on direct children, similarly to this library. How would you advise approaching this issue?

![image](https://user-images.githubusercontent.com/49447848/205450005-9b521619-8aa0-461a-a1f2-5c9f8cca309f.png)

**Comment by isaacHagoel** [comment]
What do you mean by overrendering?

**Comment by Indeedornot** [comment]
Oh apologies for using unspecific term. In this case just meaning rendering items off screen, not required to be displayed due to being in am overflow. 

As such it causes there to be too many elements in the dom and a lag

**Comment by isaacHagoel** [comment]
Why not write an 'isOffScreen' action and use it to toggle display:hidden
or something like that?
I think it shouldn't be too complicated. What am i missing?

**Comment by Indeedornot** [comment]
> Why not write an 'isOffScreen' action and use it to toggle display:hidden

Oh okay, I assume that it is the only way (i.e. css properties) due to the workings of the library? Maybe not what I thought to do, but I believe it will be easy to implement in such form and should work as expected.

Thank you for your quick response
