### ISSUE TITLE
run transformDraggedElement on same dropzone

### ISSUE THREAD

**Issue by janrito** [isaacHagoel/svelte-dnd-action#419]
currently transforming the in-flight element is triggered when it enters a drop-zone, but not in the same one.

This means that styling the element is inconsistent.

I figured out how to achieve this using a global `#dnd-action-dragged-el` directive. But this is cumbersome `#dnd-action-dragged-el` vs `DRAGGED_ELEMENT_ID` and also, it only allows us to add styling, not replace it. 

My usecase is, the element uses a class `shadow-sm`, but while being dragged, I want it to be replaced with `shadow-xl`

**Comment by isaacHagoel** [comment]
so on dragstart you want to run a function on the dragged element after it
has been styled by the lib?

**Comment by janrito** [comment]
I'm actually having trouble trying to build an minimum setup to reproduce this. The issue I have is with multiple dropzones, a source one where dropping is disabled and it automatically copies the dragged item - like the dragula example (unless dropped in the same zone).  The dragged item fails to transform until it is dragged-considered over another dropzone
