### ISSUE TITLE
Help with filtering lists

### ISSUE THREAD

**Issue by Gazook89** [isaacHagoel/svelte-dnd-action#422]
I have two dnd zones from which i can move items between.  I would like to be able to add a text input filter on each.  However, with my current setup the filter uses the full set of original items in a list.....so it filters correctly when i start typing text, but when i remove all of the text from the input (to an empty string for the search term), it fills the list with all of the original items again.   Rather than the altered list after having moved items to the other dnd zone.

How could I get the *current* list of items in a dnd zone, so that I can send it to the filter?  

I suspect this is a simple thing, though I am just starting with Svelte and certainly no pro with vanilla js either.

**Comment by isaacHagoel** [comment]
It sounds like it should be simple but I will need to see the code to say
for sure. Can you make a REPL?

**Comment by Gazook89** [comment]
I think I need to step back and consider this further.  Likely I'm just stuck on a basic svelte problem.  Before taking your time I feel like I need to spend a little more time on it myself.  Closing (for now), and thanks!
