### ISSUE TITLE
Overlapping drop zones are a bit hard to deterministically work with

### ISSUE THREAD

**Issue by luan** [isaacHagoel/svelte-dnd-action#426]
This took me a while to figure out, but because dropzones are sorted by _depth_ (in the tree), if you have a fixed/absolute positioned dropzone that overlaps with another one, the one that happens to be deeper will win, but that's not always desirable.

Here's a contrived example in the REPL:
https://svelte.dev/repl/bd019a07008049c5973cdc7d864003bc?version=3.55.1

If you try to drag from under to over (left to right) you only hit the dropzone on the right once you're completely out of the rect of the one on the left (because it's artificially deeper in the tree with those extra divs).

Obviously this example is exaggerated, but in my real use case I have a dropzone that slides into view, has a much shallower structure, and conflicts with that it's covering.

I hacked around it by putting my floating dropzone into an artificially deeper tree, but I think maybe we could solve it with (optimally) specified dropzone priority?

The "correct" behavior here would probably be the exact same stacking as the browser does, so that z-indicies would apply, but I think that may be too complex to implement.

**Comment by isaacHagoel** [comment]
Thanks. I am open to pull requests or deeper investigation of how to
imitate the browser stacking in a performant way
