### ISSUE TITLE
Too much recursion

### ISSUE THREAD

**Issue by sytanta** [isaacHagoel/svelte-dnd-action#431]
I met this issue when dragging a deeply nested list as in the following REPL:

https://svelte.dev/repl/42718fc8ac8546a0ae5ecde405ca17e7?version=3.55.1

Keeping dragging "item 4" around will trigger it.

![too-much-recursion](https://user-images.githubusercontent.com/4252962/217718251-3ca8377d-3db2-4d48-a5d6-1840df869c71.png)

Thanks!

**Comment by isaacHagoel** [comment]
Based on the error message from your screenshot, it looks like it is coming
from Svelte ,not from the lib. Do you mind checking older versions and the
issues on their repo?

**Comment by sytanta** [comment]
Sure I will and will let you know.

**Comment by sytanta** [comment]
Checked all svelte versions from 3.23.0 onward and the issue persisted. Some similar issues from svelte repo:

https://github.com/sveltejs/svelte/issues/7032
https://github.com/sveltejs/svelte/issues/3218
https://github.com/sveltejs/svelte/issues/2542

There was some logic from `<svelte:self>` that ran excessively when `on:consider` was called.

**Comment by isaacHagoel** [comment]
Thanks a lot! As I said, I am pretty sure it is not related to the lib but
I'll try to find time to have a look.
