### ISSUE TITLE
ondragover Event

### ISSUE THREAD

**Issue by Tezzus** [isaacHagoel/svelte-dnd-action#437]
Hey Isaac thanks for contributing this great library to the svelte community!!

Is an "ondragover Event" planned ?? Would be very helpful :)

https://www.w3schools.com/jsref/event_ondragover.asp

**Comment by isaacHagoel** [comment]
The lib uses 'consider' events instead. Is there anything you are trying to
acheive and can't?

**Comment by Tezzus** [comment]
Yes I would like to get the element (A) that is being hovered over by the dragged element (B). Thanks for helping :)

**Comment by isaacHagoel** [comment]
You should be able to get that from the information in the consider events.
There are also internal events that the lib uses and nothing prevents you
from listening on.
If you make a repl demonstrating what you're trying to acheive, i can try
to fix it for you
