### ISSUE TITLE
Point of Triggering Flip / Consider

### ISSUE THREAD

**Issue by Tezzus** [isaacHagoel/svelte-dnd-action#438]
Hey Isaac, I would really like to change the point where the flip of two items is triggered.

Observed State: Item (A) flips (throws consider) when the dragged Item (B) passes the center of Item (A) with its top or bottom border.

Wanted State: 

List 
A
B

1) Item (A) flips (throws consider) when the dragged Item (B) passes the top of Item (A) with its bottom (Item B) when B is originally below A. 

List
B
A
2) Item (A) flips (throws consider) when the dragged Item (B) passes the bottom of Item (A) with its top (Item B) when A is originally below B. 

Where in the src can I change this ?

Appreciate Your Help. 👍

**Comment by isaacHagoel** [comment]
have a look at 
https://github.com/isaacHagoel/svelte-dnd-action/blob/master/src/helpers/observer.js
which uses
https://github.com/isaacHagoel/svelte-dnd-action/blob/master/src/helpers/listUtil.js
which uses
https://github.com/isaacHagoel/svelte-dnd-action/blob/master/src/helpers/intersection.js

**Comment by Tezzus** [comment]
Hey Isaac, thanks a lot. 

Setting TOLERANCE_PX in observer.js to element.offsetHeight() * VAR

solved the issue for me 👍

**Comment by saturnonearth** [comment]
Can we get this as an adjustable prop?
