### ISSUE TITLE
Return dragged item to original container

### ISSUE THREAD

**Issue by danxcraig** [isaacHagoel/svelte-dnd-action#442]
Is there a way to return an item to the container it originated from without dragging it back there?

For example:

* I have two dnd containers.
* I drag an item from container 1 to container 2
* I click a 'move back' button 
* The item is removed from container 1 and returned to container 2

**Comment by isaacHagoel** [comment]
Sure. This should be easy to implement. The lib won't do it for you though.
You need to store the state you want to rollback to and the rollback logic.
If you need help with this pls make a repl and i can assist

**Comment by danxcraig** [comment]
Thanks, was mainly seeing if the lib could get there. Ended up using stores to achieve the results I needed. Pretty nice outcome!

https://user-images.githubusercontent.com/11553887/228537834-99493151-dcc3-4d81-92d2-4e1de7c80507.mp4

**Comment by isaacHagoel** [comment]
Nice!
