### ISSUE TITLE
[Error] TypeError: undefined is not an object (evaluating 'el.getBoundingClientRect')

### ISSUE THREAD

**Issue by zahachtah** [isaacHagoel/svelte-dnd-action#444]
I am doing something a bit advanced and before trying to redo and isolate it in a REPL I'd like to ask if you would have any hint as to what could possibly cause this error, it happens after dragging an item from a nested dnd into a new zone. dragging it within the same base zone does not give error. Just asking for a first guess since you are so familiar with svelte-action-dnd so I can investigate. If not I'll work up a corresponding REPL to isolate it.

[Error] TypeError: undefined is not an object (evaluating 'el.getBoundingClientRect') (in intersections.js line10)
	getBoundingRectNoTransforms (svelte-dnd-action.js:126)
	animateDraggedToFinalPosition (svelte-dnd-action.js:825)
	handleDrop (svelte-dnd-action.js:822)

**Comment by isaacHagoel** [comment]
could it be that the destination zone gets removed upon drop before the lib has the opportunity to animate the dropped item into place?
you can try to turn off the animations "flipDurationMs=0" and see if it still happens

**Comment by zahachtah** [comment]
"flipDurationMs=0" didn't help, but I had to refactor the code and it seems to work now. I do think I had some inconsistencies in how the divs were used.

**Comment by brendan-morin** [comment]
I'm running into `TypeError: undefined is not an object (evaluating 'el.getBoundingClientRect')`, and also found that setting duration to 0 didn't help. 

I am able to reproduce by grabbing the element and throwing it somewhere and releasing quickly. If I do it slowly it does not throw the error. I was also able to reproduce a similar `TypeError: undefined is not an object (evaluating 'originalDragTarget.parentElement')` if I do the same but the release is nearby the original location.

In my case, I am using this alongside `use:autoAnimate`, and if I remove that, I'm not able to reproduce (though I will say the combined effect of both libraries looks really nice!). Full definition:
```html
<div
    use:autoAnimate
    use:dndzone={{
        items: option.values,
        dragDisabled: !isEditing || isPending,
        flipDurationMs: 200,
        dropTargetStyle: {},
        // Limit to dropping values within the same option
        type: String(option.id),
    }}
    onconsider={(e) => handleDndConsider(option.id, e)}
    onfinalize={(e) => handleDndFinalize(option.id, e)}
>
```
and
```typescript
const handleDndConsider = (
    optionId: number,
    e: CustomEvent<DndEvent>
) => {
    const index = options.findIndex((o) => o.id === optionId);
    options[index].values = e.detail.items;
};
const handleDndFinalize= (
    optionId: number,
    e: CustomEvent<DndEvent>
) => {
    const index = options.findIndex((o) => o.id === optionId);
    options[index].values = e.detail.items;
};
```
loop is something like:
```
{#each options as option (option.id)}
    <div
        use:autoAnimate
        use:dndzone...
    >
        {#each option.values as value (value.id)}
            <div animate:flip={{ duration: 200 }}>
```

**Comment by isaacHagoel** [comment]
If you turn this into a repl I can have a look. Most likely the animation
action is replacing an element in the Dom (a common trick in animation)
which breaks this library
