### ISSUE TITLE
Uncaught TypeError: el is undefined

### ISSUE THREAD

**Issue by DeveloperMarius** [isaacHagoel/svelte-dnd-action#446]
Hey,

I'm getting the following error when I'm dropping an element into another dropzone:
```
Uncaught TypeError: el is undefined
    getBoundingRectNoTransforms intersection.js:10
    animateDraggedToFinalPosition pointerAction.js:272
    handleDrop pointerAction.js:267
    handleDragStart pointerAction.js:440
    handleMouseMoveMaybeDragStart pointerAction.js:364
    addMaybeListeners pointerAction.js:337
    handleMouseDown pointerAction.js:387
    configure pointerAction.js:527
    update pointerAction.js:544
    update action.js:34
```

I think this is caused because the element placeholder/ shadow does not exists in the target dropzone.
In this specific case I don't want that this element can be dropped into the target dropzone and because of this I'm not updating the displayed items:
`items = [...items];` instead of `items = [...e.detail.items];`
Can you please add a check if the element you are getting the position for really exists so that this error is not thrown?

Thank you for this wonderful library.

~ Marius

**Comment by isaacHagoel** [comment]
I need to understand better what you're trying to do/avoid. Can you pls
make a simple REPL?

**Comment by DeveloperMarius** [comment]
Hey,
I fixes my issue after trying to reproduce it. 
Thank you.

~ Marius

**Comment by dsignr** [comment]
> Hey, I fixes my issue after trying to reproduce it. Thank you.
> 
> ~ Marius

Hi, any ideas on how you managed to solve this? I have the exact same issue.
