### ISSUE TITLE
Items with methods

### ISSUE THREAD

**Issue by Swoopy** [isaacHagoel/svelte-dnd-action#447]
Hi,
I try to use items with methods (instances of a class) in dropzones, but in the consider/finalize events the items only contains the properties without the methods. Is that the normal behavior? Do the dnd-action deepcopy the items including methods when making the e.detail.items array? How can I keep the methods? Maybe I'm misunderstanding something... :)
Best regards,
Swoopy

**Comment by isaacHagoel** [comment]
Can you please make a repl that reproduces the issue?

**Comment by maps82** [comment]
He probably means something like this, which doesn't work:

https://svelte.dev/repl/153779c4ea2f4cb7ac6e55810b9275ec?version=3.58.0

**Comment by isaacHagoel** [comment]
Thanks @maps82 . I normally don't like to assume but I think you're right.
I had a quick look. 
If you change line 27 to be ` {((item instanceof Item) && item.getTitle()) || "hello"}` there will be no errors but you'll see exactly when the class is replaced with an object and loses the method.
As far as I know JS does not provide a generic way to clone an instance of a class (if there is one please comment and reopen this issue).
I would suggest dealing with it in the event handlers (for consider and finalize) and instantiate new instances of the class from the array that's provided by the library. That should be easy to implement (happy to help if needed)

**Comment by maps82** [comment]
I gave up dealing with the instances in the consider/finalize methods and created a simple plain object array for use with dnd (which comes from a svelte store):

```javascript
let items = [];
$: items = $myArrayOfClassInstances.map((a) => ({id: a.id, name: a.name,}))
``` 
In  finalize I sync the items back to my array of class instances, which works fine.
