### ISSUE TITLE
Crazy nesting with easy access to node data

### ISSUE THREAD

**Issue by Aliyss** [isaacHagoel/svelte-dnd-action#448]
Hiya

First of all thanks a lot for the package. This is just great.

I was working around some stuff and I really needed it to be recursive so I looked at [Crazy 
Nesting](https://svelte.dev/repl/fe8c9eca04f9417a94a8b6041df77139?version=3.58.0). But wanted to be able to reuse it for other components.

So I modified it a bit, so the data is accessible from the parent and can be reused. Also this way one can abstract the "UI Schema" from the "Data" and so to speak index another object.

Modified: https://svelte.dev/repl/9ad1b529c471472e8d4b27c135ef36ad?version=3.58.0

I know issues are usually used to describe Issues, however I thought maybe if someone else stumbles upon the same thing it could help having it here.

**Comment by isaacHagoel** [comment]
Thanks for that! I tagged it as an example.
