### ISSUE TITLE
Highlight drop zone `on:consider` with `TRIGGERS`

### ISSUE THREAD

**Issue by Adimac93** [isaacHagoel/svelte-dnd-action#465]
Changing style based on `TRIGGERS`. So far I've inspected `dropTargetClasses` value and its value is always set properly. 

Unfortunately dynamic style is out of sync in two ways:
- dragging over the same drop zone causes it to stop updating color
- dropping element in zone causes other _dragged-over_ zones to stop updating color
```ts
function handleConsider(
    e: CustomEvent<
        DndEvent<{
            id: number;
            activity: Activity;
            colId: number;
        }>
    > & {
        target: any;
    }
) {
    const trigger = e.detail.info.trigger;
    if (trigger === TRIGGERS.DRAGGED_ENTERED) {
        dropTargetClasses = ["bg-black"];
    } else if (trigger === TRIGGERS.DRAGGED_LEFT) {
        dropTargetClasses = ["bg-transparent"];
    }
    // ...
}

async function handleFinalize(
    e: CustomEvent<
        DndEvent<{
            id: number;
            activity: Activity;
            colId: number;
        }>
    > & {
        target: any;
    }
) {
    dropTargetClasses = ["bg-transparent"];
    // ...
}
```

```html
<section
    class="... bg-transaprent"
    use:dndzone={{
        items: draggableActivities,
        flipDurationMs,
        type: "activities",
        dropTargetStyle: {
            "box-shadow": `0px 0px 0px 4px rgba(164, 190, 224, 0.2)`,
            "border-radius": "0.25rem",
        },
        dropTargetClasses,
    }}
    on:consider={handleConsider}
    on:finalize={handleFinalize}
>
    {#each ... (id)}
       <Component animate:flip={{ duration: flipDurationMs }}>
    {/each}
</section>
```

Here is a video demonstrating this problems. Value of  `dropTargetClasses` is displayed above columns.
[Video](https://github.com/isaacHagoel/svelte-dnd-action/assets/47300834/fe5498bf-368b-4fc6-9c61-f78907ded430)

It might be that TRIGGERS aren't suitable solution for my problem, please let me know.

**Comment by isaacHagoel** [comment]
To make sure I follow, what are you trying to achieve?
Do you want the background of the all available drop zones to change mid drag based on whether the dragged element entered one of them?

**Comment by Adimac93** [comment]
I want to highlight only one zone that currently is being considered for the element drop, so mid drag based.

**Comment by isaacHagoel** [comment]
So why modify the dropTargetClasses rather than style the drop zone
yourself (use the trigger to turn some boolean on/off and base the style on
that)?

**Comment by Adimac93** [comment]
I've found out that `dndzone` style updates after `finalize`. I've tried to base the style on boolean (for the second time :laughing:) but this time it worked and I have no doubt that something is bugged. Thank you for guidance and awesome library!

**Comment by bouchtaoui-dev** [comment]
> I've found out that `dndzone` style updates after `finalize`. I've tried to base the style on boolean (for the second time 😆) but this time it worked and I have no doubt that something is bugged. Thank you for guidance and awesome library!

It would be nice if you a show  working example, maybe people like can benefit from :)
