### ISSUE TITLE
Crazy nesting item shakes then flyes away when targeting outer container

### ISSUE THREAD

**Issue by vini-brito** [isaacHagoel/svelte-dnd-action#472]
Hello! How to avoid the "shaky" and the "fly away" behaviours when using nested containers?
Note how the dragged element shakes and moves away even if the mouse cursor is doing a straight line movement and a much smaller movement than what the element makes.

It happens mainly when I try to drag to outer containers (see GIF below):

![Peek 2023-08-16 17-03](https://github.com/isaacHagoel/svelte-dnd-action/assets/6878457/c123fe4e-6b79-43c4-8715-7103c9638915)

Here is the URL of the standard example: https://svelte.dev/repl/fe8c9eca04f9417a94a8b6041df77139?version=3.59.2
Not mine, just the one linked in the library's readme.

**Comment by isaacHagoel** [comment]
Ah it is probably the same as [this](https://github.com/isaacHagoel/svelte-dnd-action/issues/470). Can you try an earlier version? Does it happen only in the REPL or outside of it as well?
I am planning to deploy a fix this week

**Comment by vini-brito** [comment]
You are right, locally it works great, no shaking and no flying away, see GIF below:
Locally it is smoother than what it is in the GIF, seems like my FPS were low in this recording, just saying in case anyone comes across this in the future. 

![Peek 2023-08-16 17-24](https://github.com/isaacHagoel/svelte-dnd-action/assets/6878457/bb362068-597f-45d9-8dd9-3db522a77ee5)

**Comment by isaacHagoel** [comment]
This is fixed in version 0.9.25 (works in REPL as well as locally)
