### ISSUE TITLE
Bug: If child element has transition or out transition - items will disappear on move

### ISSUE THREAD

**Issue by chanmathew** [isaacHagoel/svelte-dnd-action#474]
Hi there, came across a bug where if you have a `transition` directive or `out` directive within a draggable element in the list, it will cause issues with rendering of the draggable list and the items will disappear. However, if you have an `in` directive, the animations will still work, it only seems to break if it's an `out` or full `transition`.

Please see this REPL:
https://svelte.dev/repl/ce96ac99e07349c8a44d741ff34ce981?version=4.2.0

**Comment by isaacHagoel** [comment]
From the README:
> Svelte's built-in transitions might not play nice with this library. Luckily, it is an easy issue to work around. There are examples above.

**Comment by chanmathew** [comment]
Ah missed that, thanks for your prompt response!
