### ISSUE TITLE
Drag and drop across two different zones leads to undefined error

### ISSUE THREAD

**Issue by dsignr** [isaacHagoel/svelte-dnd-action#477]
Hi, I created a REPL to illustrate my issue:
https://svelte.dev/repl/f9152ceb69924e6e9cd9eff6f95e73da?version=4.2.0

Try to drag any of row, box or grid into container. You will notice an error in the console.

```
Uncaught TypeError: el is undefined
    getBoundingRectNoTransforms

```
It is coming from `src/helpers/intersection.js`  from the function `getBoundingRectNoTransforms`. 
Basically the element in `const rect = el.getBoundingClientRect();` is undefined. 
This function is being called from `src/pointerAction.js`. From what I can see, the shadow element doesn't exist in the target drop zone and therefore it throws an error. 

There is another issue where someone raised the same exact problem but they have somehow managed to solve it. https://github.com/isaacHagoel/svelte-dnd-action/issues/446

I am unsure how to solve this, any pointers would be useful.

Thank you.

**Comment by isaacHagoel** [comment]
Hi,
I will have a look later today or tomorrow at the latest. What I would
expect to see is something (not the lib) that is removes the element in
question from the DOM midst drag.

**Comment by dsignr** [comment]
Thank you for the fast response! There is nothing else in my code manipulating the DOM, in fact the REPL I shared is from my interface directly (hence you see lot of tailwind classes). I hope this helps.

**Comment by isaacHagoel** [comment]
I haven't looked yet but are any of the tailwind classes adding out
transitions?

**Comment by dsignr** [comment]
I am pretty sure, no. I ran it through a vanilla setup and the result is still the same. However, manipulating the items array in `CanvasLoop.svelte` in the REPL to the following removes the error:

```
    function consider(e) {
        nodes = e.detail.items
    }

    function finalize(e) {
        nodes = [...nodes]
    }
```

So, I guess something to do with the array passed from the parent (`Canvas.svelte`)?

**Comment by isaacHagoel** [comment]
Ahh you found the issue without me.
In the original REPL there are consider and finalize handlers that don't
re-assign the items array. As the README states a few times, you have to
update the list in these handlers (even if you don't use the items from the
event or even if just assign it to itself) in order for the lib to work
properly. Without the assignment there is no re-render and the action's
update method isn't called by Svelte.

**Comment by dsignr** [comment]
Thank you, that makes sense. Sorry I missed it in the docs and wasted your time. Thanks for the quick response, and as I stated earlier, awesome library, thank you. 

And one last thing - Please consider adding a PayPal donate button on the GitHub readme :)

**Comment by isaacHagoel** [comment]
No worries. This one is easy to miss. I wish there was a way to warn the user when that happens. Happy to help
