### ISSUE TITLE
Issues in 0.9.27

### ISSUE THREAD

**Issue by matt8707** [isaacHagoel/svelte-dnd-action#482]
I’m seeing bugs in 0.9.27. I have dnd sections, and in those dnd items, when a section is dragged, the section below it gets `visibility: hidden;` added to it in chrome (until page reload). This doesn’t happen if i remove the nested items or change section display from grid to block.

I'm also seeing "Bug! trying to decrement when there are no dropzones"

None of these issues happen if i downgrade to 0.9.26

**Comment by isaacHagoel** [comment]
This is really weird. Any change you can provide a REPL that can be used to reproduce the issue?

**Comment by matt8707** [comment]
https://svelte.dev/repl/c468b005aad4425aad1f6da628c397b6?version=4.2.0

**Comment by isaacHagoel** [comment]
What do i need to do in order to reproduce and which browser and OS are you using? 
I drag stuff around (mac, chrome) and get no issues. 
I suspect I know what the problem might be but I want to be able to reprod.

**Comment by matt8707** [comment]
I'm using macos 13.5.1. I can reproduce in chrome, safari and firefox. Dragging a section, visibility: hidden gets added.


https://github.com/isaacHagoel/svelte-dnd-action/assets/36163594/3e47f547-f10d-47b5-aa6e-5bf740b646e3

**Comment by isaacHagoel** [comment]
thanks. initially i didn't understand what i am looking at. the video helped it click.
i reverted the problematic change.
