### ISSUE TITLE
Nesting issue 

### ISSUE THREAD

**Issue by TheAvonian** [isaacHagoel/svelte-dnd-action#495]
I have been having an issue with a personal project and originally I had a data layout where it was one large object that has children and those children might have children and it goes on and on, but two errors would occur depending on what happens on finalise. 
![image](https://github.com/isaacHagoel/svelte-dnd-action/assets/29378966/a230dda9-ce78-4d5d-893a-52239df23dfd)
This error would pop up after finalising a drag and another issue would be after finalising a drag into its same spot, I logged the before and after state of the object and the dragged one's data would add another {} to the array.

I created a simple repl demonstrating this behaviour.
https://svelte.dev/repl/714e10b3f8644eb4992c1276bc735dd1?version=4.2.0

Thank you.

Edit: forgot to add that I ended up changing my data layout to be more like the nesting example whilst maintaining my logic and the same issue occurs so I'm using that in the repl

**Comment by isaacHagoel** [comment]
I had a quick look. It seems to happen because you are doing 
```	{@const datachild = map[child.id]}```
But during the drag operation the placeholder/shadow item gets a temporary id and therefore datachild is undefined.
There are multiple potential fixes. the first one that popped to my mind:
you can find the original id in e.detail.info.id, u can assign it to a variable and use that to grab what you need from the map if the original id returns undefined

**Comment by TheAvonian** [comment]
Hmm I've swapped out that expression and replaced a fair majority of the code and now it is almost identical to the Crazy Nesting example yet this issue still occurs...
https://svelte.dev/repl/714e10b3f8644eb4992c1276bc735dd1?version=4.2.0
Heres the link again I think I saved over the other example.

**Comment by TheAvonian** [comment]
I just figured it out, turns out the issue was this section
```jsx
<div
	use:dndzone={{ items: current.children, flipDurationMs: 200 }}
	on:consider={onConsider}
	on:finalize={onFinalize}
	class="group"
>
	<div> // RIGHT HERE
		<div>
			{current?.id}
		</div>
	</div> // TO HERE
	{#each current.children as child(child.id)}
		<div class="item">
			<svelte:self
				current={map[child.id]}
				bind:map={map}
			/>
		</div>
	{/each}
</div>```
Removing that made it work. 
Thanks for the help tho!

**Comment by michalstruck** [comment]
Bruh I cannot believe it but that fixed my issue as well. Wild
