### ISSUE TITLE
Cannot use dropTargetClasses to modify outline, since dropTargetStyle has a default value.

### ISSUE THREAD

**Issue by kenbankspeng** [isaacHagoel/svelte-dnd-action#498]
Since I use Tailwind, I prefer dropTargetClasses over dropTargetStyle.

With dropTargetStyle taking priority over dropTargetClasses, I am unable to apply an outline using dropTargetClasses since dropTargetStyle has a default value of {outline: 'rgba(255, 255, 102, 0.7) solid 2px'}.

When I remove the default outline using the option dropTargetStyle: { }, I continue to be unable to set an outline using dropTargetClasses. 

It seems for outline, I must use dropTargetStyle.

Is it possible to remove the default value for dropTargetStyle?

**Comment by isaacHagoel** [comment]
I didn't look into it yet but would be super useful if u make a simple REPL
that illustrates the issue

**Comment by kenbankspeng** [comment]
[REPL](https://svelte.dev/repl/a06cb7aca7f049059a9fd772d832ffbf?version=4.2.1)

:global(.drop-target){
    background: red;
    outline: blue solid 10px;
}

On drag, the drop zone has a red background but not a blue outline.

I observe adding the option dropTargetStyle: {} does resolve the issue here, although I did not see this work when using tailwind css.

**Comment by isaacHagoel** [comment]
the REPL allows using tailwind (u can import or add it via a script tag).
i need to see the issue reproduced in order to debug.
if in the repl above u are able to remove the default style then there is no problem...

**Comment by kenbankspeng** [comment]
The workaround also works for tailwind. I had assumed 'outline-4' was sufficient. It required 'outline outline-4'. Will close this.

I know it's very minor and just an opinionated suggestion, but unstyled might be a better default, leaving styling to the consumer. 

Aside: dropTargetClasses is an array of strings, but seems to only work with 1 class per string. You would be more compatible with tailwind if you allowed multiple classes per string. Right now, I would have to do this: `dropTargetClasses: ['bg-neutral-900', 'outline', 'outline-4', 'outline-blue-500', 'etc.']` instead of `dropTargetClasses: ['bg-neutral-900 outline outline-4 outline-blue-500 etc.']`.

**Comment by isaacHagoel** [comment]
The idea of that default was to have something functional right out of the
box.
Splitting by spaces should be a simple change. I am open to a PR.
