### ISSUE TITLE
Childless branch within tree

### ISSUE THREAD

**Issue by kenbankspeng** [isaacHagoel/svelte-dnd-action#500]
See [REPL](https://svelte.dev/repl/35ea5630dd0c484ab8b2ca7e41ab0684?version=4.2.1.)  - I have a 3-level tree with each level being a dnd drop zone, allowing me to rearrange level 1 items, level 2 items and level 3 items as needed. For example, I can drag a level 3 item from one branch to another outside of the original parent.

But if at any time a branch has no children (pre-rearrange or as a result of dnd rearrange), then the parent no longer has a drop zone for the insertion of a first-item child.

Have you come across this? Any suggestion? Is the solution to insert a 1px high dummy drop zone ensuring every parent has at least 1 child?

Thanks.

**Comment by isaacHagoel** [comment]
I can't look at the repl right now but why not minHeight on the dnd zone?

**Comment by kenbankspeng** [comment]
Like Trello board? But tree doesn't have a blank landing pad like a trello column would.

**Comment by isaacHagoel** [comment]
maybe you can apply the min height only while dragging (after drag start
until drop)

**Comment by kenbankspeng** [comment]
Maybe best solution is some exception logic for nested that allows drop on a parent when child list is empty. It seems sortablejs does it that way. Closing this.
