### ISSUE TITLE
Class instances cannot be used in items array as original dragged item gets copied

### ISSUE THREAD

**Issue by magnusdahlstrand** [isaacHagoel/svelte-dnd-action#512]
Hi, and thanks for writing a solid dnd library for svelte.

Unfortunately, the library doesn't support lists of class instances.

In `handleDragStart`, a copy of the dragged item is made into `draggedElData` instead of using the original object directly. If the original object is an instance of a class, the copy is not an instance. When the finalize call happens, this copy is used instead of the original object in the reordered array.

[This is the code causing this](https://github.com/isaacHagoel/svelte-dnd-action/blob/554135cbea198acee4e35dd256efa847079c17af/src/pointerAction.js#L390C9-L390C22).
This change seems to have been introduced in commit [14a6a6b](https://github.com/isaacHagoel/svelte-dnd-action/commit/14a6a6b98fb00f791261c374084d1e66a1a77366#diff-3eff2eb784c259a70aa99b331bdf2de36ef13b78240a7789e3e530e0f639f817R145).

One way I can currently work around this is by creating an "overlay list", essentially a list which maps over the original list and references the ID and the real object, and as the copy is only shallow this works, but ideally a copy would not be created at all, or at least the original object would be used in the finalize call instead of said copy.

I have [produced a test case in the REPL](https://svelte.dev/repl/1567cdef5b314466880a890ed55a80ec?version=4.2.2), where if you drag an item, on reorder the title will become "undefined", as the text was produced by the method `get title()` on the `Item` class, which the new copied item is not an instance of.

Thanks, Magnus

**Comment by isaacHagoel** [comment]
Would changing that line from `draggedElData = {...items[currentIdx]}` to ` draggedElData = items[currentIdx]` fix the issue?

**Comment by magnusdahlstrand** [comment]
It seems that would fix it - just providing a PR!

**Comment by dnlbln** [comment]
Just came here to say ran into the same issue and using the same work around. What's the update on the pull request being merged ?

**Comment by isaacHagoel** [comment]
Was waiting for the PR author to update the version and release date but
haven't heard back. If he doesn't do it by tomorrow I will address it
myself
