### ISSUE TITLE
Integrate Svelte-Movable into svelte-dnd-action

### ISSUE THREAD

**Issue by tsemachh** [isaacHagoel/svelte-dnd-action#514]
Hi
Has anyone experienced in integrating [svelte-movable](https://github.com/daybrush/moveable/tree/master/packages/svelte-moveable) into svelte-dnd-action -
Don't get me wrong the system is awesome , UI wise I would like to provide the users some of the features exist in movable
Thanks
Tsemach

**Comment by tsemachh** [comment]
Hi 
We didn't try it yet, we were examining alternatives.
Eventually , we choose react for the project , so they took react-grid-layout with React-moveable and it's working o.k.

I think if it was somehow pre-integrated it could be a great choice for many projects

**Comment by isaacHagoel** [comment]
I see. Thanks for the info.
I will close this for now but will keep it in mind if/when there is more interest in the future.
