### ISSUE TITLE
Usage with Svelte 5's $state

### ISSUE THREAD

**Issue by JVariance** [isaacHagoel/svelte-dnd-action#522]
I struggled with getting svelte-dnd-action to work with an $state array as items source, but finally I got it right.
[REPL](https://svelte-5-preview.vercel.app/#H4sIAAAAAAAACsVSXWvEIBD8K4stXAK5XD_e0iRQWgr9DXf3IHHDCUaDmsKd-N-rnmkLpc_1IewOM7OzGkdGLtCQZu-IpBOShjzPM6mIPc-xMR8oLIbeqEUPEWnNoPls-4M8WD7NSltwwCS7KIngYdRqgs1Vtg3wlg6WK7l5CvygEGhhOr9bnAx0cGsstVjsHWcN3PkKUnG_Fg9r8eiPZTYYF5kM4UQlE_gq2YuShjPUBZbgDhLCGQJkgecpWDO0lIs6AfVE56LgtoSuD8mvgng02kXLANV1YIKPAy2AL3PxHTv5JNT_FeqNSyr4Bf8pVLv7fiXZLiIaLgab_E6dy5mSqFldqgh6H79KDvlaO_frpjNjzDv-YKxrB0YfSe4G6XD6SklNmlgBhyIWNWelvyZpBe9dxny7C13S76I-LbSIPvyGk2J85MhIY_WC_ug_AX2y1tbBAgAA)

compressed solution:
```typescript
   e.detail.items.map((it) => { 
        return { ...it };
  });
```

**Comment by isaacHagoel** [comment]
Interesting. I haven't tried runes yet. Why is this required? Do you have
any idea? Why didn't it "just work"?

**Comment by JVariance** [comment]
Actually, it does "just work"... didn't try that out in the repl, because it didn't work in my project... Weird 🤔

**Comment by JVariance** [comment]
In my project it's in fact just working with the solution of above.
So, what I **can** say, is that items will have mixed values (proxies and simple objects) when using ` use:dndzone={{ items: myItems }}`.
![image](https://github.com/isaacHagoel/svelte-dnd-action/assets/62245444/9788cbda-29ca-4a58-b27e-ea0451f0570b)

And when used like above it includes only the objects.
![image](https://github.com/isaacHagoel/svelte-dnd-action/assets/62245444/1c62497d-89a1-4d1c-8d9a-6af446fcab5c)

**Comment by JVariance** [comment]
More precisely, the reordering **is** also working with `use:dndzone={{ items: myItems }}` in my project, but then the state is kinda messed up and the ui is not updating as expected on other changes. It's quite possible that I have something "wrong" in my code, which, if clarified, would make my approach `myItems.map((it) => { return { ...it }; }` obsolete.

**Comment by isaacHagoel** [comment]
Got it. Thanks for the clarification

**Comment by JVariance** [comment]
Ok, now it suddenly also "just works" in my project after some changes I made. If you want to, you can remove this issue 😅

**Comment by isaacHagoel** [comment]
Haha, good to hear. All good
