### ISSUE TITLE
ReferenceError: self is not defined after migrating to sveltekit2

### ISSUE THREAD

**Issue by noobmaster19** [isaacHagoel/svelte-dnd-action#526]
Here's a shortened form of the error:

```
4:16:44 PM [vite] Error when evaluating SSR module 
...
ReferenceError: self is not defined
    at .../.pnpm/svelte-dnd-action@0.9.34_svelte@4.2.8/node_modules/svelte-dnd-action/dist/index.js:4:23
    at .../.pnpm/svelte-dnd-action@0.9.34_svelte@4.2.8/node_modules/svelte-dnd-action/dist/index.js:5:2
    at instantiateModule 
```

**Comment by isaacHagoel** [comment]
How did you encounter this? By upgrading sveltekit? Was it working with the
previous version of sveltekit (or the lib)? Which line is it complaining
about (can you click into it)?
In general SSR should ignore the lib altogether

**Comment by Rar9** [comment]
+1 getting the same  [vite] Error when evaluating SSR module 
ReferenceError: self is not defined

**Comment by Rar9** [comment]
down grading from 0.9.34 to 0.9.33 helps but gives this warning

[vite-plugin-svelte] WARNING: The following packages have a svelte field in their package.json but no exports condition for svelte.

svelte-dnd-action@0.9.33

Please see https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#missing-exports-condition for details.

**Comment by isaacHagoel** [comment]
@Rar9 yeah that's the warning 0.9.34 was supposed to fix. checking what this new error is about

**Comment by isaacHagoel** [comment]
I don't have time to get to the bottom of this now (hopefully tomorrow). The lib itself doesn't use "self" (it does use "window" quite a lot) so this error has to do with the code that rollup adds (the irony :)) as can be seen [here](https://www.unpkg.com/browse/svelte-dnd-action@0.9.34/dist/index.js). Version 0.9.33 has that too, see [here](https://www.unpkg.com/browse/svelte-dnd-action@0.9.33/dist/index.js) so I am not sure why it doesn't trigger the same error. This wasn't a problem with Sveltekit 1 so very strange indeed. 
This means that changes to the library code will not solve the issue. It has to be something in the rollup config or the exports config or god knows what. 
I followed the advice on the link with 0.9.34 thinking it is a quick fix but looks like I was wrong. 
Use 0.9.33 for now. It has all the latest feature. 

I will try to make some time for this tomorrow. If anyone knows the solution please do let me know :)

**Comment by isaacHagoel** [comment]
okay, it was a silly mistake i made. please used 0.9.35

**Comment by Rar9** [comment]
your new updated works, iconify/svelte has the same  issue ReferenceError ... what did u change?

**Comment by isaacHagoel** [comment]
I added this to package.json:
```
"exports": {
        ".": {
            "svelte": "./src/index.js"
        }
    },
```
Notice that it should point to `src` not `dist`, exactly like the top level "svelte" entry in package.json
