### ISSUE TITLE
Scrolling with nested dnd zones not working

### ISSUE THREAD

**Issue by abramovic-nenad** [isaacHagoel/svelte-dnd-action#535]
Hello, 

I tried to implement [Crazy nesting example](https://svelte.dev/repl/fe8c9eca04f9417a94a8b6041df77139?version=3.59.2) with fixed height for **node 1** item. Here is [updated example](https://svelte.dev/repl/42c8de54648c41c1a7f605cb201bcd97?version=4.2.8) with fixed height for **node 1** item and a few more items. When I try to drag an item the auto scroll is not working. When the center of an item is dragged to the edge of the outermost dnd zone near the right side (empty space on the right side of the inner dnd zones) then the auto scroll is working.

Is this expected behaviour or should the auto scroll occur when the user drags an item to the top or bottom edge of the outermost dnd zone? 

With [this workaround](https://github.com/isaacHagoel/svelte-dnd-action/issues/311#issuecomment-1557424908) I was able to enable auto scroll.

**Comment by isaacHagoel** [comment]
this should work out of the box. It is being worked on (admittedly slowly) in #506

**Comment by abramovic-nenad** [comment]
Thanks for the info.

**Comment by dusty-phillips** [comment]
Following up on discussion from #506, here is a repro:

https://svelte.dev/repl/4675f90eca4b46f5a914b0d0f1f5b90f?version=4.2.12

As summarized in the repro, it scrolls correctly in safari, but not in chrome.

There is a comment in [this recipe](https://svelte.dev/repl/288f827275db4054b23c437a572234f6?version=3.38.2) that suggests the overflow-y must be on the dnd container itself.

However, I have legitimate reasons to want it on an outer container, and even if I move the class="scroll-container" to the section that has the dndzone, it still doesn't work on chrome.

**Comment by isaacHagoel** [comment]
@abramovic-nenad i created #549, it is still WIP but you can test it if you'd like.
