### ISSUE TITLE
Items is not reactive (possible svelte 5 issue)

### ISSUE THREAD

**Issue by isaacfink** [isaacHagoel/svelte-dnd-action#541]
I have a list of items that I am passing in like this

```
<script lang="ts">
	import { Trash } from 'lucide-svelte';
	import { dndzone } from 'svelte-dnd-action';
	import { flip } from 'svelte/animate';

	let { items } = $props<{ items: { id: number; url: string }[] }>();

	function handleDndConsider(e: CustomEvent<{ items: { id: number; url: string }[] }>) {
		items = e.detail.items;
	}
	function handleDndFinalize(e: CustomEvent<{ items: { id: number; url: string }[] }>) {
		items = e.detail.items;
	}

	function removeItem(id: number) {
		items = items.filter((item) => item.id !== id);
	}
</script>

<div
	class="grid grid-cols-4 mt-3 gap-1"
	use:dndzone={{ items, flipDurationMs: 300 }}
	on:consider={handleDndConsider}
	on:finalize={handleDndFinalize}
>
	{#each items as item, i (item.id)}
		<div animate:flip={{ duration: 300 }} class="group relative">
			<img src={item.url} alt="" class="w-full aspect-square rounded-md" />
			<button
				on:click={() => removeItem(item.id)}
				class="absolute hidden group-hover:flex w-6 h-6 text-red-700 p-1 hover:bg-red-300/50 transition-all bg-white/50 rounded-full items-center justify-center bottom-1 right-1"
			>
				<Trash />
			</button>
		</div>
	{/each}
</div>

```

The remove button works as expected but when I add more items from outside the component (in the component using it) the list is not updated, the new items get added to the dom but they are not draggable and when I drag other elements (that were there previously) I lose the new ones, I am assuming this is because the `event.details.items` is still the old one, I tried adding a key but it didn't help

This might just be a svelte 5 thing but I am not sure

**Comment by isaacHagoel** [comment]
Hi,
How do you add the items?
Any chance you make an example using the svelte 5 playground?

**Comment by isaacfink** [comment]
I am adding them by pushing to an array, this array is passed to the component above as items, I'll try to create a repro soon

**Comment by isaacHagoel** [comment]
Thanks. I wonder if the same happens if you add in the old svelte way -
items= [...items, new item]

**Comment by isaacfink** [comment]
Here is a repl with a repro, there are some styles you can ignore, there are two lists, one is a list of buttons that when clicked should add the image to the first list, the first list is sortable and has a button to remove items, removing works fine (even though I am mutating the list) but adding adds the item but doesn't make it draggable 
https://svelte-5-preview.vercel.app/#H4sIAAAAAAAAE-07a2_jOJJ_pc59iyQNy7acOGmrkz4MemZwA3TPLrZnP40aF0qkbU5TpJakkjhB_vuhSErWK3Hv4e7TDabl2KwqqljvIjlPkw0XzEyS358mkhRskkx-KMvJdGL3Jf4wd0xYNplOjKp0jiPXJte8tB9SmVpelEpb-FGT7ZZkgn3ixsJGqwJOZvNmdOYnOUkl0ghmgVDK6C8F2TIDN_DvxhLLTn9HaGqfgNME4ilUWiRwsrO2NMl8XvLcVMWs3CmrzHy5WOBzAs_TNtXyGFWMT5_q_BjVEp8-1cUxqnN8-lSrY1QX-PSpLo9RrfA5gWck-nr2PpVOykK8KuOrY7Ne4tPn5d0xqit8-lTrY1Tv8OlTxYtjZGt8BmTHrCde4DMgO2Y-cYzPgOyY_cRLfAZkxwwoPsdnQHbMguILfAZkx0woXuEzIDtmI_ElPgOyY0YSX-EzIDtmJfE7fAZef8xK4jU-bfdI7aaSueVKYiz6jRWlQPew4csZPPkX8A2ctoLVbMMlPT21Z3DzAeyMU7i5uYGaasbpWUOZWs1speV7__MZmDDsAGxPWlZmd3h1TYB_nlN5PW_i7XU3zmZc0oRbVpibp9Z0zzDH2CyvKb-DXBBjbtJJYaNVOvlQvx3_uy4b6EZJGxWM8qoAyx5sZIp08uEHIZqlmet52aH2sbyZq_2ureYU8CPKlTDRCrakjJa9t6f26Q0j-a4VpIhpXvfcRU3tdVZZq2R_OLWUGxQI7YhgZlTBXlXT4AWpVTLJBc-_3TydOrpRuxihq5dNTMlyG5l_VkQzuI82lRCgVSUpo1FBQd0xvRHqPtpxSpmEHQ4k2TYyOHO0XCzAaiINR6tE0SltoF5eokqSc7uPVot00ufhw5Cpa15swej85qlZdaXFMxBhb9JJOmmUpbI_kOscmYGdZ9rznk68IXXnnXtF9HWZoHUPtXYwMW9WbqUrXKm3Mv83Z9IyDbkSkSmJdJb6qzrYHmxQigMLtE9ztKDOW6_nlN-10PzvyXRSKMo3nNFJYnXFnqdNtdP41L9Y8zzBb5qYHTyHekdUOacsCqXO-w4mlfRRSdbgeqSIShoRF4R6-BvByx7ynEhekDBzqKKewHk_PGN-L7UqzelZADfRbUckFexHST8qaThl-rQV3Bz1DbAZZZZwMXMD70PgGZvkZy6J4I_s-ydpT6NZoe7YL5YVp5wOJnB_ZxsuLNOnp_jLuSF-QQ_-t5sb4PTs_TAs-lCH4y9EoAsobHTuwlDsvacyLAlKuXkKYpw6sf9YaYLMfjYJnC8W8OwkgbEhyO_maSDSGmUTpNNCqQX2nHqXCUHPr5kY92UKHE7DMusA4wJqUHmCfCGbNPBWc9aKuKoqQTNBLL9jrUh7CANu_vEQEEJVN34dAlcnDgzicD9qtnXcXVInVmZGicoyCLHQLSDyEXEj2APcR5ewiy59fNCMRleLBZRRfIiaOHi-WMxXnbBJhIBsG93vuGUIqpfhVuikXkebPypj-WZf_8yUtaqIYtB8u7O1nfSi67V3-ZY4uuHwEH2a0NQMyWtj94J9SOXbaSqTJGMbpZn7SjbIwVMqATL1EBn-yOU2gUxpynSUqYf3CJq_hRjezj2Wg9xzancJLGrwsgt270vAKMHpCyguyyTwhq3YFcu6SM57X-Iziux9lCtpmbQJnGBUcvjzt6mMZ_APw4CAcxmDKGCYNDwTDASXLNoxFDJwCU5fWt0bps0slcsZ_E2zO6QgFDVUMGkNqA1giQKGPzLwXCjNmbTOHSDfEYkFBJfA__pllsrzmoNCoSkzQjHAgyWZm2KWyguPYXcMKsP0iUFmN3xbaUbh1hBpbt0row0puNhDtgfKNqQSdpbK1XcTM2IrzSLDrOVya7rTXH7vNHdEc7fSFya6msGPvk4AS0rY8e1OoIANKCeRVKI-U7mzhUBF7pSxXo0tbSQQz1Z9Q4vuWfaN28ina_7IIq8W7MwWf-kbVVSox8iSzGEmcFHDzwP8FVBL1glUPMLVR4ZpvpmC2RvLiqjiU2gPp7hRIRh8RBuGnwr1B08nOPyFbRWDf_wyOvZlX2RK-MFflVVd8pqtiw5bPS0mIJUuiKiRV23koa766Jd92ZIyalRWe6QLaSXRTNqa7urglcHL_u5irTOggugtmv-YR_0id0xz23E9V1rcokHcglHO_gzkRIJhFicsMDkRnyKAcs1yK_ZoTviyQMcEQ_ec1eaVKbr3ZuW5aUWm2p469sY9XyNRJ6zvB0rd-3KlkQE4hI2fuWYb9eDX9zGAETXMSWTOMGr4MAdOqG06OK07xazaPnIhyKxQ_q_S27nZqfv_yqrtLN_y_-D0Jl4vLlerMxdYfpKm0gx2SvNHJS0RoCuB3YtmcMd9kOt4Z_C9EDjrxQ9EExQ_KpQmXltV1lE_Lh-6TtRIri82dF6gLFe-ekA5fNxpVbAp_ES3bApEUvhCNkTzhl2SZTq53zHNTn-33Ar29czz7yLBYbIEML9q1CtQZS2j7UzQMtAgj3YclxTugzUqDTtGKLrLQWLxNJW7JX6c48cFfqzw49Kz4vzNx5O21Nzw_cDGWkyhjQsuvxmwClRpeYH8IBOqtBGXgJmTyy1waSwjFC0JIao66JN4Hka0NpDQCA99FTmp3DfmjWoZ00o2TaWxWsltSwL1UjMlKNMjifiFBFMoqV5JcsvvJn41yZ1_7zTHktxF19EVpXDLitvGoLy--uHPyy1XFCuYbxlFAZKinKay1KwlxFbqQZ5MSXI2hS8_f1ZSRX9n20oQPYXPTAo1hc9KklxNAet_JYjBXPKJZyz4F9L4BPNRVZozDb-yexxoZu77_nelmeW_lmY6mdV7ScyKboJ73R6dl74kUlPgcN8P37mioJm2ruVuTZXdOoO-NVXZZA7j0xDZbFiOa3AsuFDyYoEYXl45T6jKAQNXK1-VdBKNj7Wl8j1C0jRKbviOactzIiIi-FYmkBHDkLpeh6myujTHDiGBaDFbrpwkAzxwYVXpgC1YL09jHOaSNnWrW711dVsopc0hOLf9v5OuzCxHBF4VLleV8_rnnBtTMTP3fTjmrfV6vXj3bgodal92jOa55SJerq_OulnV8ddLpIckG1T0v8jz-epquf5-nuP1ahFf-twcBL0lpYGM2XvGZId_M5aZPcIhuXkNjWTobs_0eqLOlRCkNCyB-tsLyTqewUfXvjjj936HfZsZr-VGS75Q1XQzxkEcdeotCaWvRUnfyk5TyWVZ2WkqVWldY46-xgTLcQxFRDQjI7GzJ5Ejwe017LHo9hp-CG-tlqQDHhYD312Uvl6d1dBBvVtbQxB5C9JTf0ufvdLVRQvXBmyULjpVwaH67SnOa6llyw09ZodDTKsNr1M4k4wLbvdYEzkLBLev47vKfdm0110rWw6szDMTjHjI4u84182J_33y9TCisSxrD5gqK7g9-Ro2HEK3RMqSEY1CSsKrBm5K8m9bt-_zSjO1HCJzPDpo5DTWktSFTKEo0we326i8MkFmWESic7kxJ7s61zWiSFyb7BA0rys5VVk0wwRIZdULJTTaEjoFEXCbcHlHBKe3rWgxbG623O6qbJarYh7am_mW5d9URNndPBMqmy83a0ZyuqbndL1e5evzq-xiuYrJarW6ousVvVhf5OuMxXNB9qqyc_e2uWZmjlZlZrkxbz5dLd9Fn67OMXG0l1jxKHDZ2tvaEaruh9bYL0DqrAwuK6MAe5mx7wOlVlvNjPGvOpbU8ZVt688rbZQOOlQb4DLXTm3uXZTVv7zFOWn3SvMkqS2US4mbbyWXUWP1B6iqbBfabQv76o-HVe_BA8aLhUFPHGwrrG7Ieu1vjOh895q_YUjZcCZo3-XCGyK12RhmE4iWh-Z0-UrAk0y3s9JgLbjhUJDc7en1xezZbTVaL_P9fxb6QuZ2WRvPX9DqmOsqb0M0v33VVPDqTVSVQhHasYbvD3b46mM7KX3fotyUguxfsp66xC4KosN-TqBIQHBjI9xGH4Yo02nzsc1BreLMoXZ0obFEMWFyHwmMmVD5t39WymKvRnGnkmK_9so-AH7oaRr6SWzq2o1dOys7Zp3tYvM_sknVydQOW7AtkyF0DaEK-avwo2CyqndTja133Zs0cuw1hy2JRnZh9wEFRjkRqrUp4n-_xFS759IsNMV1xWZae1b9Zj9Uwp3azk3AkiaWDpqasFV4qC8FydnO7UJAOK4-mpaw6r_nkgqSmeZHbkzdF5yfLxa-H_nyytt8W2LVC9sMW032cLFYeLxmua7MTZLWRK36tjMecrRfUwLxC9Xhm3VOzsnmBTfsLyDkHNRySCsj1ZJWgt2kk3DqNgnB2ZMmUCqOh1dtzXwm3xi4Hcr66kCTtKiSJxa2gY1AG-Y6BKeGrPOmwHTPBtzLNHOSooeu_raJF86lb9u29lJxQtmdmefGYKKl-1r98YVXPoaw235SLzilgt2i3t3ICCfu_CecPe2PsvEHIhaFkqOcvHHfclXg1NHl-cX6_GIZo3UCwG877vfPrebbLdNAoFRKiz3U58aMYqNhgWnt96LxjgpYpYRBDQHHLJOLiqLGkFHDt_Jgq8UW6_s7_LzjlKlpKnMi74iZppJUlOMA32hSYBhkRcYwdPrLHb0Y7nTSt-Bx2b5gybjvZTXBpBhu7kgKjitTO6GvtsHtVTtwifW99pmf4_qt5tLwPBw7g8vh_xPraMvH8VBH94dmp7zuC8eLLG_Fjcncc7tzS_jP3z5_qs-nibWaZ3hgbSzZ16MHe4JQSXnA157E2_XH2yk0Z6oQjlQPJ6r1ya3PntFDnTbGgPsO0PU47nrNwwvjXXyt8D5oZ8h8Y_c9ajfUJTQ5Ee4lcX9s3xnDizwPCUB3ZN8d4TLfRY8Kt9WgPZ1WQkRGkjIyVvPcSmZMgiXWAy-43R9Qt5pQPAiOcC8tOmzxwQjKHSdHMKwaR1Ca4j2OLpOCmB2j0SPTqgOQVcE0zyOffUZBQYXjZNpfCeoAsVGMuHTFdX_YF93NZYBQeQ_gdY7abDY9hADR2-x0tYb4fAHLi0uYw2K2Ohufq-7iFrCAN4vFYtFDewV-FOTZYXQUJROV7kggc9c1vHm0hnE7VRNj-2reO0vtjO4q1jhDa5hLDIldjeMWVh_PsJKTzgjVqmyW2WaV5N8cbLiIBjK-mgY-uqwGOr6-BvzCQhv4yIobWFP6jAFH5XKABgEdLpQEyJ9R78-o92fU-zPq_X-IerP6wqNv3Btvq4drtPpksofW3OwMaPVlxc65JB5LalY0U_l7jL6VD-egXQy8FNvaCYncAeZidtXGwUu03WIWR2qoL3eHxW6z6vaVUocWRly1n0AMc4ibyaLLzlZoPGszch-gdU3fA-L9zg58sfhLew3hIrBDcb_ry-UIqAppUMglI_b0YgoFlwV5OF1MId7os7N6nvb1Ub8Y7JXcdphJwI_XuN3bpQ67GapvTXYp3O1kzx8ph9ps3WMNWndpEWN4ZRJYr9fr8qGPXdAx3MXsvKPj-r5sms5XC08wOELBMLlcraB-fJysZ6g5P-xIdblv3-I9pH032ttUab0ufreC5Tv8N4c7ok8HNAfNdC8A--Ovw1DYmd0neDLzvgfEyz9yG9V31BPIq4znUcYeOdOni9nFFBZTXM8U4rM-8eFCdrxaFKaxZLyjnKatW8pOtIkbf1XAS4gvV-7pCtgdw3p6mLUuS6epuy7d9UAcCYTX_sBm5H-A-Pr839jrDeD6OQAA

**Comment by isaacfink** [comment]
I tried changing 
```
addedTemplates.push(template);
```
to 
```
addedTemplates = [...addedTemplates, template];
```
And it works fine, looks like it's a svelte 5 issue related to proxies

**Comment by isaacfink** [comment]
Looks like svelte 5 doesn't call action update method when mutating arrays, this repl show it
https://svelte-5-preview.vercel.app/#H4sIAAAAAAAAE21SUW-DIBD-K4QtqSamvjtrssf9htoHJqclUyBwNGsM_30BtLZdIdGPu-_uO-6YaS9GsLQ6zlSyCWhFP7WmBcWrDgd7gRGBFtQqZ7pgqW1nhMamlS2OgEQgTJYcyLtFhpAdT3krg693skOhJDEwCItgvhCmLLDzOfhb7JS0aoT9qIZkD2afouFXK4PkloTFXyYVhyJJ5mRuJSGEpK8BdEautrCc5gyhWgtsyCKb9r34blC40Hf5liCsXhmSBW66KFH9ov6QLOz_13xk-C2xLzbMwaJR14pk-VLjvfxdTIL-o5X-qcGM8yi61hQL3Gtnz1mCI8gBz7f23o9mUhd4Fax0tvLrcpu4rL8dopJEyaobRfdzmBd13zDOY2_qMnGaV-xN0TcJP8e0cn4D1p2XuTEbQay75uLSzPFYlwEH41wGduxJ8BNnoUqv5RCp1jeJTAs6KS56AZxWaBz4k_8DNgxI-v8CAAA=

**Comment by isaacHagoel** [comment]
Thanks for investigating this.
I'll keep an eye on it when svelte 5 gets its official release.
