### ISSUE TITLE
Duplicate items when interacting with an asynchronous server (optimistic updates)

### ISSUE THREAD

**Issue by quangthandev** [isaacHagoel/svelte-dnd-action#543]
The bug is taken from this example link: [Interaction (save/get items) with an asynchronous server](https://svelte.dev/repl/964fdac31cb9496da9ded35002300abb?version=3).

When user drops an item and quickly starts dragging another item, the updated items from previous failed response from server will cause duplicate items. Maybe the application code could do some workarounds, but I think it should be handled by the library?

![Kapture 2024-02-23 at 14 58 31](https://github.com/isaacHagoel/svelte-dnd-action/assets/66868281/ad9b2d69-e307-4c41-befe-7fff54ea0496)

**Comment by isaacHagoel** [comment]
Great catch! This looks like a bug in the example. It doesn't take into account that a new drag might be ongoing when the drop fails on the server. I see two possible solutions: preventing a new drag until we here back from the server or adding logic to the catch handle to recover gracefully somehow.
It sounds like you have an idea for how the library can handle this... can you share?

**Comment by quangthandev** [comment]
At the moment my only idea is somehow the library can handle the duplicate items issue internally. I caught this bug when trying to learn SvelteKit by building a Trello clone. If we prevent a new drag until we get response from the server, we cannot achieve similar optimistic updates effect like Trello :).

Anyways I'll do some more research on this and get back to you.

**Comment by isaacHagoel** [comment]
I happened to have read about how Trello does it not long ago (see [here](https://www.atlassian.com/engineering/syncing-changes)).
I don't think the lib can or should have knowledge of any of that. It just accepts the items from the consumer.
I think this broke in one of the PRs I merged quite recently in which the id of the shadow item remains a temp id throughout the drag (it used to have the id of the original item with the exception of the first frame when drag starts).
I added a fix to the REPL. Let me know if it makes sense. 
In reality, in a collaborative app there will be way more completed syncing happening.

**Comment by quangthandev** [comment]
Thanks for sharing your knowledge about this, it makes more sense to me now. I agree that the lib should just accept the items from the consumer, and the application code should handle race condition with asynchronous server like in this case.

By the way your updated REPL does not work because the `shadowItem` is always `undefined`. I think you need to send the updated items on `consider` events up to the `App` component like [this](https://svelte.dev/repl/87998012660442bb8210dea530bf2dc9?version=4.2.12).

**Comment by isaacHagoel** [comment]
Hi,
Yeah you are right. I did it in a rush (something one should never do) and wasn't thinking this through.
What threw me off is that on my machine, at least after the "fix" it doesn't manifest as duplicate items (even though the shadow item is indeed undefined).

https://github.com/isaacHagoel/svelte-dnd-action/assets/20507787/bbaea891-c92a-474a-ac67-fec013056a32

Regardless, you are are right of course.
WIth that said updating the top level items on every consider event beats the purpose of this example, which is to demonstrate how the transient items states can be encapsulated within the List component. You never want them to override the server (source of truth) state altogether.
I don't want to repeat the same mistake twice so I'll give it some thought and update again.

**Comment by isaacHagoel** [comment]
Alright. I think this fix makes sense: https://svelte.dev/repl/d15442c786d845fc9fdd4c63ff5dfcf1?version=3.59.2 
I moved the concern of thing happening mid drag to the List component to keep the responsibility of dealing with transient states there. Still working on this under unideal conditions but I checked more thoroughly this time :)
Please have a look.

**Comment by quangthandev** [comment]
yeah this fix makes more sense to me because assigning new value to a prop like in the old REPL breaks my mental model :)

**Comment by isaacHagoel** [comment]
thanks. updated the in the original link with a tiny modification - when server save succeeds it doesn't update "server items" because the list is optimistically updating. again, this is just a silly demo. a real implementation will need to be more complicated.
