### ISSUE TITLE
Distinguish between "dropped in same zone" and "dropped in another zone"

### ISSUE THREAD

**Issue by dusty-phillips** [isaacHagoel/svelte-dnd-action#545]
I am doing a fairly simple nested drag and drop operation. It's virtually identical to https://svelte.dev/repl/288f827275db4054b23c437a572234f6?version=3.38.2

Using the terminology from that example, when I drag a card from one column to another, the `onFinalUpdate()` callback gets called twice. Once with a 'droppedIntoZone' trigger to update the list of items in the column that had an item added, and a second time with a 'droppedIntoAnother' trigger to update list of items in the column that had one removed.

My issue is: I only want to save my changed array to the database (IndexedDB, in my case) after both of those have executed (Otherwise I get some mildly irritating flicker). A solution would be to not write to the database if the trigger is `droppedIntoZone`, and only write on `droppedIntoAnother`, which is always called second.

But  if I drag the item within the same column, I only get one `droppedIntoZone` event, so in that case, I *do* want to save in `droppedIntoZone`.

I can't find any way to distinguish between "I am dropping in the same zone" and "I was dropped from a different zone".

Some possible solutions:
* Have a new 'droppedIntoDifferentZone' trigger that is distinct from 'droppedIntoZone'
* Fire 'droppedIntoZone' *after* droppedIntoAnother, so that the save can always happen during `droppedIntoZone, since it will be the last event either way.
* Add some state to DndEvent that links to the "other" (droppedIntoAnother) event if more than one will be fired.

All of these require changes to svelte-dnd-action, though, so I'm wondering if there is something I can do in my own code to make this distinction. Alternatively, I'm happy to put up a PR with any of the above fixes if it would be welcome.

**Comment by isaacHagoel** [comment]
One idea that pops to mind is to make a new store and when a consider
handler is called with a drag started trigger, update the store with the
identity of the origin zone (the one updating it). On drop you could
compare the zone that receives the event with the one in the store and
clear the store. Would that work?

**Comment by dusty-phillips** [comment]
Seems to work perfectly, thanks!

**Comment by isaacHagoel** [comment]
I'm glad to hear. Closing this for now.
