### ISSUE TITLE
docs for meanings of different triggers

### ISSUE THREAD

**Issue by tomconnors** [isaacHagoel/svelte-dnd-action#546]
I'm trying to make a somewhat complicated dnd UI and I suspect I'll need to check the trigger in on:consider to decide what to do. Is the exact meaning of each of the triggers documented anywhere?

**Comment by isaacHagoel** [comment]
The readme specifies which triggers exist and I believe their names express
what they are. If you have any questions about them please ask.

**Comment by isaacHagoel** [comment]
closing this due to lack of response. feel free to re-open
