### ISSUE TITLE
Spammed warnings: [Violation] Added non-passive event listener to a scroll-blocking <some> event.

### ISSUE THREAD

**Issue by dBaliukynas** [isaacHagoel/svelte-dnd-action#547]
This warning is being spammed every time when interacting with elements in the dropzone.

![image](https://github.com/isaacHagoel/svelte-dnd-action/assets/77122119/03d51498-2771-4fff-9427-d756f55d8e57)

**Comment by isaacHagoel** [comment]
The non passive listeners are added in order to allow dragging on touch screens without it activating scrolling.
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener#passive
