### ISSUE TITLE
🚮 How to gracefully delete/remove items. 

### ISSUE THREAD

**Issue by SrGeneroso** [isaacHagoel/svelte-dnd-action#548]
![brave_pqnbhuLhOk](https://github.com/isaacHagoel/svelte-dnd-action/assets/5541794/8554440c-d44b-4a2a-84a2-986670c06855)
I want to make a zone where items get deleted on drop. I've being hacking around but most likely I'm doing it not cleanly.
What would be the proper way of doing it?
Adding a REPL to the examples would be awesome.

**Comment by isaacHagoel** [comment]
Basically all you need to do is make the "bin" dropzone such that its "consider" and "finalize" handlers just assign an empty list to `items` whenever they are triggered. Did you try that?

**Comment by isaacHagoel** [comment]
Items =[] shouldn't throw. The id check only happens for elements in the
list

**Comment by SrGeneroso** [comment]
Alright!, that does it! I'm going to go a little further and maybe do a REPL of it, thanks!
```js
	function handleDndConsider(e) {
		items = e.detail.items
	}
	function handleDndFinalize(e) {
		items = []
	}
```
