### ISSUE TITLE
Nested items don't work

### ISSUE THREAD

**Issue by hvven** [isaacHagoel/svelte-dnd-action#558]
[Here](https://www.sveltelab.dev/?files=.%2Fsrc%2Froutes%2F%2Bpage.svelte%2C.%2Fsrc%2Froutes%2FBranch.svelte#code=N4IgdA5glgLlEDsD2AnApiAXKAZlANhtiAMZIIxoUDOWoA1lAgCZYjUBua%2Bl%2BAhgCMAtAFcoADj4gANCAEicONCiwBtACwA2aZvHTxAZmkBOAKz6jARkvbrl6dfUOADPcvOH7z2%2Bcf39sxdjbxc-SwB2Fz1-T3MvdUjjaIiXOOdo3xdpBOzbSzjLDJ9k21dstMj3AtLsyssAJhNE4PdEyucrMvjSty9rDNyXXrC9LWzGrwMjMZjrEcHZ%2Bo9jdpaGqKGs-tTPHsHjNeGXCec06dK88xmbHfcWrvzdpqDPRvUrk88M6s2xg5C5sdbh0FjdrFc8qU0vdej8Vi9rG8Pi4ALoAXwxsjAAAd0DA4MoUCQ6CA8IQSWQKFQYLRiIwWGxONxeIJRBIpLJ5IplGoGp0TNIDE5rHU0vZxE54UlYoKnKY9AYJmDLMKUjF1MLlrKZVVPH4Qe4ivpenVenshdJ5YKlXlVe17BqssELdZbc9dYbbn0QZpTQjnMF4RarYrtYC7HrNhbHV5naqlZqCmFtOJ2mlky4nMGFW9gupRqNNQKXetPSKXJ0kzLs9aTPYSwnNq6nh6Hk53q8NuX3JXIx3wV8m%2BkW2ULcZpkW452y2qDadI4ZNvDHCZ7k5dF7VeYa6HjPX29oxxOnWHrIPZirPInQk3HjvGnuHPUjKGXc4TmkjQP79r1G9LueXTDs2MTRlmjQlr0Npekc35yjmT4vhB8bupeA4Xlm8G1iWBRfsBYKjuBT7bhM9TmOOWxkaiGJorI2J8CQ9B8BAaBgAAVtQ5AkmSRCgJSlA0CS9KsJg7BcDw3CsmIkgyHIChKComCqHyJ4lssqxRlhr6Snoy6PLq-xgapqpfmh%2BnzhGgI-tGozaPmgzqFOMZag2V5erpdTmlp0Ert2ZTOcWW6rm5Hqlsq27eYhJ5Tu4%2Bq9AqkUlt8I71iccWDkZsaBSYyRpl2mTWSZXrmg%2BuXAhkHiZVqMVhZq8XAr0U4hshgE-KBSqNheyUXk5k7ZWWFl9DchXTmhDyQg1bmhh2-alvh7S9oCs1iqhkpruUN6hURYzTVc5HrTE-ytLWO3tn1MXvgCY2Bp52rNaenXjSOK0rrtG2Il2s6LfEBQrXpa2Zu9mRbSdh5Iu9lhrNeIGjv%2BYZag0Vx9W%2B6XbBuF4nLBwMPMs9wvXekUqVlU6aEF2yzPhezuABOTLpkek%2BW2G16bdEYjcYcoOnZtnZAl2TndqpM6oUQ4lEONPtHlzbs3KHhjPZ8t8wFgaC2TIsU2LFMS61KUQycZU9l6cu-YBxS6zLlpc7zDlKwLrm%2BU9MP45hloIWOsuDKYdnc7%2BdsoQ7ZrPbe7YFPrngLUbEO4aL5uJZKHvy3mPOOb70WntHGux672Hx5acMK9opgvmdac4abn17P2wPesbzxHQRBRHBbBeWpEYymI0pj7vzpdFaFXnZ9pJhyuc1uK-DAqIz3WUlrY9RQZpg8tXcALV%2B0RpVf12MLxe%2Bqo7GeO3hFS9RcT6flzOlf7YDh33JEFtd57cOmC7WVT30VHuOimLsESJLMFAdAJAYCoAAJ4kj4NibEYAAAWMAAC2%2BBuIEF4qQcgAkaRCSYCJMSzJJLCGkhyOS3JFKqE0JVIwG5wjBF9PoJw4hgjiA8JoZ0JxVSlHuHoTQnxyE3wIpw2sno9L6kod3XegtPg0P1HVd0mRuFp14SvC82ggwPnWv9HUT1NBiLVARcGXttTTUiPIs%2BijgKDX1PfR6ZttHw2vpZSYRF3Cqhke4RotiLQGFFBfSmQ4pY3D%2BN49Cjs7xt3aA%2BOoyV65HGuEqERhi3jGMkQKMxMIniqMjHTNJHi%2B4WQeGsJUvR2EJOCg4jM4jmw5M8IfWKI51w%2BH3lEtJs0anV1KC7IxOhknOiCerICmsgL%2BO9jfModNKrtBSXLdoMixldJPLw6Ullgbz0EfTW68Jlo%2BIGT4IZesQr9JCLMqu6l0nGLEc4VU9UMISIUXvdygj9JghWQNewVTamhVDhsZcKz7rRMjDDWC4UbleOFnhbZLhdl-GSA0p89ZjFTM2oNLhyTeG02hZtFZJjmEIucSOARWLv60RAPgKAAh-6ALQMAsBJJsFoAAB7sVpLgFBFJ0HUiZSAYSjJxIsgIeyWSXIFJqByDkUMH0hHNCjCcD8%2BVYSCOeWecsYrIaoQzMqvIqVgQFKusU9VfDLnhwrIDPVuL2omEPKUKJukwayKid4sVFiHntK9CRIESyKrBwWM4QlP8UBIBEJQDlACgEgJQOA4gABqfgoD-UwDAEyCSyDyTEH4uyrBDJRIJt5WyGSnJ5I8iUoox49doZhW0FiyeeTtUON1RBPMdkI4zgCB5DYfw1gmwMMEUw9wdA4uLVDL00EK1eCLZ%2BK6NqcgEporICN9EWLxp5agnirKqSCTpNg7leD%2BB8tzcQoVhawj2LGp8ypyTWzVsVWZG1mg3TCNKRc1ZnVFUBmwvW2oOhb11FxoDa4GcDkAsFF2ntwGmxLFGkUp4u5Dj-MeTa8Mz70qhg8aRfkKtWweHuinZWAp-i-LcM%2BVZ6YT6mDlkRXDCFHxEzyRhhCj8p6OjFQRh1RH7od3leRJCxETCoa492rIqLvElsHU8Yd2KP1uTvUdB9jGrBDRhYsV1k6TiEtkAAIRQHwBAJAYELrwUm1Bqa10MA3Zmxd26c1EMFQWshh7SnHtGuWs9VbwMhWGih1ZYQ7kNEKf82GXGHVPp8KwwDoKY4AeOb52uUo1hQiupVIDWwEZdDA%2BKy9tbZWQbiavVGYmcgDiE6FIdnwR1hHce5%2BD8n-KxfeVRATnZh1MbSGkCCWWlnpTbdhUROhNXdhrkOGV4YgJ%2BE-lqMx%2Bo-04cNcE%2BwVp3l9e83FzYtiiZMYGwRILMp7oVcRVbQypE4gjcm2U7Ofz4NNZ225ZbBH1Dtc1bY%2BRMm05rDCJV3bwXkO-FKPvFRUthwzEGlTF9A4%2BNn3fodtDl6aNusdXTbq9RMbdaijd34d3XkteyJ57Ln3gpIZ61Vi7zY6Zjv%2B21IC7bsj4bSCk7pUUDB-Ulbi5VL2Lsdd3ParL01Mck5vOoSnT3e2IujsqtqzzzGvJ0RExF43fNGEw8kUilU3jy6fIr624qwPTS7f7DX64acq1HVs3Ws3zJmzcQ85n7yyhXdk8NxTST%2Bd1ct9HCtaHrv2jrgdcHAu8vY2d8Vt3wJ9vUR-hAfASABB8HwGAEg1AOXLpTWyoznKTO4IkuZwhAr82kONwahxcGCNZRmibY6HZpTRYhUDSKJHrYv0tCBovmi27kRbVJpvltK%2BaL0Kx%2Bve1G-Mxb3fDaKctsPuCaMOWhYToKjbttJO1sQW87ryeBvwS29l4Z84Nv1eR9kz%2BxPnu01p8H9zGPI-i%2BQdahX%2BZNfA%2BK8dkfjvzvGPLT79rwxzucoIIz9rKYSIBiF8zY95Rx37N4e4gF5wnymrmTj4v414lyhhsZsYL5ES-7t4AFL6F696r795gEl7mBFyQGj7QHP7V72Rv4oH77IE-4%2BzoEX4ChX4VAQxUwpYBJXBdoIRQHE777v7z7f6a5oFtyAHL5YHX5MGgYZj35Q4Oq74wEKzbRn4UGWjbiCEYGX4iGMGzTMESH4EzYcFEFcGwFsZyHUGCh8GdzmGmEU6qH0HqHgEwyuJA7%2BRsGEEyHP7D7Hj8EKwKE-6y4vgqF0F5i2F4F1JDjNL4FSFsJP7I7b5K7H6WiHhmEQFIH%2BFAGbLBH2GhG-A6EuFREYav5vCz6n6WE8G16Py0GpHF6b5Aw%2BbwaFxuzBDUIXxmSS7oR3h5jbTkR1AdQZZpEKqk4bY8E3r5RVjHThBtDBSLgNByoAYrzhAW5DR2RESdoWBDiyY%2BCariDmDhAvjtG1jiA%2BaLKXoapxGNENDDY%2BCdAxJESbE5RTYLGGrYY0LjG1GrRhZ-ZLENHS4rgZKLh3rfi7Gvg0LJC57UZ7FGB-FtFxHLHhAI4zimSxb-AZLhCmTu7LE8H5ZfoyhpFMytidwVF95Vw1H3FVzQbbb3TQlfGXhIl%2BjbZolOJA6Q5XSfLl4xB0Hvz6g6CahpJO7PCc6jQOGwlmS96nb4QQabJSYOFpIj4nIOwqGPZZQ55XSBzynVRD6VE364FVEzTsGrKuHI7GGH7FGFH2TlFpwMHgHr73pb4RF8IGEGmxFUH8H-4pFmlBFamgEsnunt6P5j5uGT6GmOkn7JFWEBE2HAHBGWmt4bSIF6F6ncHyFGk-55HFFCFnzmkRm37BEEE%2BnEH6n%2BkOmJFGFn6pmqnplekzEsF2TOE5l2n5m8FxGoEmkulplult4VnaGGGxm5FjwJmBnxH1nn4gaBHhnlnrYq5PD366G6ndn2kDkoEjwpnWEtCHbEzoo1Y9YF6qkilrmXjikHRk6bDSmvHHShnslcbei3Ftawryo8aRmD6Gy%2BSXqYm1Kl6kmiluRbYiwaL6mtk4Gelb4Oglk4Zvk7mExfl1Dti1zYltljlnETnOGDkngrwaIPmOpy6ez4GXEvCnmXTHbNiEmyKtLRA-IcHgVuQ-kjltm4WMn4VAU3TBRSaApVl2am5paQFkUrgUXQViGmoHnqgIVAXsk%2BrTrsAwB8BwDEjEDBqUqhrhq4B8AcBQCUg4gIAQD6YroYIcpcqmZbpST8p5okJqDPgtCUYML6AeDInSDhBuD8j1A1AeAOUOBGDbFWXuJ6D7HSCOVyzaBeW-iCieUBUeDGUOCmWMLmDBWQxuBmUNCRC%2BVTDmVWUpjrjBC%2BURWhWckBVpVRU0JOBBXLGRUOBmVCx5UmXZUZUlUhVlWaDmAVUFWFA5WZX5XpXVWNWlWFU0I1XSBZXtXlVdVNVVW5XagSh9VtX1UOCxWBWeBPAeWWWLi1XpXdVjWLVFXtiRDLUJbbDrUjWVU9Xw5WVdWRDWWTUIzrAwn6Dk6OWXhbWXVOBbX2BbXqBWC3UTWOVbUuUbgtXDVwVbU-X9W7V-VjUpAPXEXbV1VmWPjGDaC-WjVmXXWg3pXrDQ07VLUA1mWPwrJI1g0tBGCY0I0416BbVsYuXxW%2BR7X5VUS41lWU09WNHU1LWSikSlA42o3BAY0s2FWWjw1U3s1WCND1DuUC2eCyZ80WVQ3s3WCs3i17VvVc09UqR01FV83s217GCNDzVU34GdVbXiCvLq3-Uw2S0G2y1jWPXZCy5rXi2PBOBnUEE-X3Xs0-WVBgZ3XhUO1S23WW3tjM1G0K0tAe1G2NGm0GDJmNFMLjkqRjHG2w1u1G2ei%2B1R2s2linF-74GNBHX3UWQGD20%2B2W0FD%2B3I3R2x3zhbUsJKEJ0hXCiR0rh21PXe0F2G313XmGzLaPB8Z3XXau051d2N0Rh3Vnjx3SimAiGRBfVgY3Hx0fSq3l13Uvrt3Z2N2L4bgU0x091s1G1jDx3V7LHzyVAgrx2LgPWSpUQGDaBnXa1Zgmwz3PmWDFw6B11Y1m3T0r0P2-VxD9gg790qr5BcK1zx2aD33pW%2BUWWUINFcIE3s1DGQ0J3CWyBZqsSUh4AQCMrqUJ6rqYLroZqp7ZoZ4GX7rKTOapYQbSwtFrIOaeoBauYbaAkZWtFgq6zUxYnPGkOpZUy7mdF3HHHLFskIp-jjC1hCwgQKoI4qnQguaPl2TxY0OPJ0MzHODazHT9whaL5jC0J4W4V5K82KaJJOiklDQ-BQaLZm6ticYfZUaVq7JbabmTYipWKyIyllqeql51CsxnjKpYzEU9aPJdFiNXrVhKiNz%2Bh46ArdRmRYzcn3EDjokm5Sp8ITSpb4GjBhIV6KO-qG7hZfa3iJObRnj1xXBMP2OMxinsO9acPSo6q1gZIDTF4BI1Aqw2O1guVm6Ma9AmhTSCnzAgxqPhNqpraurbbEPCzeOEOuaA6q41ryotOGrC63hxNi43huORhs4PInqjKtIyp7a3gdODS57ejdMTlOKPI1I3ASkPKtMDMZFmqzIMz0O7m1P0FJOhiTFAR47FIgRhQJPvo%2B6QoATkz-pjn-aNLvpzYBDk60ztAFM3NBQUPjMOq6MyLMa%2BZElcmoTVaMlLOHFnNuZ2OoSFOuYQhPbgs4uQsnxXNDOwW7lyw%2BCTwrlUTcPiE%2BPpaW4%2BAtGzhiwGNqMDYggX4qYgCKWUDR7kCIPIPEDx58SJ7oPGaYNwPp76V7rWbnoMuZa07%2BNpOwVVGKOMZ9PUUgnBbLECPSNhZqvyPqsA5At9L9EhbcOiPDPiM3keb9aRwxCqM0XqNnDsaPqUMvDUO-MWtcM9rej4alblPnPbxAgswVz2sUxrbpTOtYycvTDDY8birzRGqhS2Z4ahaZyyOQqUvcaURXAlk%2BpAA) is a minimal SvelteLab reproduction.

if you drag "2" and release it doesn't work. 2 has 3 and 4 as items but if I drag 3 or 4 it works fine. I took some parts of the code from "Crazy nesting" though I don't know how to fix this.

**Comment by isaacHagoel** [comment]
i don't have time to do deep debugging now but there is a solution in place for nested scenarios that lead to problematic recursions. it's documented in the README (maybe not in the clearest way). In your case: 
```
<script>
	import { dndzone, SHADOW_ITEM_MARKER_PROPERTY_NAME } from 'svelte-dnd-action';

	export let node
</script>

<p>{node.id}</p>
{#if node.c !== undefined}
	<div
		use:dndzone={{ items: node.c }}
		on:consider={(e) => {
			node.c = e.detail.items;
		}}
		on:finalize={(e) => (node.c = e.detail.items)}
	>
		{#each node.c as n (n.id)}
			<div data-is-dnd-shadow-item-hint={n[SHADOW_ITEM_MARKER_PROPERTY_NAME]}>
				<svelte:self node={n} />
			</div>
		{/each}
	</div>
{/if}
```

**Comment by hvven** [comment]
That works though but that makes "4" not draggable individually.

**Comment by isaacHagoel** [comment]
works for me. what r u using?
https://github.com/isaacHagoel/svelte-dnd-action/assets/20507787/bd9f9798-92f5-444e-b10a-9a973cda171c

**Comment by hvven** [comment]
If I drag "2" first then "4" I can't drag "4"

**Comment by isaacHagoel** [comment]
sorry, i told u to look at the readme but didn't follow all the instructions myself (doing this while juggling some other stuff)
try this
<script>
	import { dndzone, SHADOW_ITEM_MARKER_PROPERTY_NAME } from 'svelte-dnd-action';

	export let node
</script>

<p>{node.id}</p>
{#if node.c !== undefined}
	<div
		use:dndzone={{ items: node.c }}
		on:consider={(e) => {
			node.c = e.detail.items;
			node = {...node};
		}}
		on:finalize={(e) => {
			node.c = e.detail.items; 
			node = {...node};
		}}
	>
		{#each node.c as n (`${n.id}${n[SHADOW_ITEM_MARKER_PROPERTY_NAME]? "_shadow" : ""}`)}
			<div data-is-dnd-shadow-item-hint={n[SHADOW_ITEM_MARKER_PROPERTY_NAME]}>
				<svelte:self node={n} />
			</div>
		{/each}
	</div>
 {/if}

**Comment by isaacHagoel** [comment]
no need for node = {...node} in the handlers, updating

**Comment by hvven** [comment]
Thanks a lot for helping me. I have 0 clue what is going on and I was stuck for several hours. Again thanks a lot, how do you even juggle other stuff with this... I'm just too dumb...

**Comment by isaacHagoel** [comment]
no worries. you are not dumb, these nested scenarios are not easy to reason about when you are not used to it.
let me know if you need any further assistance. closing this for now,
