### ISSUE TITLE
Nested DND vs Hidden elements

### ISSUE THREAD

**Issue by zeroed-tech** [isaacHagoel/svelte-dnd-action#561]
Hi,
Thanks for the great library!

I've run into a bit of a mixture of issues and I'm not sure if I'm doing something dumb or if somethings broken.

My dropzone is quite simple
```
<section
      class="space-y-2"
      use:dndzone={{ items: rule.rules, flipDurationMs: 300 }}
      on:consider={handleDndConsider}
      on:finalize={handleDndFinalize}
    >
```

I've got a similar setup to the [Crazy Nesting](https://svelte.dev/repl/fe8c9eca04f9417a94a8b6041df77139?version=3.59.2) example however when trying to drag a group of nodes, I'm encountering a "Maximum call stack size exceeded" exception.

Logging the contents of the items array passed into `handleConsider`, I can see there is a circular reference in that the dragged group appears to be getting added to itself all be it with an `isDndShadowItem` property added.
![image](https://github.com/isaacHagoel/svelte-dnd-action/assets/3313484/c7894742-739a-4117-aa6a-0a9473adc4a8)
This in turn results in svelte attempting to render an infinitly nested component. Interestingly, if I log the values passed to `handleDndConsider` in the Crazy Nesting example, I'm not seeing the isDndShadowItem value added

Theres a reference to shadow properties [here](https://github.com/isaacHagoel/svelte-dnd-action?tab=readme-ov-file#output) which talks about using `SHADOW_PLACEHOLDER_ITEM_ID` to filter out the item being dragged. I found this referenced in a similar issue here https://github.com/isaacHagoel/svelte-dnd-action/issues/307

To be clear, this does fix my issue  (e.g. `{#each rule.rules.filter((f) => f.id != SHADOW_PLACEHOLDER_ITEM_ID) as r (r.id)}`) however it creates the next issue, items appear to become hidden and never come back, for example, heres what my UI looks like before a drag
![image](https://github.com/isaacHagoel/svelte-dnd-action/assets/3313484/05a3e292-b99a-45f3-8f09-fa47173b70ca)
And after dragging the top row down slightly
![image](https://github.com/isaacHagoel/svelte-dnd-action/assets/3313484/bda667a5-624a-4b2c-8339-56691d71d845)

The same issue can be seen in this [REPL](https://svelte.dev/repl/d4c21245c79c48d28593e356a47a3c1f?version=3.42.1) which was referenced in the above issue (307). Just drag the red button at the top over the purple button and the purple button will be perminantly hidden.

I suspect the hidden issue is being caused by filtering out elements with an ID of `SHADOW_PLACEHOLDER_ITEM_ID` as this breaks the rule 

> The items in the list that is passed-in are in the same order as the children of the container (i.e the items are rendered in an #each block), and the container has no extra (and no fewer) children.

but that leaves me with a the problem that I can either have a drag element kill the page with an infinite loop, of I can have elements vanish.

Hopefully I've just done something stupid
Thanks

**Comment by isaacHagoel** [comment]
Hi,
The best solution for the endless recursion issue that happens in some nested scenarios (I suspect it happens do to the rendering, calling the action order in Svelte) is to use the hint as described in the README.
You can see an example that is probably clearer than the README in [this comment](https://github.com/isaacHagoel/svelte-dnd-action/issues/558#issuecomment-2053558283).
Please let me know if that helps.

**Comment by zeroed-tech** [comment]
Thanks Isaac, that works perfectly. Thanks for your help and this great library
