### ISSUE TITLE
Drop right when page/viewport scrolling will persist the scrolling

### ISSUE THREAD

**Issue by Acylation** [isaacHagoel/svelte-dnd-action#564]
Firstly thanks for your awesome package!

I've built a kanban board with svelte and dnd-action, however, sometimes when I scroll down with the dragged card and drop it quickly, the viewport would scroll all the way to the bottom, and preventing other normal scrolls.

After some investigation, the problem was narrowed. Here's the REPL link, adpat from the [Super basic, single list, with animation](https://svelte.dev/repl/3d544791e5c24fd4aa1eb983d749f776?version=3) sample. Hard to reproduce though, since we need to carefully place the dragged card at the edge of scrolling area and release it quickly. https://svelte.dev/repl/1004983c988540e29075fc7868e147ec?version=3.59.2

If the page got stuck, you can refresh to experience the problem again.

![Multiple](https://github.com/isaacHagoel/svelte-dnd-action/assets/73122375/5051e1da-c419-4614-8517-8f176fb872d4)

**Comment by isaacHagoel** [comment]
Interesting. Do you see any errors in the console?
which browser and which OS are you using?

**Comment by Acylation** [comment]
The console stays silence in default level but there are some messages logged in the `verbose` level only when initializing the page.

> 15[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>

This problem is observed on both Microsoft Edge (124.0.2478.51) and Chrome (124.0.6367.78) with the aforementioned REPL. My kanban board is built upon Obsidian, an electron based desktop app.

Operating system: Windows 10 Home China 10.0.19045

**Comment by marchellodev** [comment]
Also facing the same exact problem

**Comment by isaacHagoel** [comment]
I couldn't reproduce the issue. Can you please check with version 0.9.40
and let me know if it still happens (the scrolling logic changed in version
0.9.41 and I want to know if that change introduced the issue)?

**Comment by marchellodev** [comment]
@isaacHagoel thank you for such a quick response! 

In 0.9.40 there is no autoscroll when the dragged element is approaching the viewport border. hence, the issue does not exist in 0.9.40

0.9.40: 
https://github.com/isaacHagoel/svelte-dnd-action/assets/61112084/10a8bd15-9e62-44a4-93e4-e71da727f973


0.9.47 (the scroll bug can be observed near the end of the recording):

https://github.com/isaacHagoel/svelte-dnd-action/assets/61112084/48eb9434-aef2-4138-9223-73858fdc0083

**Comment by isaacHagoel** [comment]
Mmm... 0.9.40 does have scrolling when the item is near the edge of the
viewport, I wonder why it doesn't work in this case but let's focus on the
0.9.47 issue. Does it reproduce for you on a repl? If yes, can you include
a repl link?

**Comment by marchellodev** [comment]
@isaacHagoel The issue is reproducible in an original repl (by @Acylation): https://svelte.dev/repl/1004983c988540e29075fc7868e147ec?version=3.59.2

**Comment by Acylation** [comment]
Yes I confirm that in v0.9.40 I can't perform auto scroll. In v0.9.47 the problem is still there. An addtion, I tested the REPL with iOS safari and it will also show the problem.

**Comment by isaacHagoel** [comment]
Okay. I managed to reproduce it on my android phone (but I can't reprod on
desktop browsers). I will have a look

**Comment by isaacHagoel** [comment]
I deployed a fix and verified it on my phone. Please give version 0.9.48 a try and let me know if there are any issues.
Apologies for the delay.

**Comment by Acylation** [comment]
Yeah it works fine. I can feel the scrolling paused a little bit for each viewport length and no more stuck is found. Thanks for the fix and all the efforts for the wonderful package!
