### ISSUE TITLE
svelte version @5.0.0-next.140 breaks Svelte-dnd-action

### ISSUE THREAD

**Issue by lts20050703** [isaacHagoel/svelte-dnd-action#580]
I'm not sure if this is a regression in Svelte 5 (downgrading to version @5.0.0-next.139 make it work again) or if this is something you need to change to make it work with Svelte 5 again, so I'm making an issue here

(Copy pasted from the bug report I created in the svelte repo - https://github.com/sveltejs/svelte/issues/11769)

### Describe the bug

Svelte version @5.0.0-next.140 breaks svelte-dnd-action ([github repo](isaacHagoel/svelte-dnd-action), [npm](https://www.npmjs.com/package/svelte-dnd-action))

Downgrading to version @5.0.0-next-139 make it work again

### Reproduction

https://www.sveltelab.dev/vso69kln4n2plp8

The code is based on svelte-dnd-action's [basic example](https://github.com/isaacHagoel/svelte-dnd-action?tab=readme-ov-file#basic-example) with the following changes:
- the `items` variable is declared with `$state` to make it reactive like how it would in Svelte 4.
- `on:*` directives changed to `on*` properties

### Logs

```shell
chunk-SPBQG5KN.js?v=9ad32f8b:813 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'prev')
    at reconcile (chunk-SPBQG5KN.js?v=9ad32f8b:813:18)
    at chunk-SPBQG5KN.js?v=9ad32f8b:716:7
    at execute_reaction_fn (chunk-222NRIEF.js?v=9ad32f8b:1584:29)
    at execute_effect (chunk-222NRIEF.js?v=9ad32f8b:1705:20)
    at process_effects (chunk-222NRIEF.js?v=9ad32f8b:1824:13)
    at flush_queued_root_effects (chunk-222NRIEF.js?v=9ad32f8b:1744:9)
    at process_deferred (chunk-222NRIEF.js?v=9ad32f8b:1771:3)
```

### System Info

```shell
System:
    OS: Linux 6.5 KDE neon 6.0 6.0
    CPU: (8) x64 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
    Memory: 6.47 GB / 15.40 GB
    Container: Yes
    Shell: 3.7.1 - /usr/bin/fish
  Binaries:
    Node: 22.2.0 - ~/.local/share/nvm/v22.2.0/bin/node
    npm: 10.8.0 - ~/.local/share/nvm/v22.2.0/bin/npm
    pnpm: 8.15.3 - ~/.local/share/nvm/v22.2.0/bin/pnpm
    bun: 1.1.8 - ~/.bun/bin/bun
  Browsers:
    Brave Browser: 125.1.66.113
  npmPackages:
    svelte: ^5.0.0-next.140 => 5.0.0-next.140
```

### Severity

blocking an upgrade

**Comment by isaacHagoel** [comment]
I commented on the Svelte issue. It doesn't look like a lib thing. I'll keep watching

**Comment by lts20050703** [comment]
Svelte has reverted the change that breaks Svelte-dnd-action
