### ISSUE TITLE
Modify the dragged DOM element before it's being dragged

### ISSUE THREAD

**Issue by ivenuss** [isaacHagoel/svelte-dnd-action#581]
## The issue
When the column in the board is being dragged, it freezes at the point where it started and no longer rerenders to reactive states which can be inside that element. I get this is the functionality of how it works.

### How I would expect it to work
But if I want to have a scenario where I want to hide cards in the board while the column is being dragged, I simply don't know how to do that. I would expect `svetle-dnd-action` would provide some event like `beforedrag` which I can make all the DOM changes (hide the cards).

### Reproduction
Reproduction shows how dragged column (column **TODO**) doesn't hide the cards while it's being dragged.

https://svelte.dev/repl/038782190d3e4123aa0b7e54decb8736?version=3.59.2

**Comment by isaacHagoel** [comment]
Once drag starts the element is copied by the lib and isn't controlled by Svelte.
The library provides a 'transformDraggedElement' option. 
Another way to do this, if all you need is to change it when drag starts is to do it in your 'consider' handler. You could check for the trigger DRAG_STARTED, use a window.getElementById to get the dragged element and change whatever you need.

**Comment by ivenuss** [comment]
Thank you for your quick answer. I managed to solve it with the `transformDraggedElement` handler. I also tested the second option, but the dragged element doesn't seem to exist when trigger is `DRAG_STARTED` (unless I am doing it wrong). 

For anyone, who's facing the similar issue I am posting my solution: 

### Transform dragged element variant transform
Working example can be found here: https://svelte.dev/repl/6457a93531854358ae2147981537d54c?version=3.59.2
```ts
// This is a handle function called by `transformDraggedElement`
const handleTransform = (element) => {
	const cardsEl: HTMLElement | null = element?.querySelector('#cards');

	cardsEl?.remove();
};
```

### Drag started variant
```ts
function handleDndConsiderColumns(event) {
	if (event.detail.info.trigger === TRIGGERS.DRAG_STARTED) {
	const draggedEl: HTMLElement | null = document.getElementById(DRAGGED_ELEMENT_ID);
	const cardsEl: HTMLElement | null | undefined = draggedEl?.querySelector('#cards');

	cardsEl?.remove();
}
```
