### ISSUE TITLE
Object literal may only specify known properties

### ISSUE THREAD

**Issue by craigcosmo** [isaacHagoel/svelte-dnd-action#589]
![CleanShot 2024-06-14 at 11 05 35](https://github.com/isaacHagoel/svelte-dnd-action/assets/538657/20b6f879-e7de-448b-bfa8-d3ff041666ca)

**Comment by isaacHagoel** [comment]
Have you read the part about typescript in the readme?

**Comment by craigcosmo** [comment]
ok readme works
