### ISSUE TITLE
How to stop Items from moving up and down?

### ISSUE THREAD

**Issue by harishdurga** [isaacHagoel/svelte-dnd-action#590]
I am trying to build a form builder where from one section users will drag and drop form controls into a form. So what I am trying to achieve is that to prevent items inside the form controls dragzone not move but be draggable to another zone which is form in my case.

**Comment by isaacHagoel** [comment]
No move in what situation?
Can you describe it as
1. The user drags an item from section A
2. The user hovers over an item from section B
...
?
I assume you tried dropFromOthersDisabled

**Comment by harishdurga** [comment]
User tries to drag an item from Section A. when the user hovers that dragged element over any other elements from Section A, those elements may move up or down to make space for the item that is being dragged. I want to prevent this behavior.  Sorting of elements or dragging within the Section A should be disabled. But items should be dragged and dropped to Section B from Section A. And Items can be rearranged within Section B but not in Section A.

**Comment by harishdurga** [comment]
I think this particular example of unsortable list will help my case. 
https://svelte.dev/repl/e020ea1051dc4ae3ac2b697064f234bc?version=3.59.2

I am checking it

**Comment by isaacHagoel** [comment]
That's the right direction. Basically you can just do items=items in the
consider handler and it won't resort

**Comment by Donny-H** [comment]
@harishdurga did you find an easy way to do this? Something like:

`    function handleDndConsider(e:any) {
        e.detail.items = e.detail.items;
        speakers = e.detail.items;
    }
    function handleDndFinalize(e:any) {
        e.detail.items = e.detail.items;
        speakers = e.detail.items;
    }`

Is not working, everything is still sorting normally.

In the example there is a ton of things he's doing with aria but that seems extremely complex for some simple functionality 

(speakers is the array of items)

**Comment by isaacHagoel** [comment]
Do you mean speakers=speakers?
In your examples you still assign e.detail.items to speakers
