### ISSUE TITLE
Drop zone disappears

### ISSUE THREAD

**Issue by Stijn-Timmer** [isaacHagoel/svelte-dnd-action#595]
Hi there,

I’m using svelte-dnd in my project, and I’ve encountered an issue when dragging a drop zone that is already inside another drop zone. Specifically:

- When I attempt to drag a nested drop zone, it seems to disappear from my data object for a brief moment before reappearing.
- If I finalize the drag-and-drop operation during this brief period when the item is not visible, it disappears completely.

I’m probably missing something here, but I can’t figure out what’s going wrong. Any assistance or guidance on this issue would be greatly appreciated!

![issue-dnd](https://github.com/user-attachments/assets/6dc19f9f-5719-4567-8644-11c57d43dee6)

I managed to reproduce it in this simple repl:
https://svelte.dev/repl/e4c4659b11a4436a9e07dc5e5c936d87?version=4.2.18

**Comment by Stijn-Timmer** [comment]
I'm still encountering this problem and haven't been able to figure it out yet. I suspect I might be missing something small or overlooking a detail. Despite my efforts, I can't seem to identify the issue.

Before I close this issue due to inactivity, I wanted to check if anyone has any insights. Perhaps it's an oversight on my part rather than a project-related issue. 😛

**Comment by isaacHagoel** [comment]
Sorry. I missed this somehow when you opened it. I will have a look today
or tomorrow and update

**Comment by isaacHagoel** [comment]
@Stijn-Timmer I had a quick look. If you open the console you'd notice that your REPL throws an exception:
"Uncaught TypeError: Cannot read properties of undefined (reading 'type')"
Because it gets the shadow item and can't find the column id. There are various ways to fix this depending on the desired behaviour which is hard for me to figure out without context.
What should be the relationship between the top level and nested items. What should be allowed to be dropped into where?

**Comment by Stijn-Timmer** [comment]
Thank you, @isaacHagoel, for taking a peek.

Apps and directories should be able to swap places with each other.
Apps should be able to move in and out of a directory (to group them). A directory should not be able to be moved inside another directory.

**Comment by isaacHagoel** [comment]
So i should be able to pick app-3 up and drop it into app1, correct?

**Comment by Stijn-Timmer** [comment]
Sorry, 
You should be able to pick up app-3 and drag it out of the "directory" into root, but also able to drag lets say for example app-2 back into the directory.

Root being the first dndZone:
```
<section
  class="container"
  use:dndzone={{ items: data, flipDurationMs: 200 }}
  on:consider={handleDndConsiderRoot}
  on:finalize={handleDndFinalizeRoot}
>
```

<img width="1188" alt="image" src="https://github.com/user-attachments/assets/f1dc5059-914f-49ac-aba4-665990c25356">

**Comment by isaacHagoel** [comment]
I applied the nested zones fix mentioned in the README (as experimental) to solve the problem:
https://svelte.dev/repl/f4cf1bdc562849d59cb9ae905e488594?version=4.2.18
I also added `centreDraggedOnCursor` but that's just for convenience, not a part of the fix.

**Comment by Stijn-Timmer** [comment]
Thanks for the help, this is the behaviour i was looking for!
I'll close the issue.
