### ISSUE TITLE
svelte-dnd-action breaks store updates when updating the items in a dnd-zone when the tab is not active/visible

### ISSUE THREAD

**Issue by onecseven** [isaacHagoel/svelte-dnd-action#597]
Hey guys,

So basically my app tries to sync between open tabs by updating stores when ‘storage’ events fire. However, when the store update would change an items position in the dnd-zone, dnd throws a type error that breaks the whole store and leaves the tab unusable. The error occurs in src/pointerAction.js -> dndzone -> configure (line 535), when it tries to get the current mouse location, it’s getting undefined. I’m not sure if this is a bug or just a weird edge case. 

If anyone has any ideas on how to avoid that or even what in the library would need to change to fix it, I could try it and submit a PR. 

thanks!
tatiana

**Comment by isaacHagoel** [comment]
can you please provide more details? how can this be reproduced?

**Comment by onecseven** [comment]
Sure, I uploaded a repo with the minimal code necessary to trigger the bug. You can test it on pages: https://onecseven.github.io/dnd-issue/

The relevant code is here https://github.com/onecseven/dnd-issue/tree/main/src

**Comment by isaacHagoel** [comment]
I see. I am not sure what the exact root cause is (i will block some time
tomorrow to look more deeply into it) but in general the reason the
consider and finalize events are separate is exactly cases like this. Even
if I get this fixed, I don't think you want to persist intermediary states
(considers).

**Comment by onecseven** [comment]
Noted, will change that. Thanks for taking the time to look this over!

**Comment by isaacHagoel** [comment]
no problem. i fixed the problem in version 0.9.50
