### ISSUE TITLE
Drag and drop stickers onto a canvas

### ISSUE THREAD

**Issue by garysassano** [isaacHagoel/svelte-dnd-action#599]
I noticed that all the examples demonstrate moving elements from one stack to another, but none of them illustrate taking something like sticker images from a box and placing them onto a canvas.

**Comment by isaacHagoel** [comment]
When you say canvas, do you mean something like Figma, when you can drop
anywhere?
If yes, this is not the problem this library is trying to solve. I reckon I
can add it (it is not hard to implement) but it will be separate to
everything the lib does now
