### ISSUE TITLE
Order of execution of actions for child and parent inverted in Svelte 5

### ISSUE THREAD

**Issue by vini-brito** [isaacHagoel/svelte-dnd-action#605]
Hello! Wanted to ask if this change in Svelte 5 will affect this library: 

https://github.com/sveltejs/svelte/issues/13382

It shows that the order of executions is inverted for nested elements.

**Comment by isaacHagoel** [comment]
Thanks for the heads up. I see in the comments that they decided to make it
work like Svelte 4.

**Comment by vini-brito** [comment]
Nice! They hadn't commented that yet when I saw it.
