### ISSUE TITLE
Keep copy of item in original location while dragging

### ISSUE THREAD

**Issue by axekan** [isaacHagoel/svelte-dnd-action#616]
I'm trying to achieve a behavior close to [Pragmatic Drag and drop](https://atlassian.design/components/pragmatic-drag-and-drop/examples#list), but cant figure out how to get it all the way working. 

[Here is a Repl](https://svelte.dev/playground/6c36e4d0b97847439a8541b4563c2f66?version=3.59.2) of my progress.

The issue is that it when grabbing an item from the middle it will disappear, causing all other items to shift. I want to avoid this and just show a lower opacity version until i drop it (like in Pragmatic Drag and drop). It also doesn't seem to show the drop indicator in the correct spot. I think this is because it is a different size than the actual dragged item.

Is there any example of doing something like this with svelte-dnd-action? If not, what would be the best approach to do this?

**Comment by isaacHagoel** [comment]
Did you see the two dragula like examples in the readme?

**Comment by isaacHagoel** [comment]
Thinking about it further I wouldn't recommend using this library if you want this behaviour, which is basically the behaviour of the dnd implementation that's built into the browser. This library was written with the purpose of offering an alternative to that. It won't be easy and maybe not even possible to fully achieve this behaviour with code that was written specifically to create a much richer UX. You'll be basically fighting against the library

**Comment by axekan** [comment]
> Thinking about it further I wouldn't recommend using this library if you want this behaviour, which is basically the behaviour of the dnd implementation that's built into the browser. This library was written with the purpose of offering an alternative to that. It won't be easy and maybe not even possible to fully achieve this behaviour with code that was written specifically to create a much richer UX. You'll be basically fighting against the library

Thank you for answering. I see what you mean.
