### ISSUE TITLE
 README: All Svelte REPL links in Examples and Recipes section return 404

### ISSUE THREAD

**Issue by onursoyer** [isaacHagoel/svelte-dnd-action#622]
## Description
All Svelte REPL links in the "Examples and Recipes" section of README.md are broken (404). This likely happened due to changes in Svelte REPL's URL structure.

## Steps to Reproduce
1. Go to README.md
2. Check any REPL link in "Examples and Recipes" section
3. Get 404 error

**Comment by isaacHagoel** [comment]
There is a PR open that fixes it. Planning to merge tonight

**Comment by isaacHagoel** [comment]
https://github.com/isaacHagoel/svelte-dnd-action/pull/621
