### ISSUE TITLE
Allow to dynamically enable/disable dragging out of and/or dropping for a dnd-zone

### ISSUE THREAD

**Issue by isaacHagoel** [isaacHagoel/svelte-dnd-action#63]
Problem:
It is not possible to conditionally activate dragging/ dropping for a specific dndzone. For example, the container might be 'full' so further dropping shouldn't be allowed. Alternatively, maybe the App is in a state that doesn't allow taking elements out of a container temporarily.

Add two new boolean options:
`dragDisabled` and `dropDisabled`
both will default to false.
Both options should support being dynamically updated after initialisation (as any other option) to allow the library users to have control over what is allowed and when.

If `dragDisabled` is set to true, it should not be possible to drag elements out of the dndzone (drag start should be disabled, cursor shouldn't indicated dragging is possible).
If 'dropDisabled` is set to true, it should not be possible to drop any element into the dndzone (it shouldn't trigger any events when an element is dragged over it and it shouldn't be highlighted as a drop target when drag starts, dropping over it is like dropping over something that is not a dndzone).

Setting both of them to true, effectively disables the dnd-zone altogether.

If `dragDisabled` is set to true in the midst of an item from the container already being dragged, it should have no effect over the on-going dragged item (drag continues normally).
If `dropDisabled` is set to true in the midst of an item from the container already being dragged, it should have no effect until the element is dropped. In other words, the element will be allowed to return to its parent container either by dropping it there again or by dropping it outside of any container, ignoring the fact that drop is disabled (otherwise, where should it go? :)). After that, it won't be possible to drop other elements into the container (as long as the dropDisabled flag is set to true).

Example (pseudocode):
```html
<section use:dndzone={{items, dragDisabled:true, dropDisabled:true}} on:consider=... on:finalize=...>
    ...
</section>
```
 
 this should resolve #61 and #62

**Comment by isaacHagoel** [comment]
Option 2:
Make the consider and finalize events cancellable, allowing users to run preventDefault() in order to cancel them.
[See experiment here](https://svelte.dev/repl/48f3a06eb65549a0aaeaf1b4d9e4576f?version=3.23.0).

Let's examine how the this can be used:
1. User wants to prevent dragging elements out of a dndzone - user will need to add the following logic to the consider handler: if the number of items in e.detail.items is smaller than the original number of items, cancel the event, otherwise allow it. Notice that it means that the 'consider' handler has to make a distinction between the original items and the items the list currently has (which might include a placehoder element if something is dragged over the list)
2. User wants to prevent dropping elements in the dropZone - consider and finalize handlers need to preventDefault if the number of items is larger than the original number (because u still want to allow taking things out)

Potential issues from the library point of view:
1. how does highlighting of all valid drop zones (this feature exists now) work?
2. what should happen when the consider event is cancelled? should this dnd zone be marked as 'out of the game' until the element is dropped or should it be retried if the user drags over it again?
3. what happens if the user doesn't cancel consider but cancels finalize (the placeholder element stays stuck in the list or the element that was taken out stay stuck outside of the list)?

**Comment by isaacHagoel** [comment]
After giving it more thought, I decided to go with the original approach. Instead of `dropDisabled`, the option will be called `dropFromOthersDisabled` because it is more descriptive of what it does.

**Comment by zba** [comment]
just tried it and it not works in 0.2.0 very simple dropzone with

```
<section dropFromOthersDisabled={true} dragDisabled={true} use:dndzone={{items: tasks, flipDurationMs}} on:consider={handleDndConsider} on:finalize={handleDndFinalize}>
```

ignores both new attributes :/

**Comment by isaacHagoel** [comment]
@zba you don't seem to be passing it into the dndzone.
try:
```html
<section use:dndzone={{items: tasks, flipDurationMs, dropFromOthersDisabled:true dragDisabled:true}} on:consider={handleDndConsider} on:finalize={handleDndFinalize}>
```

**Comment by zba** [comment]
ah sorry, seems at morning I just not concentrated :) thanks

**Comment by isaacHagoel** [comment]
no worries. let me know if i can help in any other way.
it occurred to me that a nice way to achieve max items could be using a reactive variable (rather than doing anything in the consider or finalize handlers).
something like
```html
<script>
const MAX_ALLOWED = 3;
let items = [];
$: dropFromOthersDisabled = (items.length === MAX_ALLOWED); 
...
</script>
<section use:dndzone={{items, dropFromOthersDisabled}} ...>
```
