### ISSUE TITLE
Only draggable and Only droppable zones

### ISSUE THREAD

**Issue by farskid** [isaacHagoel/svelte-dnd-action#74]
There would be cases in which you'd want some zones to be draggable only (items can be dragged out of them, no drop in them) or droppable only (items can be dropped in it, nothing can be dragged out of it). Take the screenshot below for an example. in this case there are 3 lists containing a number of items. these lists should be only draggable and nothing should be able to be dropped int them.
on top of them, there is a droppable only zone that you could drop items onto them (items coming from lists) and nothing should be able to be dragged out of them.

![image](https://user-images.githubusercontent.com/8332043/83542018-1429f380-a503-11ea-886a-8895a572c3fb.png)

How would you be able to achieve this using current set of API in the lib?

I already attempted to solve it using `type` but that gets nowhere as all of them should share the same type and it makes all of them both draggable and droppable.

Also tries using `dropFromOthersDisabled: true` on only droppable lists but it doesn't get to the intended behaviour.

**Comment by isaacHagoel** [comment]
It should be
dropFromOthersDisabled: true on the bottom lists 
dragDisabled: true on the top lists

**Comment by isaacHagoel** [comment]
@farskid hi, did U the try my suggestion above?

**Comment by farskid** [comment]
@isaacHagoel Yeah. I get runtime error since the drop only area doesn't have any children.
![image](https://user-images.githubusercontent.com/8332043/83925596-35534400-a790-11ea-986a-1f12e9fe2c9f.png)

**Comment by farskid** [comment]
A reproducable example can be found here:
https://codesandbox.io/s/blissful-flower-oexmm?file=/App.svelte

**Comment by isaacHagoel** [comment]
in your example, it looks like the 'dragZone' has no consider or finilize handlers.

**Comment by farskid** [comment]
Adding consider and finalize to dragZones doesn't seem to solve it either.

**Comment by isaacHagoel** [comment]
I didn't have a chance to debug your code but please make sure that you can drag and drop items within the same list. if that doesn't work there might be an issue with your consider/finalize handlers (the library relies on your code to update the data list correctly).
Regardless, I fixed an issue with nested container (not sure if it was affecting you). Please use version 0.2.3.
Lastly, here is a [REPL](https://svelte.dev/repl/fe598a2a27cd40c8a12caae01d9da440?version=3.23.0) that does what you need (if I understand you correctly) using the method I proposed.

**Comment by farskid** [comment]
Thanks for the demo. Yeah the way I was updating the items was apparently wrong but anyhow I want the drop only area to be inside each column and only accept cards from other columns than the one it's in. I went with having to put a drop only area on top of the columns because I wanted the `shadowElIndex` to always be 0 (dropped items always be dropped on top), so I ended up patching the code in a way that enforces `shadowElIndex` to always be zero. another thing I planned to achieve was to disable sorting of cards inside the same column so I also ended up disabling the code inside `handleDraggedIsOverIndex`.

```
diff --git a/node_modules/svelte-dnd-action/src/action.js b/node_modules/svelte-dnd-action/src/action.js
index 9919642..41446b3 100644
--- a/node_modules/svelte-dnd-action/src/action.js
+++ b/node_modules/svelte-dnd-action/src/action.js
@@ -90,7 +90,8 @@ function handleDraggedEntered(e) {
     items = items.filter(i => i.id !== shadowElData.id)
     console.debug(`dragged entered items ${JSON.stringify(items)}`);
     const {index, isProximityBased} = e.detail.indexObj;
-    shadowElIdx = (isProximityBased && index === e.currentTarget.children.length - 1)? index + 1 : index;
+    // shadowElIdx = (isProximityBased && index === e.currentTarget.children.length - 1)? index + 1 : index;
+    shadowElIdx = 0;
     shadowElDropZone = e.currentTarget;
     items.splice( shadowElIdx, 0, shadowElData);
     dispatchConsiderEvent(e.currentTarget, items);
@@ -114,11 +115,11 @@ function handleDraggedIsOverIndex(e) {
         console.debug('drop is currently disabled');
         return;
     }
-    const {index} = e.detail.indexObj;
-    items.splice(shadowElIdx, 1);
-    items.splice( index, 0, shadowElData);
-    shadowElIdx = index;
-    dispatchConsiderEvent(e.currentTarget, items);
+    // const {index} = e.detail.indexObj;
+    // items.splice(shadowElIdx, 1);
+    // items.splice( index, 0, shadowElData);
+    // shadowElIdx = index;
+    // dispatchConsiderEvent(e.currentTarget, items);
 }
 
 /* global mouse/touch-events handlers */

```

**Comment by isaacHagoel** [comment]
Interesting. So you would like to disable the ability to move an element to a different index in the list?
If so and if you'd like it to become a feature, can you please describe your usecase?

**Comment by isaacHagoel** [comment]
@farskid is this still relevant for you?

**Comment by isaacHagoel** [comment]
closing for now. feel free to re-open if this is still needed.
