### ISSUE TITLE
enable selection

### ISSUE THREAD

**Issue by FSou1** [isaacHagoel/svelte-dnd-action#78]
Is there a chance to do not disable text selection of a draggable item? The best solution is to add an icon that is turning on draggable mode, otherwise, array items are still selectable.

**Comment by isaacHagoel** [comment]
I think it makes sense to not disable selection when the `dragDisabled:true` option is passed in and as long as there is no active drag action taking place (if there is I will disable selection again). Will that do the trick for you? it should allow u to add a toggle like you are describing.

If so, I can play with it to see if it introduces any strange side-effects. Before disabling it, it was causing a lot of pain by scrolling the screen when u dragged over stuff and so on.

**Comment by FSou1** [comment]
Yes, it make sense.

пн, 8 июн. 2020 г., 2:45 Isaac Hagoel <notifications@github.com>:

**Comment by isaacHagoel** [comment]
@FSou1 done. toggling the dragDisabled option now also toggles user-select
