### ISSUE TITLE
add hover styling

### ISSUE THREAD

**Issue by spooky** [isaacHagoel/svelte-dnd-action#85]
Is it possible to change styling for the drop target that a currently dragged item is hovered over (so in the REPL example, change styling of only one of the TODO/DOING/DONE columns when an item is being dropped)?

**Comment by isaacHagoel** [comment]
currently not but could be added. what did you have in mind (as far as API goes)?

**Comment by spooky** [comment]
I'm thinking { hoverClass: "foo" } as one of the options.

**Comment by isaacHagoel** [comment]
sorry for the delay. i've been super busy. I am pondering the classes idea. i think it has some advantages but since svelte mingles the class names the classes used will have to be declared in a :global style block. I will look into it.

**Comment by isaacHagoel** [comment]
This is now possible using the new information that was added to the dispatched events - they now have an `info` object in addition to `items`. You can apply new styling when you get the DRAGGED_ENTERED event `trigger` and remove it when you get DRAG_LEFT (and probably also drop related triggers). 
Let me know if that doesn't work out for you and/or if I can help.
Closing this for now.
