### ISSUE TITLE
can it be easily made to work with maps?

### ISSUE THREAD

**Issue by zahachtah** [isaacHagoel/svelte-dnd-action#87]
This is so useful I will definitely change my application back to using array storage again, but I originally choose a [map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) for simplicity in accessing items (but keeping the iterable functionality). I haven't used actions enough to be very well versed in judging if this is possible to add? Thanks for this nice package!

**Comment by zahachtah** [comment]
The question may come up in the future but for now, I simply will change to using arrays for this case

**Comment by isaacHagoel** [comment]
Hi @zahachtah,
Thanks for the issue. Can you please provide a code snippet that illustrates how you were trying to use a map?
