### ISSUE TITLE
array in object?

### ISSUE THREAD

**Issue by zahachtah** [isaacHagoel/svelte-dnd-action#95]
This is amazingly useful and neat!

question: I happen to pass on the item array inside an object, i.e.

instead of 

`let items = [
    		{id: 1, name: "item1"},
    		{id: 2, name: "item2"},
    		{id: 3, name: "item3"},
    		{id: 4, name: "item4"}
    ]; `

I have 

`let node = {
        items: [
    		{id: 1, name: "item1"},
    		{id: 2, name: "item2"},
    		{id: 3, name: "item3"},
    		{id: 4, name: "item4"}
                  ];
         other: 'somehting'
}; `

but I get a compile error if I now use

`use:dndzone={{node.items, flipDurationMs}}`

it doesn't like the .-notation

Do you know of any simple trick? I would very much need to keep the structure of node.items as node also carries other information.

Thanks for this!!

**Comment by isaacHagoel** [comment]
```
se:dndzone={{items:node.items, flipDurationMs}}
```
should work

**Comment by zahachtah** [comment]
Thank you!, that worked, but stuck at another issue downstream due to a somewhat complicated setup. I'll work on it today to see if I can solve it. I need to have recursive components... :-/  Maybe I can ask for advice again later if I can get a minimal working example in svelte.repl?

**Comment by isaacHagoel** [comment]
Sure. I'm happy to help

**Comment by zahachtah** [comment]
This is an [example](https://svelte.dev/repl/3a8bfab2bb3a464eb5856c3c6dcc6285?version=3.24.0) of what I want to do and how far I got

I have a list of nodes (node1, node1....etc)

some contain items arrays for other nodes, and others are leaf-nodes, i.e don't have items but only content. These are trees of nodes.

I use the component Content.svelte recursively to create the structure I want, as you can see when you click and open the svelte.REPL link above. 

I can add the `<section use:dndzone={{items:node.items, flipDurationMs}} on:consider={handleDndConsider} on:finalize={handleDndFinalize}> ... </section>` and svelte-dnd-action seems to get set up ok and one can even move the nodes.

But they just disappear on the drop.

Maybe some id reference or the item list reference gets lost during my setup? I need to use string as id, I hope that is not an issue.

Any idea on how to make this work would be greatly appreciated!

**Comment by zahachtah** [comment]
I added output to console in the 

`	function handleDndFinalize(e) {
		items = e.detail.items;
		console.log(e)
	}`

and it shows:

`message: "items is not defined"`

**Comment by zahachtah** [comment]
It says "items is not defined" in the error message

**Comment by isaacHagoel** [comment]
looks like in your consider and finalize handlers you are assigning to `items` (which is not defined) rather than to `node.items`.
Check out [this REPL](https://svelte.dev/repl/5e26e6fdf013426eb034c5f9fcb460ed?version=3.24.0)

**Comment by zahachtah** [comment]
Awesome, thanks! I played around a bit more. I added a bind and display the JSON under the dnd areas. 

1) when one moves an item and drops it one node changes name to isDndShadowItem and keeps that name, i.e. the "node4" id name disappears....Any idea what that is?

2)  It's really neat that one can drop e.g. node 4 (with its subnodes) into node3's items and it works. However, once one has done that one cannot move an items among node4's items nor drop any other item into that. 

I don't mean to take your time on this, but if you have any idea [here's the REPL](https://svelte.dev/repl/bfd224ebe3b64a6bb89b809b91f75d7d?version=3.24.0) showing the nodes list while moving (sorry, unformatted)

**Comment by zahachtah** [comment]
Ah, the branch nodes lack an id...... will fix

**Comment by isaacHagoel** [comment]
I can't play with it right now, but normally for nested dnd zones you would
use the "type" attribute to control what can be dropped into what. there is
an example in the REPL that is linked to in README.md

**Comment by zahachtah** [comment]
that didn't fix the issues 1 and 2 above though....

[REPL](https://svelte.dev/repl/bfd224ebe3b64a6bb89b809b91f75d7d?version=3.24.0)

**Comment by zahachtah** [comment]
of course, thanks for your help!

**Comment by zahachtah** [comment]
just for reference: 

Everything works almost out of the box, one can drag individual items between the same levels and between levels. 

dragging a container that has its own items creates an issue so that one cannot drop other items into that container's array anymore. Will investigate.

**Comment by isaacHagoel** [comment]
Hi, 
Could you pls clarify what is the behaviour you are trying to achieve? should it be possible to mix small and large items at the same level or should small items always reside within the large items?

**Comment by zahachtah** [comment]
Mixing large and small items, creating nested views. I understand the use of type for restricting what can be dropped but I was needing unrestricted reshuffling here. Also, it seems on drop it doesn’t remove the dndShadow item property, or is that intentional?

**Comment by isaacHagoel** [comment]
It shouldn't but it's most likely a symptom, not the actual issue.
Can U pls provide exact steps to reproduce and expected behaviour?

**Comment by zahachtah** [comment]
[Here is a REPL](https://svelte.dev/repl/bfd224ebe3b64a6bb89b809b91f75d7d?version=3.24.0) with exact description, steps, and expected behavior.

**Comment by isaacHagoel** [comment]
Thanks. This is very helpful. I'll try to find some time to debug it
during the weekend.
I have never encountered this usecase before :)

**Comment by zahachtah** [comment]
This is by far the slickest dnd implementation I have come across. Very nice idea and implementation. 

Btw, Is it possible to "assign" a sub-div" within a div to act as the "handle" by which one can drag and drop? In case one doesn't want the entire div to be a "dragging handle". Sorry, I just get ideas while playing with this. Seems somewhat more complicated.

**Comment by isaacHagoel** [comment]
Your example does not have unique IDs. for example the id: `node2` is used twice. Can you please fix it such that all the ids are unique?
About drag handles see my response on #86

**Comment by zahachtah** [comment]
Actually they do have unique id's. I added a check at the bottom. 

I guess what you are seeing is the id's are also in the items array? and I used one item twice (i.e. id node13 was in two different item lists. That actually seems to work!?). But I changed that for now. The problem described persists

**Comment by isaacHagoel** [comment]
sorry, i misunderstood the setup. yes, they are unique. 
I will need to spend some more time to fully nail it down but it looks like the library assumes an item cannot be dragged over two dropzones of the the same type at the same time. The overlap in this case (once node 4 is dropped between items 9 and 10) seems to cause ignoring the dropzone inside of node4. i didn't look into the leftover shadowitem property yet.

**Comment by isaacHagoel** [comment]
I looked into the issue with the leftover isDndShadowItem property. In fact there is no issue.
If u look at the finalize event you printing you will see the property is not there. 
<img width="655" alt="Screen Shot 2020-08-01 at 7 51 20 pm" src="https://user-images.githubusercontent.com/20507787/89099279-628b3e00-d431-11ea-9b69-12d3c6563eba.png">
the reason you see it in the JSON stringify output is that svelte doesn't realize that it needs to update it post drop. To fix it, change your finalize function to
```javascript
	function handleDndFinalize(e) {
		node.items = e.detail.items;
		nodes = {...nodes};
		console.log(e)
	}
```

**Comment by isaacHagoel** [comment]
About the other issue, the key to fixing it lies [in observer.js in the loop that starts in line 51](https://github.com/isaacHagoel/svelte-dnd-action/blob/f25f2e77efb3f399c094ffd59d8592ec34a377aa/src/helpers/observer.js#L51).
You can see that it loops over the dropzones (of the relevant type) and once it finds one that the dragged element is over - it breaks. Changing the order in which it loops to somehow take into account the nesting (start from the inside out) - should solve the problem.
Not sure I will get to this soon as there are more urgent issues. If you'd like to give it a shot pls let me know.

**Comment by isaacHagoel** [comment]
@zahachtah Actually I think that simply running that loop in a reverse order might do the trick (because Svelte renders top down which determines the registration order). Would you like to give it a shot?

**Comment by zahachtah** [comment]
That makes sense. I am not good at all at javascript programming, but I looked up reversing for .. of .. loops and there doesn't seem to be a built in way. A hacky way then would be to:

`for (var i = dropZones.length - 1; i >= 0; i--) {
	const dz = dropZones[i]
        ......
}`

I'll download the REPL and try this today.

**Comment by isaacHagoel** [comment]
you'll need to clone the library and run it locally. if it is too much of
a hassle I will try it out at some point. hopefully this week

**Comment by zahachtah** [comment]
No hassle, just skills :-)

will try today

**Comment by zahachtah** [comment]
Quick progress-update. You are right in that svelte renders top-down initially. But when you move something svelte doesn't seem to redo that render so the order gets disturbed. 

So, my solution will be to check the number of other items each item contains and based on that create an index that gives the right loop-order.

should have something end of tomorrow the latest

**Comment by zahachtah** [comment]
Ok, have it working but am best at scientific programming so my javascript skills are not very well developed. So the code is more linear and not as elegant as a good javascript programmer can do. So instead of submitting a PR I just show you how I did. It should be simple to make this prettier for you, but the algorithm is pretty easy to see:

first I need two functions (I divided them into two since they do two different things):

```function countContains(arrayObj) {
    var counts = [];
    for (var i=0; i<arrayObj.length;i++){
        var count=0
        for (var j=0; j<arrayObj.length;j++) {
            if (arrayObj[i].contains(arrayObj[j])) { count++ }
        }
        counts.push(count)
    }
    return counts
}

function sortId(array) {
    return array.map((val, ind) => {return {ind, val}}).sort((a, b) => {return a.val > b.val ? 1 : a.val == b.val ? 0 : -1 }).map((obj) => obj.ind);
}```

Then I had to add some code before the loop and change the loop slightly:

```
const Z=Array.from(dropZones)
const ind=sortId(countContains(Z))
let z=ind.map(i=>Z[i])
for (const dz of z) {
    ...........
```
steps:
1) first I make an array from the dropZones Map (not sure if this is needed)
2) I get the count of items contained within each item (countContains) and then generate a sorting array based on that (sortId)
3) I now generate a new Array in the correct order
4) we can now iterate on this new array.

With this algorithm I can now drop a parent container into a list and then drop items into that one. Seems all kind of hierarchies are possible.


I hope this helps, and sorry for nut making a PR, but You'd have to rewrite it to not look amateurish anyway I presume....

**Comment by isaacHagoel** [comment]
:)
Thanks for this. It sure does help and saves time for me.
Don't be hard on yourself. problem solving skills are more important than elegance.
There is one issue I need to address before I attend to this. I guess you can use your version for now to continue developing your app until this is fixed here, right?

**Comment by zahachtah** [comment]
Yes, i can use this until then. Thanks for the tips on how to solve it. Learned much

**Comment by zahachtah** [comment]
How sensitive is this to the suggested structure:

```
    <div use:dndzone="{{items: myItems, ...otherOptions}}" on:consider={handler} on:finalize={handler}>
         {#each myItems as item(item.id)}
            <div>this is now a draggable div that can be dropped in other dnd zones</div>
         {/each}   
    </div>
```
For example, if I have 
```
    <div use:dndzone="{{items: myItems, ...otherOptions}}" on:consider={handler} on:finalize={handler}>
      <div>
         {#each myItems as item(item.id)}
            <div>this is now a draggable div that can be dropped in other dnd zones</div>
         {/each}   
      </di>
    </div>
```

or 
```
    <div use:dndzone="{{items: myItems, ...otherOptions}}" on:consider={handler} on:finalize={handler}>
         {#each myItems as item(item.id)}
           <div>
             <div>this is now a draggable div that can be dropped in other dnd zones</div>
           </div>
         {/each}   
    </div>
```
or 
```
<div>
    <div use:dndzone="{{items: myItems, ...otherOptions}}" on:consider={handler} on:finalize={handler}>
         {#each myItems as item(item.id)}
           <div>
             <div>this is now a draggable div that can be dropped in other dnd zones</div>
           </div>
         {/each}   
    </div>
</div>
```

any of those scenarios that could potentially give issues? Trying to understand an issue I have with my site.

**Comment by isaacHagoel** [comment]
The library treats the direct children of the element that is annotated with the `use` directive and draggable items. 
The dragaable items can have children and that shouldn't be a problem.
This is invalid:
```
<div use:dndzone="{{items: myItems, ...otherOptions}}" on:consider={handler} on:finalize={handler}>
         {#each myItems as item(item.id)}
           <div>
             <div>this is now a draggable div that can be dropped in other dnd zones</div>
           </div>
         {/each}   
    </div>
```
The library will see X items in the list but only one direct child (the wrapper div inside of the `each` block)

**Comment by isaacHagoel** [comment]
@zahachtah I have fixed the issue and have created pull request #103. I have simplified your proposed solution a bit for better performance.
I have tested it locally with your example from the REPL and it all seems to be behaving correctly
Ideally, I would like you to verify that it solves all of your issues before I merge. 
Can you please checkout branch `95-super-nested-support` and give it a try?

**Comment by zahachtah** [comment]
perfect! works flawless.

**Comment by isaacHagoel** [comment]
thx for verifying. merged
